from functools import partial

from polars import Date, Datetime, Float64, Int64

from aemo_etl.configuration import BRONZE_BUCKET, LANDING_BUCKET
from aemo_etl.definitions.utils import asset_check_factory, post_process_hook
from aemo_etl.factory.definition import (
    GetMibbReportFromS3FilesDefinitionBuilder,
)
from aemo_etl.parameter_specification import (
    PolarsDataFrameReadScanDeltaParamSpec,
    PolarsDataFrameWriteDeltaParamSpec,
    PolarsDeltaLakeMergeParamSpec,
)
from aemo_etl.register import definitions_list, table_locations
from aemo_etl.util import get_metadata_schema, newline_join

#     ╭────────────────────────────────────────────────────────────────────────────────────────╮
#     │                      define table and register to table locations                      │
#     ╰────────────────────────────────────────────────────────────────────────────────────────╯


table_name = "bronze_vicgas_int126_dfs_data"

s3_prefix = "aemo/vicgas"

s3_file_glob = "int126*"

s3_table_location = f"s3://{BRONZE_BUCKET}/{s3_prefix}/{table_name}"

primary_keys = (
    "dfs_version",
    "gas_date",
)

upsert_predicate = newline_join(
    *[f"s.{col} = t.{col}" for col in primary_keys], extra="and"
)

table_schema = {
    "dfs_version": Int64,
    "gas_date": Date,
    "last_update_datetime": Datetime(time_unit="ms", time_zone="Australia/Melbourne"),
    "previous_day_min": Float64,
    "max": Float64,
    "overnight_min": Float64,
    "average_wind_speed": Float64,
    "sunshine": Int64,
    "effective_temperature": Float64,
    "dfs_edd": Float64,
    "total_demand_forecast": Int64,
    "current_date": Datetime(time_unit="ms", time_zone="Australia/Melbourne"),
}

schema_descriptions = {
    "dfs_version": "Demand forecast version",
    "gas_date": "Gas Day date the temperature data applies to (e.g. 30 Jun 2007)",
    "last_update_datetime": "Time data obtained and loaded into AEMO's database (e.g. 05:00:00)",
    "previous_day_min": "Previous day over night minimum temperature (NULL from 15 April 2024)",
    "max": "Maximum temperature for day (NULL from 15 April 2024)",
    "overnight_min": "Overnight minimum temperature (NULL from 15 April 2024)",
    "average_wind_speed": "Average wind speed (knots) (NULL from 15 April 2024)",
    "sunshine": "Hours of sunshine (NULL from 15 April 2024)",
    "effective_temperature": "Effective temperature calculated by AEMO's Demand Forecasting System (DFS)",
    "dfs_edd": "Effective Degree Day (EDD) calculated by AEMO's Demand Forecasting System (DFS)",
    "total_demand_forecast": "AEMO's total daily demand forecast for the gas day calculated by AEMO's Demand Forecasting System (DFS)",
    "current_date": "Date and time report produced (e.g. 30 June 2005 1:23:56)",
}

report_purpose = """
This report provides AEMO's calculated effective temperature, effective degree day (EDD) and total system demand forecast
(representing system demand and site specific demand) for the DWGM from AEMO's Demand Forecasting System (DFS).

This data can be used to validate forecasting methodologies against AEMO's DFS. It is also used to validate AEMO's demand
forecast where there has been a demand override in the scheduling process.

Not every demand generated by the AEMO DFS is used in the scheduling process. Participants should reference INT108
Schedule Run Log to determine the Demand Forecasts used for each schedule.

The INT108 forecast_demand_version identifies the forecast used by AEMO in generating a schedule.

This report contains data for:
- the current gas day
- 1-day ahead
- 2 days ahead
- the previous 7 days

Each report therefore can contain data for up to 10 days.
Each row of the report contains data for one generated nodal forecast.

From 15 April 2024, AEMO has a new weather forecast data provider. The following fields will be NULL:
- previous_day_min
- max
- overnight_min
- average_wind_speed
- sunshine
"""

table_locations[table_name] = {
    "table_name": table_name,
    "table_type": "delta",
    "glue_schema": "aemo",
    "s3_table_location": s3_table_location,
}


#     ╭────────────────────────────────────────────────────────────────────────────────────────╮
#     │                                register the definition                                 │
#     ╰────────────────────────────────────────────────────────────────────────────────────────╯


definition_builder = GetMibbReportFromS3FilesDefinitionBuilder(
    key_prefix=["bronze", "aemo", "vicgas"],
    io_manager_key="s3_polars_deltalake_io_manager",
    asset_metadata={
        "description": report_purpose,
        "dagster/column_schema": get_metadata_schema(table_schema, schema_descriptions),
        "s3_polars_deltalake_io_manager_options": {
            "write_delta_options": PolarsDataFrameWriteDeltaParamSpec(
                target=s3_table_location,
                mode="merge",
                delta_merge_options=PolarsDeltaLakeMergeParamSpec(
                    predicate=upsert_predicate,
                    source_alias="s",
                    target_alias="t",
                ),
            ),
            "scan_delta_options": PolarsDataFrameReadScanDeltaParamSpec(
                source=s3_table_location
            ),
        },
    },
    group_name="aemo",
    name=table_name,
    s3_source_bucket=LANDING_BUCKET,
    s3_source_prefix=s3_prefix,
    s3_file_glob=s3_file_glob,
    s3_target_bucket=BRONZE_BUCKET,
    s3_target_prefix=s3_prefix,
    table_schema=table_schema,
    check_factories=[partial(asset_check_factory, primary_keys=primary_keys)],
    table_post_process_hook=partial(
        post_process_hook, primary_keys=primary_keys, table_schema=table_schema
    ),
)

definitions_list.append(definition_builder.build())
