#!/usr/bin/env bash

pulumi config set --secret cognito_client_id "$COGNITO_DAGSTER_AUTH_CLIENT_ID"
pulumi config set --secret cognito_server_metadata_url "$COGNITO_DAGSTER_AUTH_SERVER_METADATA_URL"
pulumi config set --secret cognito_token_signing_key_url "$COGNITO_TOKEN_SIGNING_KEY_URL"
pulumi config set --secret cognito_client_secret "$COGNITO_DAGSTER_AUTH_CLIENT_SECRET"
pulumi config set website_root_url "$WEBSITE_ROOT_URL"
pulumi config set developer_email "$DEVELOPER_EMAIL"
