import json
from importlib.resources import files
from typing import Final, TypedDict, cast

from polars import Datetime, String
from polars._typing import PolarsDataType

_MANIFEST_PACKAGE: Final = "aemo_etl.defs.raw.sttm"
_MANIFEST_RESOURCE: Final = "source_tables.json"

_INGESTION_METADATA_SCHEMA: Final[dict[str, PolarsDataType]] = {
    "ingested_timestamp": Datetime("us", time_zone="UTC"),
    "ingested_date": Datetime("us", time_zone="UTC"),
    "surrogate_key": String,
    "source_file": String,
}

_INGESTION_METADATA_DESCRIPTIONS: Final[dict[str, str]] = {
    "ingested_timestamp": "timestamp which the data was ingested",
    "ingested_date": "date which the data was ingested, this is time zeroed utc",
    "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
    "source_file": "source file",
}


class STTMManifestColumn(TypedDict):
    name: str
    not_null: bool
    primary_key: bool
    description: str


class STTMManifestLandingOnlyGap(TypedDict):
    report_id: str
    reason: str


class STTMManifestReport(TypedDict):
    report_id: str
    report_name: str
    name_suffix: str
    glob_pattern: str
    description: str
    surrogate_key_sources: list[str]
    source_columns: list[STTMManifestColumn]


class STTMManifestSource(TypedDict):
    title: str
    section: str
    original_pdf_url: str


class STTMSourceTablesManifest(TypedDict):
    manifest_version: int
    source: STTMManifestSource
    reports: list[STTMManifestReport]
    landing_only_gaps: list[STTMManifestLandingOnlyGap]


def load_sttm_source_tables_manifest() -> STTMSourceTablesManifest:
    manifest_text = (
        files(_MANIFEST_PACKAGE)
        .joinpath(_MANIFEST_RESOURCE)
        .read_text(encoding="utf-8")
    )
    return cast(STTMSourceTablesManifest, json.loads(manifest_text))


def get_sttm_report_manifest(report_id: str) -> STTMManifestReport:
    normalized_report_id = report_id.upper()
    for report in load_sttm_source_tables_manifest()["reports"]:
        if report["report_id"] == normalized_report_id:
            return report
    raise KeyError(f"unknown STTM report: {report_id}")


def sttm_report_schema(report: STTMManifestReport) -> dict[str, PolarsDataType]:
    source_schema = {column["name"]: String for column in report["source_columns"]}
    return {**source_schema, **_INGESTION_METADATA_SCHEMA}


def sttm_report_schema_descriptions(report: STTMManifestReport) -> dict[str, str]:
    source_descriptions = {
        column["name"]: column["description"] for column in report["source_columns"]
    }
    return {**source_descriptions, **_INGESTION_METADATA_DESCRIPTIONS}


def sttm_landing_only_gap_report_ids() -> tuple[str, ...]:
    return tuple(
        gap["report_id"]
        for gap in load_sttm_source_tables_manifest()["landing_only_gaps"]
    )
