from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int039b_v4_indicative_locational_price_1",
    glob_pattern="int039b_v4_indicative_locational_price_1*",
    schema={
        "gas_date": String,
        "node_name": String,
        "ti": Int64,
        "nodal_price_value_gst_ex": Float64,
        "transmission_id": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Starting hour of gas day being reported e.g. 30 Jun 2007 06:00:00",
        "node_name": "Name of node at which price applies",
        "ti": "Hour index (1-24)",
        "nodal_price_value_gst_ex": "Nodal price ($)",
        "transmission_id": "Schedule number these prices are related to",
        "current_date": "Date and Time Report Produced",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report lists the hourly locational (nodal) prices generated by the MCE
        (market clearing engine) from each approved schedule in the gas day and upon
        approval of subsequent re-schedule for the previous 7 days. The report contains
        hourly pricing data for each locational node for the previous 7 days. Therefore
        it is expected that each node will reflect 24 prices per gas day (commencing
        6:00 AM daily) for the past 7 days. Each report contains the pricing data for
        each hour of the gas day per locational node across a 7-day period. It is
        expected that the report will reflect: - date of the gas day - name of
        locational node - each hourly index for the gas day (ie 1 to 24) - price per
        hour excluding GST - schedule number which price relate to - the date and time
        when the report was produced. As each report includes the gas date, followed by
        each locational node's 24 hourly prices across 7 days, this means that if there
        are 30 locational nodes in the one day, then this would mean 30 multiplied by 24
        hourly prices. Therefore the user can expect to see 720 rows of data for that
        gas day, multiplied by 7 days which will give potentially a total of 5040 rows
        of data per report for the previous 7 days.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "node_name", "ti", "transmission_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
