from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int042_v4_weighted_average_daily_prices_1",
    glob_pattern="int042_v4_weighted_average_daily_prices_1*",
    schema={
        "gas_date": String,
        "imb_dev_wa_dly_price_gst_ex": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day for the reference prices e.g. 30 Jun 2007",
        "imb_dev_wa_dly_price_gst_ex": "Imbalance and deviation weighted average daily price",
        "current_date": "Date and Time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is available to Participants for use in settlement for off-market
        hedge contracts. Potentially it is also useable as benchmark price of gas in
        contract negotiations. Traders may wish to user the report to get a daily
        perspective of the value of gas in a day. This report can be read in conjunction
        with INT041 which relates to the actual market ex ante prices and the calculated
        "reference prices". This report provides a weighted average daily price based on
        the total imbalance and deviation payments. The report provides another
        perspective of the market pricing of gas. Again these average prices are only
        for information and analysis purposes and are not used in the actual settlement
        of the gas day. Each report contains the: - gas date - weighted average daily
        price for imbalance and deviation (GST exclusive) - date and time when the
        report was produced. The report should contain one row representing each gas day
        in a month. Therefore in a month consisting of 30 days, the user can expect to
        see 30 rows of data.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
