from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int079_v4_total_gas_withdrawn_1",
    glob_pattern="int079_v4_total_gas_withdrawn_1*",
    schema={
        "gas_date": String,
        "unit_id": String,
        "qty": Float64,
        "qty_reinj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported e.g. 30 Jun 2007",
        "unit_id": "Unit of measurement (GJ)",
        "qty": "Total Gas withdrawn Daily",
        "qty_reinj": "Total Net Gas withdrawn Daily (Withdrawals less re-injections)",
        "current_date": "Date and time report produced e.g. 30 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides a view of the total quantity of gas that is flowing in the
        DTS on a given day. Retailers may use this information as an input to their
        demand forecasts or to estimate their market share. Participants must be aware
        that the data is of operational quality and not settlement quality, and is
        therefore subject to revision. The report contains metering data for the prior
        gas day. In the context of this report, re-injections represent the flow to the
        transmission pipeline system (TPS) from the distribution pipeline system (DPS)
        at times of low pressure and low demand. The first quantity reported, "qty",
        includes re-injections. It should be noted that for a single day, multiple
        entries can exist. Initial uploads of data for a given date can be incomplete
        when it is first reported and updates arriving later into AEMO's system will
        cause multiple entries to exist. Each report contains details of the withdrawals
        that occurred on the previous seven gas days.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
