from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int029a_v4_system_notices_1",
    glob_pattern="int029a_v4_system_notices_1*",
    schema={
        "system_wide_notice_id": Int64,
        "critical_notice_flag": String,
        "system_message": String,
        "system_email_message": String,
        "notice_start_date": String,
        "notice_end_date": String,
        "url_path": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "system_wide_notice_id": "Id of the Notice",
        "critical_notice_flag": "",
        "system_message": "SWN SMS message",
        "system_email_message": "SWN email message",
        "notice_start_date": " e.g. 14 Feb 2007 11:48:55. Sorted descending.",
        "notice_end_date": "e.g. 23 Jul 2007 16:30:35",
        "url_path": """
            Path to any attachment included in the notice e.g.
            Public/Master_MIBB_report_list.zip
        """,
        "current_date": """
            Date and time the report was produced e.g. Jul 23 2007 16:30:35
        """,
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
            This report is a CSV file (INT029a) published by AEMO containing public
            system-wide notices shared on the MIBB. It provides consistent and timely
            market operation updates and mirrors the content of the HTML version
            (INT105). These reports are for public viewing, unlike similar reports
            (INT029b and INT106) sent to specific participants.

            Key points:

            Purpose: Public communication of market notices.

            Format: CSV (INT029a) and HTML (INT105), both containing the same
            information.

            Timing: Issued simultaneously when AEMO publishes a system-wide notice.

            Content: Includes the issue date/time, urgency level, effective period, and
            source for further details.

            Notices are listed from most recent to oldest.
        """).strip("\n"),
    surrogate_key_sources=["system_wide_notice_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
