from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int050_v4_sched_withdrawals_1",
    glob_pattern="int050_v4_sched_withdrawals_1*",
    schema={
        "gas_date": String,
        "withdrawal_zone_name": String,
        "scheduled_qty": Float64,
        "transmission_id": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Starting hour of gas day being reported e.g. 30 Jun 1998 09:00:00",
        "withdrawal_zone_name": "Withdrawal zone name",
        "scheduled_qty": "Scheduled withdrawal (GJ) for withdrawal zone.",
        "transmission_id": "Schedule ID from which results were drawn",
        "current_date": "Date and time report produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides information required under 320(2)(i) and 320(3)(a) of the
        NGR. It provides a view of the amount of gas that is flowing in each of the
        withdrawal zones, and in the network overall, on a given day. It therefore
        contributes to data on mid- to long-term trends for planning and load
        forecasting purposes. A report is produced each time an operational schedule
        (OS) is approved by AEMO. Therefore it is expected that at least 9 of these
        reports will be issued each day: - 5 being for the standard current gas day
        schedules - 3 being for the standard 1-day ahead schedules - 1 being for the
        standard 2 day ahead schedule. Each report will provide information on at most 3
        gas days, and only report the details associated with the latest approved
        schedule for each of the three specified gas days. Each report contains details
        of the energy quantities scheduled: - in the latest approved schedule for the
        current gas day and - in the last approved 1-day ahead schedule and - in the
        last approved 2-day ahead schedule. The energy quantities reported are scheduled
        withdrawal quantities for a withdrawal zone: Scheduled withdrawals =
        Controllable withdrawals + forecast uncontrollable demand. Each row in the
        report contains details of the scheduled withdrawals for the specified
        withdrawal zone for the specified schedule.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "withdrawal_zone_name", "transmission_id"],
    group_name="vicgas__vic_dwm_sched_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
