from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int037b_v4_indicative_mkt_price_1",
    glob_pattern="int037b_v4_indicative_mkt_price_1*",
    schema={
        "demand_type_name": String,
        "price_value_gst_ex": Float64,
        "transmission_group_id": Int64,
        "schedule_type_id": String,
        "transmission_id": Int64,
        "gas_date": String,
        "approval_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "demand_type_name": (
            "Normal Uses Demand forecast used by operational schedule. "
            "10% exceedence means the estimated market price is based on "
            "10% exceedance of the forecast demand level. "
            "90% exceedence means the estimated market price if the demand "
            "is 90% of the forecast demand."
        ),
        "price_value_gst_ex": """
            Forecast market price ($) for BoD Scheduling horizon of the gas day in
            question
        """,
        "transmission_group_id": """
            Link to the related day(s) ahead operational schedule
        """,
        "schedule_type_id": "MS (Market Schedule Id)",
        "transmission_id": "Schedule number these prices are related to",
        "gas_date": "e.g. 30 Jun 2007",
        "approval_datetime": """
            Date and time the schedule was approved 29 Jun 2007 01:23:45
        """,
        "current_date": "Date and time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report indicates prices for the day and predictions for the next
        two days.

        Market participants may use this to estimate pricing for the following two
        days.
    """).strip("\n"),
    surrogate_key_sources=["demand_type_name", "transmission_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
