from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int153_v4_demand_forecast_rpt_1",
    glob_pattern="int153_v4_demand_forecast_rpt_1*",
    schema={
        "forecast_date": String,
        "version_id": Int64,
        "ti": Int64,
        "forecast_demand_gj": Int64,
        "vc_override_gj": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "forecast_date": "Gas date of forecast e.g. 30 Jun 2007",
        "version_id": "Forecast version used to identify which forecast was used in the schedule (reference INT108)",
        "ti": "Time interval (1-24)",
        "forecast_demand_gj": "Forecast total hourly demand (in GJ/hour) potentially used as input in the MCE",
        "vc_override_gj": "Quantity (in GJ) of any AEMO override (can be either positive or negative)",
        "current_date": "Date and time report produced",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is created each time AEMO generates and saves a demand forecast.
        Note this may occur many times prior to the running of a schedule as AEMO tests
        the feasibility of the different variables used in a schedule. The report
        provides: the total uncontrollable withdrawal quantity that may be used as input
        in the production of a schedule; and the quantity (positive or negative) by
        which AEMO deems it necessary to adjust Market participant submissions in order
        to maintain system security. Participants may use this report to gauge AEMO's
        schedulers view of the current day situation. As not every saved forecast demand
        generated is used in the scheduling process, Market participants need to
        reference INT108 Schedule Run Log to determine which Demand Forecast was
        actually used in scheduling. This report is generated each time AEMO generates
        and saves a demand forecast. A given report may contain demand forecasts for the
        current day, 1 day ahead, 2 days ahead, and 3 days ahead. There will be 24 rows
        in the report for each demand forecast.
    """).strip("\n"),
    surrogate_key_sources=["forecast_date", "version_id", "ti"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
