from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int111_v5_sdpc_1",
    glob_pattern="int111_v5_sdpc_1*",
    schema={
        "gas_date": String,
        "ti": Int64,
        "mirn": String,
        "ps_hourly_max_qty": Int64,
        "ps_hourly_min_qty": Int64,
        "os_hourly_max_qty": Int64,
        "os_hourly_min_qty": Int64,
        "ramp_up_constraint": Int64,
        "ramp_down_constraint": Int64,
        "schedule_response_time": String,
        "ps_daily_min_qty": Int64,
        "ps_daily_max_qty": Int64,
        "os_daily_min_qty": Int64,
        "os_daily_max_qty": Int64,
        "expiration_time": String,
        "sdpc_id": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas date (e.g. 24 Nov 2007)",
        "ti": "Trading interval (1-24)",
        "mirn": "Meter Installation Registration Number",
        "ps_hourly_max_qty": "Pricing schedule hourly maximum quantity",
        "ps_hourly_min_qty": "Pricing schedule hourly minimum quantity",
        "os_hourly_max_qty": "Operating schedule hourly maximum quantity",
        "os_hourly_min_qty": "Operating schedule hourly minimum quantity",
        "ramp_up_constraint": "Ramp up constraint",
        "ramp_down_constraint": "Ramp down constraint",
        "schedule_response_time": "Schedule response time (e.g. 30 Jun 2007 06:00:00)",
        "ps_daily_min_qty": "Pricing schedule daily minimum quantity",
        "ps_daily_max_qty": "Pricing schedule daily maximum quantity",
        "os_daily_min_qty": "Operating schedule daily minimum quantity",
        "os_daily_max_qty": "Operating schedule daily maximum quantity",
        "expiration_time": "Expiration time (e.g. 06:00:00)",
        "sdpc_id": "ID of the Constraint",
        "current_date": "Date and Time Report Produced (e.g. 30 June 2005 1:23:56)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains information regarding any supply and demand point
        constraints (SDPCs) that are current in the scheduling processes used in the
        DTS. These constraints are part of the configuration of the network that can be
        manually set by the AEMO Schedulers and form one of the inputs to the schedule
        generation process. Traders can use this information to understand the
        network-based restrictions that will constrain their ability to offer or
        withdraw gas in the market on a given day. Note these constraints can be applied
        intraday and reflect conditions from a point in time. A report is produced each
        time an operational schedule (OS) or pricing schedule (PS) is approved by AEMO.
        Therefore, it is expected that each day there will be at least 9 of these
        reports issued. Each report contains details of the SDPCs that have applied to
        schedules previously run: - on the previous gas day - for the current gas day
        and - for the next 2 gas days. Each SDPC has a unique identifier and applies to
        a single MIRN. Each row in the report contains details of one SDPC for one hour
        of the gas day, with hourly intervals commencing from the start of the gas day.
        This report will contain 24 rows for each SDPC for each gas day reported.
    """).strip("\n"),
    surrogate_key_sources=[
        "gas_date",
        "ti",
        "mirn",
        "schedule_response_time",
        "expiration_time",
        "sdpc_id",
        "current_date",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
