from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int135_v4_uplift_cap_1",
    glob_pattern="int135_v4_uplift_cap_1*",
    schema={
        "gas_date": String,
        "schedule_no": Int64,
        "positive_ave_ancillary_rate": Float64,
        "negative_ave_ancillary_rate": Float64,
        "positive_uplift_rate": Float64,
        "negative_uplift_rate": Float64,
        "current_datetime": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day Format: dd mm yyyy e.g. 23 Jul 2008",
        "schedule_no": "Pricing schedule horizon that the uplift payment applies to",
        "positive_ave_ancillary_rate": "Positive average ancillary rate over all injection and withdrawal points and all MP's. PAVAPR variable from the ancillary payment calculations.",
        "negative_ave_ancillary_rate": "Negative average ancillary rate over all injection and withdrawal points and all MP's. NAVAPR variable from the ancillary payment calculations.",
        "positive_uplift_rate": "Positive uplift rate. UPR(P) variable from the uplift payment calculation.",
        "negative_uplift_rate": "Negative uplift rate. UPR(N) variable from the uplift payment calculation.",
        "current_datetime": "When report produced. The format is dd mm yyyy hh:mm:ss e.g. 23 Jul 2008 16:30:35",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        To provide aggregated information used in Ancillary and Uplift payments
        calculations. This public report is produced whenever ancillary and uplift
        payments are required. The variables PAVAPR and NAVAPR are the average rate of
        ancillary payment as described in the Ancillary Payment Procedures. The
        variables UPR(P) and UPR(N) are part of the uplift rate cap as described in
        the Uplift Payment Procedures.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "schedule_no"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
