from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int188_v4_ctm_to_hv_zone_mapping_1",
    glob_pattern="int188_v4_ctm_to_hv_zone_mapping_1*",
    schema={
        "mirn": String,
        "site_company": String,
        "hv_zone": Int64,
        "hv_zone_desc": String,
        "effective_from": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "mirn": "Meter Installation Registration Number",
        "site_company": "Company name",
        "hv_zone": "Heating value zone number as assigned by the AEMO. Values for Victoria can be in the range of 400-699",
        "hv_zone_desc": "Heating value zone name",
        "effective_from": "Date when the HV zone became effective for the mirn, Example: 01 Aug 2023",
        "current_date": "Date and time report produced, Example: 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        A report containing the DWGM's Custody Transfer Meter (CTM) to Heating Value
        Zone mapping. The report provides the mapping of active DTS CTMs to the Heating
        Value Zones. The mapping of non-DTS CTM to heating value zone mapping for South
        Gippsland, Bairnsdale and Gippsland regions are also provided.
    """).strip("\n"),
    surrogate_key_sources=["mirn"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
