from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int171_v4_latest_nsl_1",
    glob_pattern="int171_v4_latest_nsl_1*",
    schema={
        "nsl_update": String,
        "gas_date": String,
        "distributor_name": String,
        "nsl_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "nsl_update": "Time profile created",
        "gas_date": "Primary key for MIBB report (e.g. 30 Jun 2007)",
        "distributor_name": "Primary Key for MIBB report",
        "nsl_gj": "Daily nsl energy for a DB",
        "current_date": "Time report created (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to list the Net System Load (NSL) for each distribution area for
        a rolling 3 year period. This report may be used to validate consumed energy
        produced in INT169. Section 2.8.4 of the Victorian Retail Market Procedures
        sets out AEMO's obligation to publish the NSL and Attachment 6 of the Victorian
        Retail Market Procedures sets out how AEMO calculates the NSL. This public
        report is updated daily and reflects data which is one business day after the
        gas date (Day + 1). This report only applies to the DTS network. The NSL is
        defined as the total injection into a distribution business network minus the
        daily metered load (i.e. all the interval metered sites). It therefore
        represents the consumption profile of all the non-daily read meters (basic
        meters).
    """).strip("\n"),
    surrogate_key_sources=["nsl_update", "gas_date", "distributor_name"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
