from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int140_v5_gas_quality_data_1",
    glob_pattern="int140_v5_gas_quality_data_1*",
    schema={
        "mirn": String,
        "gas_date": String,
        "ti": Int64,
        "quality_type": String,
        "unit": String,
        "quantity": Float64,
        "meter_no": String,
        "site_company": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "mirn": "Meter Installation Registration Number",
        "gas_date": "Gas day being reported e.g. 30 June 2007",
        "ti": "Time interval of the gas day (1-24), where 1 = 6:00 AM to 7:00 AM, 2 = 7:00 AM to 8:00 AM, until the 24th hour",
        "quality_type": dedent("""
            Gas quality type
                (e.g. Wobber index, Hydrogen Sulphide, Total sulphur,
                     Temperature, Heating value, Relative Density,
                     Odorisation; Gas Composition types including Methane, Ethane, Propane, N-Butane,
                     I-Butane, N-Pentane, I-Pentane, Neo-Pentane, Hexanes, Nitrogen, Carbon Dioxide, Hydrogen)
        """).strip("\n"),
        "unit": "Unit of measurement",
        "quantity": "Measurement value (some values are averaged instantaneous values for the hour)",
        "meter_no": "CTM meter number",
        "site_company": "Company name",
        "current_date": "Date and Time Report Produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides a measure of gas quality and composition at injection
        points as outlined in Division 3 / Subdivision 3 Gas Quality, of the NGR. It
        is important for the Distribution Network Operators as they have the right to
        refuse the injection of out of specification gas into their distribution
        networks. Most of the data provided are hourly average values, although some
        are spot (instantaneous) readings. Not all gas quality measures are provided
        for each injection point. The data provided for a particular injection point
        differs by the gas source for and monitoring equipment at the point. This report
        is generated each hour. Each report displays gas quality and composition details
        for the previous 3 hours at least. Time interval shows each hour in the gas
        day, where 1 = 6:00 AM to 7:00 AM, 2 = 7:00 AM to 8:00 AM, until the 24th
        hour.
    """).strip("\n"),
    surrogate_key_sources=["mirn", "gas_date", "ti", "quality_type"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
