from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int261_v4_agg_amdq_transferred_1",
    glob_pattern="int261_v4_agg_amdq_transferred_1*",
    schema={
        "gas_date": String,
        "aggregated_amdq_transferred": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported e.g. 02 Feb 2001",
        "aggregated_amdq_transferred": """
            Total AMDQ transffered each day for the previous month
        """,
        "current_date": "Date and Time report produced e.g. 30 Jun 2007 06:00:00",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report displays the aggregated AMDQ transfer quantities for the previous
        30 days. It registers the daily off market trades and transfer amounts.

        A market participant report is produced on a monthly basis showing the total
        AMDQ transferred each day for the previous 30 days.

        Each report contains: - the gas date - the aggregated AMDQ transferred - the
        date and time when the report was produced
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
