from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int262_v4_spare_capacity_limits_1",
    glob_pattern="int262_v4_spare_capacity_limits_1*",
    schema={
        "gas_date": String,
        "node_id": Int64,
        "node_name": String,
        "current_system_capacity": Float64,
        "current_lateral_capacity": Float64,
        "max_system_capacity": Float64,
        "min_system_capacity": Float64,
        "max_lateral_capacity": Float64,
        "min_lateral_capacity": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas Date data generated e.g. 02 Feb 2001",
        "node_id": "AMDQ node ID",
        "node_name": "AMDQ node name",
        "current_system_capacity": """
            Current system spare capacity available for Gas Date (refer to Content
            notes)
        """,
        "current_lateral_capacity": """
            Current lateral spare capacity available for Gas Date (refer to Content
            notes)
        """,
        "max_system_capacity": """
            Maximum future system spare capacity available for Gas Date (refer to
            Content notes)
        """,
        "min_system_capacity": """
            Minimum future system spare capacity available (refer to Content notes)
        """,
        "max_lateral_capacity": """
            Maximum future lateral spare capacity available (refer to Content notes)
        """,
        "min_lateral_capacity": """
            Minimum future lateral spare capacity available (refer to Content notes)
        """,
        "current_date": "Date and Time report produced e.g. 21 May 2007 01:32:00",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report displays the current and future maximum and minimum 'lateral' and
        'system' spare capacity available for each AMDQ node.

        This report is generated daily for the current gas day.

        Null capacity values indicate the spare capacity is not calculated for this
        node as the spare capacity is considered very large.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "node_id"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
