from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int291_v4_out_of_merit_order_gas_1",
    glob_pattern="int291_v4_out_of_merit_order_gas_1*",
    schema={
        "gas_date": String,
        "statement_version_id": Int64,
        "ancillary_amt_gst_ex": Float64,
        "scheduled_out_of_merit_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day dd mmm yyy e.g.30 Jun 2008",
        "statement_version_id": "Statement version ID",
        "ancillary_amt_gst_ex": """
            Total estimated AP for the gas day (net position as at the last schedule
            of the day) ancillary_amt_gst_ex = SUM(payment_amt) FROM
            ap_daily_sched_mirn per gas_date for inj_wdl_flag = 'I'
        """,
        "scheduled_out_of_merit_gj": """
            Net out of merit order GJs scheduled and delivered over the day
            scheduled_out_of merit_gj = SUM(ap_qty_gj) FROM ap_constrained_up per
            gas_date for inj_wdl_flag = 'I'
        """,
        "current_date": """
            Current report run date time. Format dd Mmm yyyy hh:mi:ss e.g. 15 May
            2008 12:22:12
        """,
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This is a public report generated for actual volumes of gas that contribute to
        APs (volumes of out of merit order gas). Report to be on the issue of each
        settlement (M+7, M+18 and M+118).
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "statement_version_id"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
