from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int284_v4_tuos_zone_postcode_map_1",
    glob_pattern="int284_v4_tuos_zone_postcode_map_1*",
    schema={
        "last_update_datetime": String,
        "postcode": String,
        "tuos_zone": Int64,
        "tuos_zone_desc": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "last_update_datetime": """
            date time the mapping was last updated in AEMO database (e.g. 30 Jun
            2007)
        """,
        "postcode": "Post Code",
        "tuos_zone": "TUOS Zone mapped to post code",
        "tuos_zone_desc": "TUoS Zone description",
        "current_date": "Date and Time Report Produced (e.g. 30 Jun 2007 01:23:45)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This public report defines the postcodes to TUoS zone mappings used to assign
        new MIRNs to a TUoS zone for TUoS billing purposes. It is this mapping that is
        provided to the Transmission System Service Provider for billing purposes.
        Retail businesses can use this report to verify the MIRNs that are being billed
        in each TUoS zone, and also to confirm the DB Network to which it is connected
        and the heating Zone used if it is an interval meter.

        A report is produced monthly showing the current transmission tariff zone to
        postcode mapping. The report only covers the DTS (declared transmission system)
        network.
    """).strip("\n"),
    surrogate_key_sources=["postcode", "tuos_zone"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
