from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int236_v4_operational_meter_readings_1",
    glob_pattern="int236_v4_operational_meter_readings_1*",
    schema={
        "gas_date": String,
        "direction_code_name": String,
        "direction": String,
        "commencement_datetime": String,
        "termination_datetime": String,
        "quantity": Float64,
        "time_sort_order": Int64,
        "mod_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Starting hour of gas day being reported (e.g. 30 Jun 2007)",
        "direction_code_name": "Distribution zone or injection meter",
        "direction": "'Withdrawals' or 'Injections'",
        "commencement_datetime": "Start time/date value applies for",
        "termination_datetime": "End date value applies for (e.g. 30 Jun 2007 06:00:00)",
        "quantity": "Metered value. Injection: direct reading. Withdrawals: Summed by Distribution Business Zone in GJ.",
        "time_sort_order": "Internal flag",
        "mod_datetime": "Date and time data last modified (e.g. 30 Jun 2007 06:00:00)",
        "current_date": "Date and Time Report Produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains the energy by distribution network area data for the
        previous and the current gas day. As this report is generated on an hourly
        basis, participants can use this report for adjusting their forecast of system
        load over the course of the day on a geographical basis. It can be used as an
        input into Participants bidding decisions leading up to the next schedule.
        Distributors can use this information to monitor energy flows. Note this is
        operational data and is subject to substituted data. Therefore, do not use it
        to validate settlement outcomes. This report is summed by distribution network
        zones, net of re-injections and transmission customers. Each report contains 24
        rows for the previous gas day for each injection point and each distribution
        zone.
    """).strip("\n"),
    surrogate_key_sources=[
        "gas_date",
        "direction_code_name",
        "direction",
        "commencement_datetime",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
