from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int271_v4_latest_total_hourly_nsl_1",
    glob_pattern="int271_v4_latest_total_hourly_nsl_1*",
    schema={
        "network_id": String,
        "nsl_update": String,
        "gas_date": String,
        "ti": Int64,
        "nsl_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_id": "Network ID of NSL",
        "nsl_update": "Time profile created",
        "gas_date": "Primary key for MIBB report (e.g. 30 Jun 2007)",
        "ti": "Time Interval (1-24)",
        "nsl_gj": "Hourly nsl total for all DB",
        "current_date": "Date and Time report created (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This public report is to provide a 3-year rolling history for network system
        load (NSL) on an hourly basis for both DTS and non-DTS Networks. This report
        may be used to review non-daily metered load profiles across each network and
        to forecast non-daily metered load shape in each distribution network area.

        Participants may wish to use this data as an input into their forecasting
        systems to assist in predicting the daily profile of their non-daily read
        customers' meters. It should be noted that the larger the number of non-daily
        read meters for which a Market participant is the FRO, the NSL will better
        approximate the hourly behaviour of the Market participants non-daily read load.

        Section 2.8.4 of the Victorian Retail Market Procedures AEMO's obligation to
        publish the NSL and Attachment 6 of the Victorian Retail Market Procedures set
        out how AEMO calculates the NSL.

        A report contains data which is grouped by network identifier which is used to
        distinguish non-DTS networks from the DTS network.
    """).strip("\n"),
    surrogate_key_sources=["network_id", "gas_date", "ti"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
