from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int259_v4_pipe_segment_1",
    glob_pattern="int259_v4_pipe_segment_1*",
    schema={
        "pipe_segment_id": Int64,
        "pipe_segment_name": String,
        "linepack_zone_id": Int64,
        "commencement_date": String,
        "termination_date": String,
        "node_destination_id": Int64,
        "node_origin_id": Int64,
        "diameter": Float64,
        "diameter_paired": Float64,
        "length": Float64,
        "max_pressure": Float64,
        "min_pressure": Float64,
        "max_pressure_delta": Float64,
        "pressure_at_regulator_outlet": Float64,
        "regulator_at_origin": String,
        "reverse_flow": String,
        "compressor": String,
        "mean_pipe_altitude": Int64,
        "last_mod_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "pipe_segment_id": "Pipe segment identifier",
        "pipe_segment_name": "Pipe segment name",
        "linepack_zone_id": "Linepack zone identifier",
        "commencement_date": "Commencement date of the pipe segment",
        "termination_date": "Termination date of the pipe segment",
        "node_destination_id": "Node destination identifier",
        "node_origin_id": "Node origin identifier",
        "diameter": "Pipe diameter",
        "diameter_paired": "Paired pipe diameter",
        "length": "Pipe segment length",
        "max_pressure": "Maximum pressure",
        "min_pressure": "Minimum pressure",
        "max_pressure_delta": "Maximum pressure differential along segment",
        "pressure_at_regulator_outlet": "Pressure at regulator outlet",
        "regulator_at_origin": "Flag indicating if a regulator exists at origin",
        "reverse_flow": "Flag indicating if reverse flow is possible",
        "compressor": "Flag indicating if a compressor exists",
        "mean_pipe_altitude": "Mean pipe altitude",
        "last_mod_date": "Time last modified",
        "current_date": "Date and Time the report is produced",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains the current pipe segment definitions. This public report
        is produced each time a change occurs. The report is similar to INT258 and
        shows minimum and maximum volumes for pipelines and the pressure of gas. Each
        report contains the: pipe segment id and name, linepack zone id, commencement
        and termination dates, node destination and origin id, pipe segment
        measurements, details of pressure, if a regulator, reverse flow and compressor
        exists, last modified date. Note: From 16 December 2024, this report is
        decommissioned and AEMO does not produce data for it.
    """).strip("\n"),
    surrogate_key_sources=["pipe_segment_id", "commencement_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
