from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int276_v4_hourly_scada_pressures_at_mce_nodes_1",
    glob_pattern="int276_v4_hourly_scada_pressures_at_mce_nodes_1*",
    schema={
        "node_id": Int64,
        "node_name": String,
        "measurement_datetime": String,
        "current_hour": Float64,
        "hour_01_ago": Float64,
        "hour_02_ago": Float64,
        "hour_03_ago": Float64,
        "hour_04_ago": Float64,
        "hour_05_ago": Float64,
        "hour_06_ago": Float64,
        "hour_07_ago": Float64,
        "hour_08_ago": Float64,
        "hour_09_ago": Float64,
        "hour_10_ago": Float64,
        "hour_11_ago": Float64,
        "hour_12_ago": Float64,
        "hour_13_ago": Float64,
        "hour_14_ago": Float64,
        "hour_15_ago": Float64,
        "hour_16_ago": Float64,
        "hour_17_ago": Float64,
        "hour_18_ago": Float64,
        "hour_19_ago": Float64,
        "hour_20_ago": Float64,
        "hour_21_ago": Float64,
        "hour_22_ago": Float64,
        "hour_23_ago": Float64,
        "hour_24_ago": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "node_id": "MCE node ID",
        "node_name": "MCE node name",
        "measurement_datetime": """
            Date and Time of latest pressure measurement (e.g. 30 Jun 2011 12:00:00)
        """,
        "current_hour": "pressure values at measurement time",
        "hour_01_ago": "pressure values for 1 hour before measurement time",
        "hour_02_ago": "pressure values for 2 hours before measurement time",
        "hour_03_ago": "pressure values for 3 hours before measurement time",
        "hour_04_ago": "pressure values for 4 hours before measurement time",
        "hour_05_ago": "pressure values for 5 hours before measurement time",
        "hour_06_ago": "pressure values for 6 hours before measurement time",
        "hour_07_ago": "pressure values for 7 hours before measurement time",
        "hour_08_ago": "pressure values for 8 hours before measurement time",
        "hour_09_ago": "pressure values for 9 hours before measurement time",
        "hour_10_ago": "pressure values for 10 hours before measurement time",
        "hour_11_ago": "pressure values for 11 hours before measurement time",
        "hour_12_ago": "pressure values for 12 hours before measurement time",
        "hour_13_ago": "pressure values for 13 hours before measurement time",
        "hour_14_ago": "pressure values for 14 hours before measurement time",
        "hour_15_ago": "pressure values for 15 hours before measurement time",
        "hour_16_ago": "pressure values for 16 hours before measurement time",
        "hour_17_ago": "pressure values for 17 hours before measurement time",
        "hour_18_ago": "pressure values for 18 hours before measurement time",
        "hour_19_ago": "pressure values for 19 hours before measurement time",
        "hour_20_ago": "pressure values for 20 hours before measurement time",
        "hour_21_ago": "pressure values for 21 hours before measurement time",
        "hour_22_ago": "pressure values for 22 hours before measurement time",
        "hour_23_ago": "pressure values for 23 hours before measurement time",
        "hour_24_ago": "pressure values for 24 hours before measurement time",
        "current_date": "Date and Time report created (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This public report is to provide 25 hours of rolling hourly SCADA pressures
        corresponding to MCE Node (i.e. pressure values for the current and the
        preceding 24 hours).

        The report contains real time data for actual SCADA pressure reading values in
        kPa corresponding to MCE nodes post validation. As these pressure values are
        subject to validation and substitution methodology, there may be substituted
        pressure readings.

        Current and previous 24 hours values from the measurement time are displayed.
        Where no value is present for a given hour, a NULL will be shown. MCE Nodes
        are set out in INT258 – MCE Nodes. Hourly pressure values are in kPa units.
    """).strip("\n"),
    surrogate_key_sources=["node_id", "measurement_datetime"],
    group_name="vicgas__vic_dwm_sched_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
