from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int263_v4_lng_monitor_1",
    glob_pattern="int263_v4_lng_monitor_1*",
    schema={
        "gas_date": String,
        "allocated_market_stock": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas Date data generated e.g. 02 Feb 2001",
        "allocated_market_stock": """
            Sum of Allocated Market LNG Stock Holding (tonnes) Sum of participant
            and AEMO Allocated stock holding excluding participant ID 14 GasNet.
        """,
        "current_date": "Date and Time report produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is one of a number of reports produced to provide market
        information about the daily total LNG reserves held by AEMO and all Market
        participants.

        This public report displays the sum of LNG reserves (in tonnes) held for each
        day for the past 60 days.

        Each report contains daily data for the last 60 days. The LNG stock reported
        excludes the status of BOC operations on AEMO's stock holding.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
