from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int257_v4_linepack_with_zones_1",
    glob_pattern="int257_v4_linepack_with_zones_1*",
    schema={
        "linepack_zone_id": Int64,
        "linepack_zone_name": String,
        "last_mod_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "linepack_zone_id": "Linepack Zone in which the pipe segment exists e.g. 6",
        "linepack_zone_name": "Name of the linepack zone, e.g. Gippsland",
        "last_mod_date": "Time last modified e.g. 20 June 2001 16:39:58",
        "current_date": "Time the report is produced e.g. 21 Jun 2001 16:39:58",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains the current linepack zones. This public report is produced
        when a change occurs. Each report contains the: linepack zone where the pipe
        segment is located, linepack zone name, last modified date and time, date and
        time when the report was produced. Note: From 16 December 2024, this report is
        decommissioned and AEMO does not produce data for it.
    """).strip("\n"),
    surrogate_key_sources=["linepack_zone_id"],
    group_name="vicgas__vic_dwm_sched_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
