from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int313_v4_allocated_injections_withdrawals_1",
    glob_pattern="int313_v4_allocated_injections_withdrawals_1*",
    schema={
        "gas_date": String,
        "gas_hour": String,
        "site_company": String,
        "phy_mirn": String,
        "inject_withdraw": String,
        "energy_flow_gj": Float64,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "dd mmm yyyy",
        "gas_hour": """
            The start time of the gas day 9:00:00 pre GMP and 6:00:00 post GMP start
        """,
        "site_company": "Site Company Name",
        "phy_mirn": "Phy_mirn (commissioned = 'Y', biddin = 'Y')",
        "inject_withdraw": "Sum of Actual Injections",
        "energy_flow_gj": "Actual GJ",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This is a public report that provides historical injection and controllable
        withdrawal information in a form that has been structured to facilitate graphing
        and trend analysis of the energy flows in the gas network: - out of the network
        at transmission withdrawal points - into the network at transmission injection
        points.

        This report does not contain a current date column to assist in graphing data
        directly from presented figures. The energy withdrawals reported in INT313 are
        controllable withdrawals.

        Each report contains daily data for the last 12 months. For each gas day date
        reported, a separate row will list the energy flow (in GJ) associated with each
        transmission pipeline injection or withdrawal MIRN.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "gas_hour", "phy_mirn"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
