from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int381_v4_tie_breaking_event_1",
    glob_pattern="int381_v4_tie_breaking_event_1*",
    schema={
        "gas_date": String,
        "schedule_interval": Int64,
        "transmission_id": Int64,
        "mirn": String,
        "tie_breaking_event": Int64,
        "cc_bids": Int64,
        "non_cc_bids": Int64,
        "part_cc_bids": Int64,
        "gas_not_scheduled": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "The date of gas day being reported (for example, 30 Jun 2012)",
        "schedule_interval": "(1,2,3,4 or 5)",
        "transmission_id": "Schedule ID from which results were drawn",
        "mirn": "Meter Registration Identification Number of the system point",
        "tie_breaking_event": "Total tie-breaking event",
        "cc_bids": """
            If the tie-breaking bids have CC allocated to them, list number of bids
            with CC allocated to them
        """,
        "non_cc_bids": """
            If the tie-breaking bids do not have CC allocated to them, list number
            of bids with no CC allocated to them
        """,
        "part_cc_bids": """
            If the tie-breaking bids have part CC allocated to them, list number of
            bids with part CC allocated to them
        """,
        "gas_not_scheduled": """
            Aggregate tie breaking bids - aggregate tie breaking bids scheduled
        """,
        "current_date": """
            Date and time report produced (for example, 30 Jun 2012 06:00:00)
        """,
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides information about tie-breaking events that occurred on
        each gas D on the following gas day D+1.

        This report details the tie-breaking events from the previous gas day for the
        5 intraday scheduling intervals. This report does not take into account MPs
        submitting bids that are inconsistent with their accreditations constraint. In
        an event MPs bids exceed their accreditation, a tie breaking event may be
        incorrectly reported.

        Each row in the report provides details for each mirn the tie-breaking events
        for the previous gas days 5 intraday schedules.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "schedule_interval", "transmission_id", "mirn"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
