from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int342_v4_ccauction_sys_capability_1",
    glob_pattern="int342_v4_ccauction_sys_capability_1*",
    schema={
        "zone_id": Int64,
        "zone_name": String,
        "zone_type": String,
        "capacity_period": String,
        "zone_capacity_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "zone_type": "Type of CC zone. Entry/Exit",
        "capacity_period": """
            CC product period representing date range period for the capacity
        """,
        "zone_capacity_gj": "Zone capacity as per current model in GJ",
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the total CC zone modelled capacities by the auction
        period.

        This report provides the total quantity of each auction product available for
        allocation on the basis of capacity certificates auction. The capacity
        certificates for a capacity certificates zone available for allocation will be
        the lower of either the maximum pipeline capacity or maximum facility or system
        point/s deliverable capacity.
    """).strip("\n"),
    surrogate_key_sources=["zone_id", "capacity_period"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
