from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int314_v4_bid_stack_1",
    glob_pattern="int314_v4_bid_stack_1*",
    schema={
        "bid_id": Int64,
        "gas_date": String,
        "market_participant_id": Int64,
        "company_name": String,
        "mirn": String,
        "bid_step": Int64,
        "bid_price": Float64,
        "bid_qty_gj": Float64,
        "step_qty_gj": Float64,
        "inject_withdraw": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "bid_id": "Bid Id.",
        "gas_date": "Gas date. Dd mmm yyyy",
        "market_participant_id": "Company Id of Bid owner",
        "company_name": "Company Name of Bid owner.",
        "mirn": "Phy_mirn (commissioned ='Y', bidding ='Y')",
        "bid_step": "Step (0 – 10)",
        "bid_price": "Dollar price per GJ for bid.",
        "bid_qty_gj": "MDQ for step.",
        "step_qty_gj": "Incremental MDQ for step",
        "inject_withdraw": "I or W Flag",
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is a public report that is published on both the MIBB and AEMO
        Website. It provides the bid stack data used in the scheduling process for the
        last scheduling horizon of each gas day in the past year.

        It provides Participants with historical trend information that combined with
        other public information enables Participants to gain an insight to the
        scheduling outcomes for that horizon in the AEMO scheduling process.

        This report provides historical bid stack data for each gas day in the previous
        one year (rolling), commencing with the previous gas day.

        This report contains bid stack details, which are constructed by AEMO based on:
        - Bid step quantities (up to 10) - Minimum daily quantity (MDQ) submitted as
        part of the bid - Hourly quantity constraints requested by Market participants
        and accredited by AEMO

        As a result of the application of the confidential accreditation values stored
        by AEMO the bid stack details may not exactly match bids submitted by Market
        participants.

        bid_step details are constructed by AEMO based on MDQ details entered as part
        of the bid and the structure of bid steps themselves.

        bid_step 0 is associated with: - a $0-price step for an injection bid - a
        VOLL-price step for a withdrawal bid

        In general bid_step 0 will reflect the MDQ entered. bid_qty_gj reflects the
        cumulative quantities as submitted by the Market participant. step_qty_gj is a
        calculated value that is the difference between 2 consecutive bid_qty_gj
        values. For example, if bid step 2 is for 2,500GJ and bid step 3 is for
        3,000GJ, then the step_qty_gj associated with bid_step = 3 is 500GJ.
    """).strip("\n"),
    surrogate_key_sources=["bid_id", "gas_date", "mirn", "bid_step"],
    group_name="vicgas__vic_ws_settle_meter_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
