from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int438_v4_bmp_version_non_pts_1",
    glob_pattern="int438_v4_bmp_version_non_pts_1*",
    schema={
        "network_name": String,
        "version_id": Int64,
        "extract_type": String,
        "version_from_date": String,
        "version_to_date": String,
        "issued_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_name": "Network name",
        "version_id": "Set to BMP run id",
        "extract_type": "Type (e.g. F for Final, P for Preliminary, R = Revision)",
        "version_from_date": "Effective start date",
        "version_to_date": "Effective end date e.g. 30 Jun 2007",
        "issued_date": "Transfer to MIBB date. (dd mm yyyy hh:mm:ss)",
        "current_date": "Time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the run version of the basic meter profiles system (BMP)
        used by AEMO when producing the preliminary, final and revised settlement
        versions. Market participants may wish to use this report as a reference for
        settlement reconciliation processing.

        This public report is produced daily on BMP run. Each report shows the unique
        name for each network and only reports the non-DTS (Declared transmission
        system) networks.

        Each report contains the: - network name - version id - extract type - version
        dates - issued date - date and time when the report was produced
    """).strip("\n"),
    surrogate_key_sources=["network_name", "version_id", "version_from_date"],
    group_name="vicgas__vic_gas_ret_rpt_dets",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
