from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int583_v4_monthly_cumulative_imb_pos_1",
    glob_pattern="int583_v4_monthly_cumulative_imb_pos_1*",
    schema={
        "network_name": String,
        "version_id": Int64,
        "fro_name": String,
        "distributor_name": String,
        "withdrawal_zone": String,
        "curr_cum_date": String,
        "curr_cum_imb_position": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_name": "Network Name",
        "version_id": "Settlement statement version identifier",
        "fro_name": "Name of Financially Responsible Organisation",
        "distributor_name": "Distribution business name",
        "withdrawal_zone": "Withdrawal zone",
        "curr_cum_date": "Current cumulative imbalance issue date",
        "curr_cum_imb_position": "Surplus or Deficit or Balance",
        "current_date": "Date and Time report produced 15 Aug 2007 10:06:54",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report shows the cumulative imbalance position of Retailers. Retailers may
        wish to use this report to track their status of the imbalance to do the
        necessary adjustments.

        This public report is updated at each issue of settlement to show the status of
        each retailer's imbalance position. There is no equivalent VIC MIBB report.

        Each report contains the: - network name - statement version id - financially
        Responsible Organisation - distributor Name - withdrawal zone - current
        cumulative imbalance issue date - current cumulative imbalance position
        (Surplus, Deficit or Balanced) - date and time report produced
    """).strip("\n"),
    surrogate_key_sources=[
        "network_name",
        "version_id",
        "fro_name",
        "distributor_name",
        "withdrawal_zone",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
