from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int538_v4_settlement_versions_1",
    glob_pattern="int538_v4_settlement_versions_1*",
    schema={
        "network_name": String,
        "version_id": Int64,
        "extract_type": String,
        "version_from_date": String,
        "version_to_date": String,
        "issued_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_name": "Network Name",
        "version_id": "balancing statement version (invoice_id) identifier",
        "extract_type": "P - Provisional, F - Final, R - Revision",
        "version_from_date": "Effective start date. (dd mmm yyyy)",
        "version_to_date": "Effective End date. (dd mmm yyyy)",
        "issued_date": "Issue date of settlement",
        "current_date": "Date and Time Report Produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to display recently issued settlement versions when balancing
        statement is issued. Participants may wish to use this report as a reference to
        link other reports together based on invoice id(balancing version).

        A report is produced when balancing statement is issued. This report is similar
        to VIC MIBB report INT438.

        Each report contains the: - statement version identifier - settlement category
        type - effective start date - effective end date - date of issue - date and
        time when the report was produced
    """).strip("\n"),
    surrogate_key_sources=["network_name", "version_id"],
    group_name="vicgas__qld_gas_ret_rpt_dets",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
