from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int891_v1_eddact_1",
    glob_pattern="int891_v1_eddact_1*",
    schema={
        "edd_update": String,
        "edd_date": String,
        "edd_value": Float64,
        "edd_type": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "edd_update": "Date and time value derived e.g. 27 Sep 2007 14:33:00",
        "edd_date": "Actual EDD date (event date) (e.g. 30 Jun 2007)",
        "edd_value": "EDD value",
        "edd_type": "=3 for NSW/ACT EDD",
        "current_date": "Time Report Produced (e.g. 30 Apr 2015 18:00:03)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the separate Effective Degree Day (EDD) values for NSW and
        ACT as calculated for a gas day.

        Gas distributors and retailers use the information in this report to derive an
        average EDD figure for use in their own routines to estimate end-use customers'
        consumption where no actual read is available for a basic meter. The NSW/ACT
        Retail Market Procedures prescribes AEMO requirement to publish the EDD, how
        AEMO calculates the EDD (refer Attachment 2) and the use of this EDD value when
        generating an estimated meter reading (see Attachment 2 and 3).

        The reported EDD is an actual EDD (i.e. Based on actual weather observations
        rather than weather forecasts) and is calculated for a time period as specified
        under Attachment 2 of the NSW/ACT RMP. It should also be noted that the
        published EDD value is not normally subject to revision.

        This report is generated daily. Each report provides a historical record of
        actual EDD for a rolling 60 day period ending on the day before the report
        date.

        Each row in the report provides the EDD for the specified edd_date.

        Since actual EDD is calculated on actual weather observations, the latest
        possible EDD available is for the previous full day. This means that actual EDD
        is always published (at least) 1 day in arrears.
    """).strip("\n"),
    surrogate_key_sources=["edd_update", "edd_date"],
    group_name="vicgas__sa_gas_ret_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
