from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int839a_v1_daily_zonal_hv_1",
    glob_pattern="int839a_v1_daily_zonal_hv_1*",
    schema={
        "gas_date": String,
        "hv_zone": Int64,
        "hv_zone_description": String,
        "heating_value_mj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": """
            Gas day being reported e.g. 30 Jun 2007. Covering a period of 120 gas
            days (as available).
        """,
        "hv_zone": "Heating value zone as assigned by the distributor",
        "hv_zone_description": "Name of the heating value zone",
        "heating_value_mj": "The Heating value is in MJ per standard cubic meters",
        "current_date": """
            Report generation date and timestamp. Date format dd Mmm yyyy hh:mm:ss
        """,
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the daily heating value for each heating value zone for
        NSW/ACT networks (COUNTRY or NSWCR).

        AEMO processes files sent by distributors and publishes the heating values via
        this public MIBB report. This process is only applicable to Network NSWCR and
        COUNTRY.

        The 'Published Daily Zonal heating value for the day' is a CSV report listing
        all of the Heating Value zones where the distributor is the current distributor.

        This report contains data for a period of 120 gas days (as available).
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "hv_zone"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
