from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int929a_v4_system_notices_1",
    glob_pattern="int929a_v4_system_notices_1*",
    schema={
        "system_wide_notice_id": Int64,
        "critical_notice_flag": String,
        "system_message": String,
        "system_email_message": String,
        "notice_start_date": String,
        "notice_end_date": String,
        "url_path": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "system_wide_notice_id": "Id of the ECGS Notice",
        "critical_notice_flag": "Critical notice flag",
        "system_message": "ECGS Notice SMS message",
        "system_email_message": "ECGS Notice email message",
        "notice_start_date": "e.g. 14 Feb 2023",
        "notice_end_date": "e.g. 10 May 2023",
        "url_path": """
            Path to any attachment included in the notice e.g.
            Public/ECGS_attachments/document.pdf
        """,
        "current_date": """
            Date and time the report was produced e.g. 30 Jun 2023 09:33:57
        """,
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is a comma separated values (CSV) file that contains ECGS notices
        published by AEMO to the public and is sent to Part 27 Relevant Entities via
        email and SMS.

        This report is published to the:
        1. Market Information Bulletin Board (MIBB) public folder
        2. NEMWEB folder: https://www.nemweb.com.au/REPORTS/CURRENT/ECGS/ECGS_Notices/

        This report is published to the MIBB and then replicated to the NEMWeb.

        The dual publication of this report allows existing Victorian DWGM and Gas
        Retail Market participants to access it via the MIBB. The general public and
        electricity market participants can access this report directly via NEMWeb.

        The "url path" field in the report reflects the MIBB folder location.

        Documents that are uploaded to the MIBB folder is replicated to the Any PDF
        following locations:

        1. MIBB/Public/ECGS_attachments
        2. www.nemweb.com.au - /REPORTS/CURRENT/ECGS/ECGS_Notices/Attachments/

        Each report contains the details of all the general ECGS notices that are in
        effect for Relevant Entities at the report generation time.
    """).strip("\n"),
    surrogate_key_sources=["system_wide_notice_id"],
    group_name="vicgas__ecgs_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
