from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int934_v4_ecgs_contacts_1",
    glob_pattern="int934_v4_ecgs_contacts_1*",
    schema={
        "company_name": String,
        "abn": String,
        "company_id": Int64,
        "first_name": String,
        "last_name": String,
        "contact_email": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "company_name": "Relevant entity organisation name",
        "abn": "ABN details of each relevant entity",
        "company_id": "Company identifier",
        "first_name": "First name of the ECGS Responsible Person",
        "last_name": """
            Last name of the ECGS Responsible Person (sorted by Company_Name then
            Last_Name)
        """,
        "contact_email": "Email address of the ECGS Responsible Person",
        "current_date": """
            Date and time the report was produced e.g. 30 Jun 2023 09:33:57
        """,
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This is the Part 27 Register for the purposes of rule 713(1)(b) of the NGR.
        AEMO only publishes a portion of the Part 27 Register information required by
        section 6.1 of the ECGS Procedures.

        This report is a comma separated values (CSV) file that contains each Part 27
        relevant entity's active ECGS Responsible Person contacts. The ECGS Responsible
        Person contact receives ECGS notices from AEMO. This report is published to
        the: 1. Market Information Bulletin Board (MIBB) public folder 2. NEMWEB
        folder: https://www.nemweb.com.au/REPORTS/CURRENT/ECGS/

        This report is published to the MIBB and then replicated to the NEMWeb.

        Each report contains the ECGS Responsible Person contacts of each relevant
        entity.
    """).strip("\n"),
    surrogate_key_sources=["company_id", "first_name", "last_name"],
    group_name="vicgas__ecgs_rpts",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
