"""bronze_int039b_v4_indicative_locational_price_1 - Bronze MIBB report configuration."""  # noqa: E501

from polars import Float64, Int64, String
from aemo_etl.configuration import (
    VICTORIAN_DECLARED_WHOLESALE_MARKET_SCHEDULING_REPORTS,
)
from aemo_etl.configuration.registry import mibb_report
from aemo_etl.configuration.report_config import ReportConfig, mibb_config_factory


@mibb_report
def CONFIG() -> ReportConfig:
    """MIBB report configuration."""
    return mibb_config_factory(
        table_name="bronze_int039b_v4_indicative_locational_price_1",
        s3_file_glob="int039b_v4_indicative_locational_price_1*",
        primary_keys=["gas_date", "node_name", "ti", "transmission_id"],
        table_schema={
            "gas_date": String,
            "node_name": String,
            "ti": Int64,
            "nodal_price_value_gst_ex": Float64,
            "transmission_id": Int64,
            "current_date": String,
            "surrogate_key": String,
        },
        schema_descriptions={
            "gas_date": "Starting hour of gas day being reported e.g. 30 Jun 2007 06:00:00",  # noqa: E501
            "node_name": "Name of node at which price applies",
            "ti": "Hour index (1-24)",
            "nodal_price_value_gst_ex": "Nodal price ($)",
            "transmission_id": "Schedule number these prices are related to",
            "current_date": "Date and Time Report Produced",
            "surrogate_key": "Unique identifier created using sha256 over the primary keys",  # noqa: E501
        },
        report_purpose="\n\nThis report lists the hourly locational (nodal) prices generated by the MCE (market clearing engine) from each approved schedule in the\ngas day and upon approval of subsequent re-schedule for the previous 7 days.\n\nThe report contains hourly pricing data for each locational node for the previous 7 days. Therefore it is expected that each node will\nreflect 24 prices per gas day (commencing 6:00 AM daily) for the past 7 days.\n\nEach report contains the pricing data for each hour of the gas day per locational node across a 7-day period. It is expected that the\nreport will reflect:\n- date of the gas day\n- name of locational node\n- each hourly index for the gas day (ie 1 to 24)\n- price per hour excluding GST\n- schedule number which price relate to\n- the date and time when the report was produced.\n\nAs each report includes the gas date, followed by each locational node's 24 hourly prices across 7 days, this means that if there are 30\nlocational nodes in the one day, then this would mean 30 multiplied by 24 hourly prices. Therefore the user can expect to see 720 rows\nof data for that gas day, multiplied by 7 days which will give potentially a total of 5040 rows of data per report for the previous 7 days.\n",  # noqa: E501
        group_name=f"aemo__mibb__{VICTORIAN_DECLARED_WHOLESALE_MARKET_SCHEDULING_REPORTS}",
    )
