"""bronze_int126_v4_dfs_data_1 - Bronze MIBB report configuration."""

from polars import Float64, Int64, String
from aemo_etl.configuration import (
    VICTORIAN_DECLARED_WHOLESALE_MARKET_SCHEDULING_REPORTS,
)
from aemo_etl.configuration.registry import mibb_report
from aemo_etl.configuration.report_config import ReportConfig, mibb_config_factory


@mibb_report
def CONFIG() -> ReportConfig:
    """MIBB report configuration."""
    return mibb_config_factory(
        table_name="bronze_int126_v4_dfs_data_1",
        s3_file_glob="int126_v4_dfs_data_1*",
        primary_keys=["dfs_version", "gas_date"],
        table_schema={
            "dfs_version": Int64,
            "gas_date": String,
            "last_update_datetime": String,
            "previous_day_min": Float64,
            "max": Float64,
            "overnight_min": Float64,
            "average_wind_speed": Float64,
            "sunshine": Int64,
            "effective_temperature": Float64,
            "dfs_edd": Float64,
            "total_demand_forecast": Int64,
            "current_date": String,
            "surrogate_key": String,
        },
        schema_descriptions={
            "dfs_version": "Demand forecast version",
            "gas_date": "Gas Day date the temperature data applies to (e.g. 30 Jun 2007)",
            "last_update_datetime": "Time data obtained and loaded into AEMO's database (e.g. 05:00:00)",
            "previous_day_min": "Previous day over night minimum temperature (NULL from 15 April 2024)",
            "max": "Maximum temperature for day (NULL from 15 April 2024)",
            "overnight_min": "Overnight minimum temperature (NULL from 15 April 2024)",
            "average_wind_speed": "Average wind speed (knots) (NULL from 15 April 2024)",
            "sunshine": "Hours of sunshine (NULL from 15 April 2024)",
            "effective_temperature": "Effective temperature calculated by AEMO's Demand Forecasting System (DFS)",
            "dfs_edd": "Effective Degree Day (EDD) calculated by AEMO's Demand Forecasting System (DFS)",
            "total_demand_forecast": "AEMO's total daily demand forecast for the gas day calculated by AEMO's Demand Forecasting System (DFS)",
            "current_date": "Date and time report produced (e.g. 30 June 2005 1:23:56)",
            "surrogate_key": "Unique identifier created using sha256 over the primary keys",
        },
        report_purpose="\n\nThis report provides AEMO's calculated effective temperature, effective degree day (EDD) and total system demand forecast\n(representing system demand and site specific demand) for the DWGM from AEMO's Demand Forecasting System (DFS).\n\nThis data can be used to validate forecasting methodologies against AEMO's DFS. It is also used to validate AEMO's demand\nforecast where there has been a demand override in the scheduling process.\n\nNot every demand generated by the AEMO DFS is used in the scheduling process. Participants should reference INT108\nSchedule Run Log to determine the Demand Forecasts used for each schedule.\n\nThe INT108 forecast_demand_version identifies the forecast used by AEMO in generating a schedule.\n\nThis report contains data for:\n- the current gas day\n- 1-day ahead\n- 2 days ahead\n- the previous 7 days\n\nEach report therefore can contain data for up to 10 days.\nEach row of the report contains data for one generated nodal forecast.\n\nFrom 15 April 2024, AEMO has a new weather forecast data provider. The following fields will be NULL:\n- previous_day_min\n- max\n- overnight_min\n- average_wind_speed\n- sunshine\n",
        group_name=f"aemo__mibb__{VICTORIAN_DECLARED_WHOLESALE_MARKET_SCHEDULING_REPORTS}",
    )
