from polars import Float64, Int64, String

from aemo_etl.configuration import (
    BRONZE_BUCKET,
    VICTORIAN_DECLARED_WHOLESALE_MARKET_SCHEDULING_REPORTS,
)
from aemo_etl.register import table_locations

#     ╭────────────────────────────────────────────────────────────────────────────────────────╮
#     │                      define table and register to table locations                      │
#     ╰────────────────────────────────────────────────────────────────────────────────────────╯


table_name = "bronze_int126_v4_dfs_data_1"

s3_prefix = "aemo/vicgas"

s3_file_glob = "int126_v4_dfs_data_1*"

s3_table_location = f"s3://{BRONZE_BUCKET}/{s3_prefix}/{table_name}"

primary_keys = [
    "dfs_version",
    "gas_date",
]

upsert_predicate = "s.surrogate_key = t.surrogate_key"

table_schema = {
    "dfs_version": Int64,
    "gas_date": String,
    "last_update_datetime": String,
    "previous_day_min": Float64,
    "max": Float64,
    "overnight_min": Float64,
    "average_wind_speed": Float64,
    "sunshine": Int64,
    "effective_temperature": Float64,
    "dfs_edd": Float64,
    "total_demand_forecast": Int64,
    "current_date": String,
    "surrogate_key": String,
}

schema_descriptions = {
    "dfs_version": "Demand forecast version",
    "gas_date": "Gas Day date the temperature data applies to (e.g. 30 Jun 2007)",
    "last_update_datetime": "Time data obtained and loaded into AEMO's database (e.g. 05:00:00)",
    "previous_day_min": "Previous day over night minimum temperature (NULL from 15 April 2024)",
    "max": "Maximum temperature for day (NULL from 15 April 2024)",
    "overnight_min": "Overnight minimum temperature (NULL from 15 April 2024)",
    "average_wind_speed": "Average wind speed (knots) (NULL from 15 April 2024)",
    "sunshine": "Hours of sunshine (NULL from 15 April 2024)",
    "effective_temperature": "Effective temperature calculated by AEMO's Demand Forecasting System (DFS)",
    "dfs_edd": "Effective Degree Day (EDD) calculated by AEMO's Demand Forecasting System (DFS)",
    "total_demand_forecast": "AEMO's total daily demand forecast for the gas day calculated by AEMO's Demand Forecasting System (DFS)",
    "current_date": "Date and time report produced (e.g. 30 June 2005 1:23:56)",
    "surrogate_key": "Unique identifier created using sha256 over the primary keys",
}

report_purpose = """
This report provides AEMO's calculated effective temperature, effective degree day (EDD) and total system demand forecast
(representing system demand and site specific demand) for the DWGM from AEMO's Demand Forecasting System (DFS).

This data can be used to validate forecasting methodologies against AEMO's DFS. It is also used to validate AEMO's demand
forecast where there has been a demand override in the scheduling process.

Not every demand generated by the AEMO DFS is used in the scheduling process. Participants should reference INT108
Schedule Run Log to determine the Demand Forecasts used for each schedule.

The INT108 forecast_demand_version identifies the forecast used by AEMO in generating a schedule.

This report contains data for:
- the current gas day
- 1-day ahead
- 2 days ahead
- the previous 7 days

Each report therefore can contain data for up to 10 days.
Each row of the report contains data for one generated nodal forecast.

From 15 April 2024, AEMO has a new weather forecast data provider. The following fields will be NULL:
- previous_day_min
- max
- overnight_min
- average_wind_speed
- sunshine
"""

table_locations[table_name] = {
    "table_name": table_name,
    "table_type": "delta",
    "glue_schema": "aemo",
    "s3_table_location": s3_table_location,
}


group_name = f"aemo__mibb__{VICTORIAN_DECLARED_WHOLESALE_MARKET_SCHEDULING_REPORTS}"
