[project]
name = "dagster-daemon-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.10.9",
    "dagster-aws>=0.26.9",
    "dagster-docker>=0.26.9",
    "dagster-postgres>=0.26.9",
]
