[[locations]]
name = "aemo-etl"
module = "aemo_etl.definitions"
port = 4000
cloud_map_name = "aemo-etl"
source_path = "backend-services/dagster-user/aemo-etl"
image_repository = "dagster/user-code/aemo-etl"
default = true
