import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AssetKey,
    AutomationCondition,
    Definitions,
    MaterializeResult,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET
from aemo_etl.defs.gas_model._parsing import parse_gas_datetime
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_fact_operational_meter_flow"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per source-specific VICGAS operational meter flow observation"
SURROGATE_KEY_SOURCES = [
    "source_system",
    "source_table",
    "gas_date",
    "point_type",
    "source_point_id",
    "flow_direction",
    "gas_interval",
    "commencement_timestamp",
    "source_surrogate_key",
]
SOURCE_TABLES = [
    "silver.vicgas.silver_int236_v4_operational_meter_readings_1",
    "silver.vicgas.silver_int313_v4_allocated_injections_withdrawals_1",
]
SOURCE_SYSTEM = "VICGAS"

VICGAS_METER_READINGS_KEY = AssetKey(
    ["silver", "vicgas", "silver_int236_v4_operational_meter_readings_1"]
)
VICGAS_ALLOCATIONS_KEY = AssetKey(
    ["silver", "vicgas", "silver_int313_v4_allocated_injections_withdrawals_1"]
)
DATES_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_date"])
OPERATIONAL_POINTS_KEY = AssetKey(
    ["silver", "gas_model", "silver_gas_dim_operational_point"]
)

_SOURCE_METER_DEPS = [
    TableColumnDep(asset_key=VICGAS_METER_READINGS_KEY, column_name="surrogate_key"),
    TableColumnDep(asset_key=VICGAS_ALLOCATIONS_KEY, column_name="surrogate_key"),
]

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": _SOURCE_METER_DEPS,
        "date_key": [
            TableColumnDep(asset_key=VICGAS_METER_READINGS_KEY, column_name="gas_date"),
            TableColumnDep(asset_key=VICGAS_ALLOCATIONS_KEY, column_name="gas_date"),
            TableColumnDep(asset_key=DATES_KEY, column_name="surrogate_key"),
        ],
        "operational_point_key": [
            TableColumnDep(
                asset_key=VICGAS_METER_READINGS_KEY,
                column_name="direction_code_name",
            ),
            TableColumnDep(asset_key=VICGAS_ALLOCATIONS_KEY, column_name="phy_mirn"),
            TableColumnDep(
                asset_key=OPERATIONAL_POINTS_KEY, column_name="surrogate_key"
            ),
        ],
        "zone_key": [
            TableColumnDep(asset_key=OPERATIONAL_POINTS_KEY, column_name="zone_key")
        ],
        "pipeline_segment_key": [
            TableColumnDep(
                asset_key=OPERATIONAL_POINTS_KEY, column_name="pipeline_segment_key"
            )
        ],
        "quantity_gj": [
            TableColumnDep(asset_key=VICGAS_METER_READINGS_KEY, column_name="quantity"),
            TableColumnDep(
                asset_key=VICGAS_ALLOCATIONS_KEY, column_name="energy_flow_gj"
            ),
        ],
        "source_surrogate_key": _SOURCE_METER_DEPS,
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "date_key": pl.String,
    "operational_point_key": pl.String,
    "zone_key": pl.String,
    "pipeline_segment_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_table": pl.String,
    "gas_date": pl.Date,
    "gas_interval": pl.String,
    "point_type": pl.String,
    "source_point_id": pl.String,
    "flow_direction": pl.String,
    "quantity_gj": pl.Float64,
    "commencement_timestamp": pl.Datetime("us"),
    "termination_timestamp": pl.Datetime("us"),
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver fact primary key generated by surrogate_key_sources.",
    "date_key": "Parent silver_gas_dim_date surrogate_key.",
    "operational_point_key": "Parent silver_gas_dim_operational_point surrogate_key when resolvable.",
    "zone_key": "Parent silver_gas_dim_zone surrogate_key when resolvable.",
    "pipeline_segment_key": "Parent silver_gas_dim_pipeline_segment surrogate_key when resolvable.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the gas model row.",
    "source_table": "Specific silver source table for this row.",
    "gas_date": "Gas day date.",
    "gas_interval": "Source interval or hour label.",
    "point_type": "Operational point identifier type.",
    "source_point_id": "Source-system operational point identifier.",
    "flow_direction": "Operational flow direction.",
    "quantity_gj": "Operational meter, injection, or withdrawal quantity in GJ.",
    "commencement_timestamp": "Interval commencement timestamp where provided.",
    "termination_timestamp": "Interval termination timestamp where provided.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "date_key",
    "source_system",
    "gas_date",
    "point_type",
    "source_point_id",
]


def _parse_datetime(column: str) -> pl.Expr:
    return parse_gas_datetime(column)


def _meter_reading_rows(df: LazyFrame) -> LazyFrame:
    return df.select(
        source_system=pl.lit(SOURCE_SYSTEM),
        source_tables=pl.lit([SOURCE_TABLES[0]]).cast(pl.List(pl.String)),
        source_table=pl.lit(SOURCE_TABLES[0]),
        gas_date=_parse_datetime("gas_date").dt.date(),
        gas_interval=pl.col("time_sort_order").cast(pl.String),
        point_type=pl.lit("direction_code_name"),
        source_point_id=pl.col("direction_code_name").cast(pl.String),
        flow_direction=pl.col("direction").cast(pl.String),
        quantity_gj=pl.col("quantity").cast(pl.Float64),
        commencement_timestamp=_parse_datetime("commencement_datetime"),
        termination_timestamp=_parse_datetime("termination_datetime"),
        source_last_updated=pl.col("mod_datetime").cast(pl.String),
        source_last_updated_timestamp=_parse_datetime("mod_datetime"),
        source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        source_file=pl.col("source_file").cast(pl.String),
        ingested_timestamp=pl.col("ingested_timestamp"),
    )


def _allocation_rows(df: LazyFrame) -> LazyFrame:
    return df.select(
        source_system=pl.lit(SOURCE_SYSTEM),
        source_tables=pl.lit([SOURCE_TABLES[1]]).cast(pl.List(pl.String)),
        source_table=pl.lit(SOURCE_TABLES[1]),
        gas_date=_parse_datetime("gas_date").dt.date(),
        gas_interval=pl.col("gas_hour").cast(pl.String),
        point_type=pl.lit("phy_mirn"),
        source_point_id=pl.col("phy_mirn").cast(pl.String),
        flow_direction=pl.col("inject_withdraw").cast(pl.String),
        quantity_gj=pl.col("energy_flow_gj").cast(pl.Float64),
        commencement_timestamp=pl.lit(None).cast(pl.Datetime("us")),
        termination_timestamp=pl.lit(None).cast(pl.Datetime("us")),
        source_last_updated=pl.lit(None).cast(pl.String),
        source_last_updated_timestamp=pl.lit(None).cast(pl.Datetime("us")),
        source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        source_file=pl.col("source_file").cast(pl.String),
        ingested_timestamp=pl.col("ingested_timestamp"),
    )


def _select_operational_meter_flow(
    vicgas_meter_readings: LazyFrame,
    vicgas_allocations: LazyFrame,
    dates: LazyFrame,
    operational_points: LazyFrame,
) -> LazyFrame:
    date_keys = dates.select(
        date_key=pl.col("surrogate_key"), gas_date=pl.col("gas_date")
    )
    operational_point_keys = operational_points.filter(
        pl.col("source_system") == SOURCE_SYSTEM
    ).select(
        operational_point_key=pl.col("surrogate_key"),
        zone_key=pl.col("zone_key"),
        pipeline_segment_key=pl.col("pipeline_segment_key"),
        point_type=pl.col("point_type"),
        source_point_id=pl.col("source_point_id"),
    )
    combined = pl.concat(
        [
            _meter_reading_rows(vicgas_meter_readings),
            _allocation_rows(vicgas_allocations),
        ],
        how="diagonal_relaxed",
    )

    return (
        combined.with_columns(surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES))
        .join(date_keys, on="gas_date", how="left")
        .join(
            operational_point_keys,
            on=["point_type", "source_point_id"],
            how="left",
        )
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver VICGAS operational meter flow fact.",
    ins={
        "vicgas_meter_readings": AssetIn(key=VICGAS_METER_READINGS_KEY),
        "vicgas_allocations": AssetIn(key=VICGAS_ALLOCATIONS_KEY),
        "dates": AssetIn(key=DATES_KEY),
        "operational_points": AssetIn(key=OPERATIONAL_POINTS_KEY),
    },
    io_manager_key="aemo_deltalake_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "deltalake"},
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_fact_operational_meter_flow(
    vicgas_meter_readings: LazyFrame,
    vicgas_allocations: LazyFrame,
    dates: LazyFrame,
    operational_points: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    return _materialize_result(
        _select_operational_meter_flow(
            vicgas_meter_readings,
            vicgas_allocations,
            dates,
            operational_points,
        )
    )


@asset_check(
    asset=silver_gas_fact_operational_meter_flow,
    name="check_required_fields",
    description="Check required fact fields are not null.",
)
def silver_gas_fact_operational_meter_flow_required_fields(
    input_df: LazyFrame,
) -> AssetCheckResult:
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_fact_operational_meter_flow_duplicate_row_check = (
    duplicate_row_check_factory(
        assets_definition=silver_gas_fact_operational_meter_flow,
        check_name="check_for_duplicate_rows",
        primary_key="surrogate_key",
        description="Check that surrogate_key is unique.",
    )
)

silver_gas_fact_operational_meter_flow_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_operational_meter_flow,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)

silver_gas_fact_operational_meter_flow_schema_drift_check = schema_drift_check_factory(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_operational_meter_flow,
    check_name="check_schema_drift",
    description="Check for schema drift against the declared asset schema.",
)


@definitions
def defs() -> Definitions:
    return Definitions(
        assets=[silver_gas_fact_operational_meter_flow],
        asset_checks=[
            silver_gas_fact_operational_meter_flow_duplicate_row_check,
            silver_gas_fact_operational_meter_flow_schema_check,
            silver_gas_fact_operational_meter_flow_schema_drift_check,
            silver_gas_fact_operational_meter_flow_required_fields,
        ],
    )
