import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AssetKey,
    AutomationCondition,
    Definitions,
    MaterializeResult,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_participant_market_membership"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per participant, source system, and market code"
SURROGATE_KEY_SOURCES = ["participant_key", "source_system", "market_code"]
SOURCE_TABLES = [
    "silver.gbb.silver_gasbb_participants_list",
    "silver.vicgas.silver_int125_v8_details_of_organisations_1",
]
GBB_PARTICIPANTS_KEY = AssetKey(["silver", "gbb", "silver_gasbb_participants_list"])
VICGAS_ORGANISATIONS_KEY = AssetKey(
    ["silver", "vicgas", "silver_int125_v8_details_of_organisations_1"]
)
PARTICIPANTS_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_participant"])

_IDENTITY_DEPS = [
    TableColumnDep(asset_key=GBB_PARTICIPANTS_KEY, column_name="CompanyId"),
    TableColumnDep(asset_key=GBB_PARTICIPANTS_KEY, column_name="ABN"),
    TableColumnDep(asset_key=GBB_PARTICIPANTS_KEY, column_name="CompanyName"),
    TableColumnDep(asset_key=VICGAS_ORGANISATIONS_KEY, column_name="company_id"),
    TableColumnDep(asset_key=VICGAS_ORGANISATIONS_KEY, column_name="abn"),
    TableColumnDep(asset_key=VICGAS_ORGANISATIONS_KEY, column_name="acn"),
    TableColumnDep(asset_key=VICGAS_ORGANISATIONS_KEY, column_name="company_name"),
]

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": [
            TableColumnDep(asset_key=PARTICIPANTS_KEY, column_name="surrogate_key"),
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="market_code"
            ),
        ],
        "participant_key": [
            TableColumnDep(asset_key=PARTICIPANTS_KEY, column_name="surrogate_key")
        ],
        "market_code": [
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="market_code"
            )
        ],
        "source_company_id": [
            TableColumnDep(asset_key=GBB_PARTICIPANTS_KEY, column_name="CompanyId"),
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="company_id"
            ),
        ],
        "source_company_code": [
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="company_code"
            )
        ],
        "participant_identity_source": _IDENTITY_DEPS,
        "participant_identity_value": _IDENTITY_DEPS,
        "source_surrogate_key": [
            TableColumnDep(asset_key=GBB_PARTICIPANTS_KEY, column_name="surrogate_key"),
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="surrogate_key"
            ),
        ],
        "source_file": [
            TableColumnDep(asset_key=GBB_PARTICIPANTS_KEY, column_name="source_file"),
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="source_file"
            ),
        ],
        "ingested_timestamp": [
            TableColumnDep(
                asset_key=GBB_PARTICIPANTS_KEY, column_name="ingested_timestamp"
            ),
            TableColumnDep(
                asset_key=VICGAS_ORGANISATIONS_KEY, column_name="ingested_timestamp"
            ),
        ],
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "participant_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "market_code": pl.String,
    "source_company_id": pl.String,
    "source_company_code": pl.String,
    "participant_identity_source": pl.String,
    "participant_identity_value": pl.String,
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver bridge primary key generated by surrogate_key_sources.",
    "participant_key": "Parent silver_gas_dim_participant surrogate_key.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the gas model row.",
    "market_code": "Gas market registration code.",
    "source_company_id": "Source-system company identifier.",
    "source_company_code": "Source-system company code where available.",
    "participant_identity_source": "Identifier type used to resolve participant_key.",
    "participant_identity_value": "Identifier value used to resolve participant_key.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = ["surrogate_key", "participant_key", "source_system", "market_code"]


def _normalize_identifier(column: str) -> pl.Expr:
    return (
        pl.col(column)
        .cast(pl.String)
        .str.replace_all(r"[^0-9A-Za-z]", "")
        .str.to_uppercase()
    )


def _with_identity(df: LazyFrame) -> LazyFrame:
    return df.with_columns(
        participant_identity_source=(
            pl.when(pl.col("source_company_id").is_not_null())
            .then(pl.lit("company_id"))
            .when(pl.col("abn").is_not_null() & (pl.col("abn") != ""))
            .then(pl.lit("abn"))
            .when(pl.col("acn").is_not_null() & (pl.col("acn") != ""))
            .then(pl.lit("acn"))
            .otherwise(pl.lit("participant_name"))
        ),
        participant_identity_value=(
            pl.when(pl.col("source_company_id").is_not_null())
            .then(pl.col("source_company_id"))
            .when(pl.col("abn").is_not_null() & (pl.col("abn") != ""))
            .then(pl.col("abn"))
            .when(pl.col("acn").is_not_null() & (pl.col("acn") != ""))
            .then(pl.col("acn"))
            .otherwise(pl.col("participant_name").str.to_uppercase())
        ),
    )


def _gbb_memberships(df: LazyFrame) -> LazyFrame:
    return df.select(
        source_system=pl.lit("GBB"),
        source_tables=pl.lit(["silver.gbb.silver_gasbb_participants_list"]).cast(
            pl.List(pl.String)
        ),
        market_code=pl.lit("NATGASBB"),
        source_company_id=pl.col("CompanyId").cast(pl.String),
        source_company_code=pl.lit(None).cast(pl.String),
        participant_name=pl.col("CompanyName").cast(pl.String),
        abn=_normalize_identifier("ABN"),
        acn=pl.lit(None).cast(pl.String),
        source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        source_file=pl.col("source_file").cast(pl.String),
        ingested_timestamp=pl.col("ingested_timestamp"),
    )


def _vicgas_memberships(df: LazyFrame) -> LazyFrame:
    return df.select(
        source_system=pl.lit("VICGAS"),
        source_tables=pl.lit(
            ["silver.vicgas.silver_int125_v8_details_of_organisations_1"]
        ).cast(pl.List(pl.String)),
        market_code=pl.col("market_code").cast(pl.String),
        source_company_id=pl.col("company_id").cast(pl.String),
        source_company_code=pl.col("company_code").cast(pl.String),
        participant_name=pl.col("company_name").cast(pl.String),
        abn=_normalize_identifier("abn"),
        acn=_normalize_identifier("acn"),
        source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        source_file=pl.col("source_file").cast(pl.String),
        ingested_timestamp=pl.col("ingested_timestamp"),
    )


def _select_market_memberships(
    gbb_participants: LazyFrame,
    vicgas_organisations: LazyFrame,
    participants: LazyFrame,
) -> LazyFrame:
    combined = _with_identity(
        pl.concat(
            [
                _gbb_memberships(gbb_participants),
                _vicgas_memberships(vicgas_organisations),
            ],
            how="diagonal_relaxed",
        )
    )
    participant_keys = participants.select(
        participant_key=pl.col("surrogate_key"),
        participant_identity_source=pl.col("participant_identity_source"),
        participant_identity_value=pl.col("participant_identity_value"),
    )
    return (
        combined.join(
            participant_keys,
            on=["participant_identity_source", "participant_identity_value"],
            how="inner",
        )
        .with_columns(surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES))
        .sort(["participant_key", "source_system", "market_code", "ingested_timestamp"])
        .unique(subset=SURROGATE_KEY_SOURCES, keep="last", maintain_order=True)
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver gas participant market-membership bridge.",
    ins={
        "gbb_participants": AssetIn(key=GBB_PARTICIPANTS_KEY),
        "vicgas_organisations": AssetIn(key=VICGAS_ORGANISATIONS_KEY),
        "participants": AssetIn(key=PARTICIPANTS_KEY),
    },
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "parquet"},
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_participant_market_membership(
    gbb_participants: LazyFrame,
    vicgas_organisations: LazyFrame,
    participants: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    return _materialize_result(
        _select_market_memberships(gbb_participants, vicgas_organisations, participants)
    )


@asset_check(
    asset=silver_gas_participant_market_membership,
    name="check_required_fields",
    description="Check required bridge fields are not null.",
)
def silver_gas_participant_market_membership_required_fields(
    input_df: LazyFrame,
) -> AssetCheckResult:
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_participant_market_membership_duplicate_row_check = (
    duplicate_row_check_factory(
        assets_definition=silver_gas_participant_market_membership,
        check_name="check_for_duplicate_rows",
        primary_key="surrogate_key",
        description="Check that surrogate_key is unique.",
    )
)

silver_gas_participant_market_membership_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_participant_market_membership,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)

silver_gas_participant_market_membership_schema_drift_check = (
    schema_drift_check_factory(
        schema=SCHEMA,
        assets_definition=silver_gas_participant_market_membership,
        check_name="check_schema_drift",
        description="Check for schema drift against the declared asset schema.",
    )
)


@definitions
def defs() -> Definitions:
    return Definitions(
        assets=[silver_gas_participant_market_membership],
        asset_checks=[
            silver_gas_participant_market_membership_duplicate_row_check,
            silver_gas_participant_market_membership_schema_check,
            silver_gas_participant_market_membership_schema_drift_check,
            silver_gas_participant_market_membership_required_fields,
        ],
    )
