"""Dagster definitions for the silver STTM market parameter fact asset."""

import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AutomationCondition,
    AutomationConditionSensorDefinition,
    Backoff,
    Definitions,
    Jitter,
    MaterializeResult,
    RetryPolicy,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET, DEFAULT_SENSOR_STATUS
from aemo_etl.defs.gas_model._sttm_common import (
    ZONES_KEY,
    parse_datetime,
    source_asset_key,
    source_metadata,
    source_table,
    with_zone_key,
)
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_fact_sttm_market_parameter"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per STTM hub and effective market parameter period"
SURROGATE_KEY_SOURCES = [
    "source_system",
    "source_table",
    "source_hub_id",
    "effective_from_date",
    "parameter_type",
    "source_surrogate_key",
]
SOURCE_TABLES = [source_table("int680_v1_dp_flag_data_rpt_1")]
INT680_KEY = source_asset_key("int680_v1_dp_flag_data_rpt_1")

_SOURCE_KEY_DEPS = [TableColumnDep(asset_key=INT680_KEY, column_name="surrogate_key")]
_SOURCE_HUB_ID_DEPS = [
    TableColumnDep(asset_key=INT680_KEY, column_name="hub_identifier")
]

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": _SOURCE_KEY_DEPS,
        "effective_from_date_key": [
            TableColumnDep(asset_key=INT680_KEY, column_name="effective_from_date")
        ],
        "effective_to_date_key": [
            TableColumnDep(asset_key=INT680_KEY, column_name="effective_to_date")
        ],
        "zone_key": [
            *_SOURCE_HUB_ID_DEPS,
            TableColumnDep(asset_key=ZONES_KEY, column_name="surrogate_key"),
        ],
        "source_hub_id": _SOURCE_HUB_ID_DEPS,
        "dp_flag": [TableColumnDep(asset_key=INT680_KEY, column_name="dp_flag")],
        "source_surrogate_key": _SOURCE_KEY_DEPS,
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "effective_from_date_key": pl.String,
    "effective_to_date_key": pl.String,
    "zone_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_table": pl.String,
    "source_report_id": pl.String,
    "parameter_type": pl.String,
    "source_hub_id": pl.String,
    "source_hub_name": pl.String,
    "effective_from_date": pl.Date,
    "effective_to_date": pl.Date,
    "dp_flag": pl.String,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver fact primary key generated by surrogate_key_sources.",
    "effective_from_date_key": "Deterministic silver_gas_dim_date surrogate_key for effective_from_date.",
    "effective_to_date_key": "Deterministic silver_gas_dim_date surrogate_key for effective_to_date.",
    "zone_key": "Parent silver_gas_dim_zone surrogate_key for STTM hub when resolvable.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the row.",
    "source_table": "Specific silver source table for this row.",
    "source_report_id": "STTM report identifier.",
    "parameter_type": "Source market parameter represented by the row.",
    "source_hub_id": "Source-system hub identifier.",
    "source_hub_name": "Source-system hub name.",
    "effective_from_date": "First gas date for which the source parameter applies.",
    "effective_to_date": "Last gas date for which the source parameter applies.",
    "dp_flag": "Source DP flag value retained with source-specific semantics.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "effective_from_date_key",
    "source_system",
    "source_table",
    "source_report_id",
    "parameter_type",
    "source_hub_id",
    "effective_from_date",
    "dp_flag",
    "source_surrogate_key",
]


def _nullable_date_key(column: str) -> pl.Expr:
    return (
        pl.when(pl.col(column).is_not_null())
        .then(get_surrogate_key([column]))
        .otherwise(pl.lit(None).cast(pl.String))
    )


def _select_sttm_market_parameters(int680: LazyFrame, zones: LazyFrame) -> LazyFrame:
    rows = int680.select(
        *source_metadata(table_name=SOURCE_TABLES[0], report_id="INT680"),
        parameter_type=pl.lit("dp_flag"),
        source_hub_id=pl.col("hub_identifier").cast(pl.String),
        source_hub_name=pl.col("hub_name").cast(pl.String),
        effective_from_date=parse_datetime("effective_from_date").dt.date(),
        effective_to_date=parse_datetime("effective_to_date").dt.date(),
        dp_flag=pl.col("dp_flag").cast(pl.String),
    ).with_columns(
        effective_from_date_key=_nullable_date_key("effective_from_date"),
        effective_to_date_key=_nullable_date_key("effective_to_date"),
        surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES),
    )
    return with_zone_key(rows, zones).select(list(SCHEMA))


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver STTM market parameter fact.",
    ins={
        "int680": AssetIn(key=INT680_KEY),
        "zones": AssetIn(key=ZONES_KEY),
    },
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "parquet"},
    retry_policy=RetryPolicy(
        max_retries=3,
        delay=60,
        backoff=Backoff.EXPONENTIAL,
        jitter=Jitter.PLUS_MINUS,
    ),
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_fact_sttm_market_parameter(
    int680: LazyFrame,
    zones: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    """Materialize the silver STTM market parameter fact asset."""
    return _materialize_result(_select_sttm_market_parameters(int680, zones))


@asset_check(
    asset=silver_gas_fact_sttm_market_parameter,
    name="check_required_fields",
    description="Check required STTM market parameter fields are not null.",
)
def silver_gas_fact_sttm_market_parameter_required_fields(
    input_df: LazyFrame,
) -> AssetCheckResult:
    """Validate required fields for the silver STTM market parameter fact."""
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_fact_sttm_market_parameter_duplicate_row_check = duplicate_row_check_factory(
    assets_definition=silver_gas_fact_sttm_market_parameter,
    check_name="check_for_duplicate_rows",
    primary_key="surrogate_key",
    description="Check that surrogate_key is unique.",
)
silver_gas_fact_sttm_market_parameter_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_sttm_market_parameter,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)
silver_gas_fact_sttm_market_parameter_schema_drift_check = schema_drift_check_factory(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_sttm_market_parameter,
    check_name="check_schema_drift",
    description="Check for schema drift against the declared asset schema.",
)


@definitions
def defs() -> Definitions:
    """Return Dagster definitions for the silver STTM market parameter fact."""
    return Definitions(
        assets=[silver_gas_fact_sttm_market_parameter],
        asset_checks=[
            silver_gas_fact_sttm_market_parameter_duplicate_row_check,
            silver_gas_fact_sttm_market_parameter_schema_check,
            silver_gas_fact_sttm_market_parameter_schema_drift_check,
            silver_gas_fact_sttm_market_parameter_required_fields,
        ],
        sensors=[
            AutomationConditionSensorDefinition(
                name="silver_gas_fact_sttm_market_parameter_sensor",
                target=[silver_gas_fact_sttm_market_parameter.key],
                default_status=DEFAULT_SENSOR_STATUS,
                run_tags={"ecs/cpu": "512", "ecs/memory": "4096"},
            )
        ],
    )
