from datetime import date, datetime
from zoneinfo import ZoneInfo

import polars as pl
from dagster import (
    AssetCheckResult,
    AutomationCondition,
    Backoff,
    Definitions,
    Jitter,
    MaterializeResult,
    RetryPolicy,
    ScheduleDefinition,
    asset,
    asset_check,
    define_asset_job,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET, DEFAULT_SCHEDULE_STATUS
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_dim_date"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per calendar date from 1900-01-01 through the run date"
SURROGATE_KEY_SOURCES = ["gas_date"]
CALENDAR_START_DATE = date(1900, 1, 1)
SCHEDULE_CRON = "3 6 * * *"
SCHEDULE_TIMEZONE = "Australia/Melbourne"
_SCHEDULE_ZONE = ZoneInfo(SCHEDULE_TIMEZONE)

SCHEMA = {
    "surrogate_key": pl.String,
    "gas_date": pl.Date,
    "gas_year": pl.Int32,
    "gas_quarter": pl.Int8,
    "gas_month": pl.Int8,
    "gas_day": pl.Int8,
    "day_name": pl.String,
}

DESCRIPTIONS = {
    "surrogate_key": "Silver date dimension primary key generated by gas_date.",
    "gas_date": "Gas day date.",
    "gas_year": "Gas date calendar year.",
    "gas_quarter": "Gas date calendar quarter.",
    "gas_month": "Gas date calendar month.",
    "gas_day": "Gas date calendar day.",
    "day_name": "Gas date weekday name.",
}

REQUIRED_COLUMNS = ["surrogate_key", "gas_date"]


def _current_schedule_date() -> date:
    return datetime.now(tz=_SCHEDULE_ZONE).date()


def _select_dates(end_date: date) -> LazyFrame:
    if end_date < CALENDAR_START_DATE:
        raise ValueError(
            f"end_date must be on or after {CALENDAR_START_DATE.isoformat()}"
        )

    return (
        pl.LazyFrame(
            {
                "gas_date": pl.date_range(
                    start=CALENDAR_START_DATE,
                    end=end_date,
                    interval="1d",
                    eager=True,
                )
            }
        )
        .with_columns(
            surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES),
            gas_year=pl.col("gas_date").dt.year().cast(pl.Int32),
            gas_quarter=pl.col("gas_date").dt.quarter().cast(pl.Int8),
            gas_month=pl.col("gas_date").dt.month().cast(pl.Int8),
            gas_day=pl.col("gas_date").dt.day().cast(pl.Int8),
            day_name=pl.col("gas_date").dt.strftime("%A"),
        )
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(value=value)


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver gas date dimension calendar for gas model facts.",
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "calendar_start_date": CALENDAR_START_DATE.isoformat(),
        "schedule_cron": SCHEDULE_CRON,
        "schedule_timezone": SCHEDULE_TIMEZONE,
    },
    kinds={"table", "parquet"},
    retry_policy=RetryPolicy(
        max_retries=3,
        delay=60,
        backoff=Backoff.EXPONENTIAL,
        jitter=Jitter.PLUS_MINUS,
    ),
    automation_condition=AutomationCondition.missing(),
)
def silver_gas_dim_date() -> MaterializeResult[LazyFrame]:
    return _materialize_result(_select_dates(_current_schedule_date()))


@asset_check(
    asset=silver_gas_dim_date,
    name="check_required_fields",
    description="Check required dimension fields are not null.",
)
def silver_gas_dim_date_required_fields(input_df: LazyFrame) -> AssetCheckResult:
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_dim_date_duplicate_row_check = duplicate_row_check_factory(
    assets_definition=silver_gas_dim_date,
    check_name="check_for_duplicate_rows",
    primary_key="surrogate_key",
    description="Check that surrogate_key is unique.",
)

silver_gas_dim_date_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_dim_date,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)

silver_gas_dim_date_schema_drift_check = schema_drift_check_factory(
    schema=SCHEMA,
    assets_definition=silver_gas_dim_date,
    check_name="check_schema_drift",
    description="Check for schema drift against the declared asset schema.",
)


@definitions
def defs() -> Definitions:
    job = define_asset_job(
        name="silver_gas_dim_date_job",
        selection=[silver_gas_dim_date],
    )
    schedule = ScheduleDefinition(
        name="silver_gas_dim_date_schedule",
        job=job,
        cron_schedule=SCHEDULE_CRON,
        execution_timezone=SCHEDULE_TIMEZONE,
        default_status=DEFAULT_SCHEDULE_STATUS,
    )

    return Definitions(
        assets=[silver_gas_dim_date],
        asset_checks=[
            silver_gas_dim_date_duplicate_row_check,
            silver_gas_dim_date_schema_check,
            silver_gas_dim_date_schema_drift_check,
            silver_gas_dim_date_required_fields,
        ],
        schedules=[schedule],
    )
