"""Dagster definitions for the silver STTM default allocation notice fact asset."""

import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AutomationCondition,
    AutomationConditionSensorDefinition,
    Backoff,
    Definitions,
    Jitter,
    MaterializeResult,
    RetryPolicy,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET, DEFAULT_SENSOR_STATUS
from aemo_etl.defs.gas_model._sttm_common import (
    FACILITIES_KEY,
    ZONES_KEY,
    parse_datetime,
    source_asset_key,
    source_metadata,
    source_table,
    with_facility_zone_keys,
)
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_fact_sttm_default_allocation_notice"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per STTM default allocation notice"
SURROGATE_KEY_SOURCES = [
    "source_system",
    "source_table",
    "notice_id",
    "source_surrogate_key",
]
SOURCE_TABLES = [source_table("int675_v1_default_allocation_notice_rpt_1")]
INT675_KEY = source_asset_key("int675_v1_default_allocation_notice_rpt_1")

_SOURCE_KEY_DEPS = [TableColumnDep(asset_key=INT675_KEY, column_name="surrogate_key")]
_SOURCE_HUB_ID_DEPS = [
    TableColumnDep(asset_key=INT675_KEY, column_name="hub_identifier")
]
_SOURCE_FACILITY_ID_DEPS = [
    TableColumnDep(asset_key=INT675_KEY, column_name="facility_identifier")
]

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": _SOURCE_KEY_DEPS,
        "date_key": [TableColumnDep(asset_key=INT675_KEY, column_name="gas_date")],
        "facility_key": [
            *_SOURCE_HUB_ID_DEPS,
            *_SOURCE_FACILITY_ID_DEPS,
            TableColumnDep(asset_key=FACILITIES_KEY, column_name="surrogate_key"),
        ],
        "zone_key": [
            *_SOURCE_HUB_ID_DEPS,
            TableColumnDep(asset_key=ZONES_KEY, column_name="surrogate_key"),
        ],
        "notice_id": [
            TableColumnDep(asset_key=INT675_KEY, column_name="notice_identifier")
        ],
        "source_hub_id": _SOURCE_HUB_ID_DEPS,
        "source_facility_id": _SOURCE_FACILITY_ID_DEPS,
        "notice_message": [
            TableColumnDep(asset_key=INT675_KEY, column_name="notice_message")
        ],
        "source_surrogate_key": _SOURCE_KEY_DEPS,
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "date_key": pl.String,
    "facility_key": pl.String,
    "zone_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_table": pl.String,
    "source_report_id": pl.String,
    "notice_id": pl.String,
    "gas_date": pl.Date,
    "source_hub_id": pl.String,
    "source_hub_name": pl.String,
    "source_facility_id": pl.String,
    "facility_name": pl.String,
    "notice_message": pl.String,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver fact primary key generated by surrogate_key_sources.",
    "date_key": "Deterministic silver_gas_dim_date surrogate_key for gas_date.",
    "facility_key": "Parent silver_gas_dim_facility surrogate_key when resolvable.",
    "zone_key": "Parent silver_gas_dim_zone surrogate_key for STTM hub when resolvable.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the row.",
    "source_table": "Specific silver source table for this row.",
    "source_report_id": "STTM report identifier.",
    "notice_id": "Source default allocation notice identifier.",
    "gas_date": "Gas day date for which default allocation was applied.",
    "source_hub_id": "Source-system hub identifier.",
    "source_hub_name": "Source-system hub name.",
    "source_facility_id": "Source-system facility identifier.",
    "facility_name": "Source-system facility name.",
    "notice_message": "Source default allocation notice message.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "date_key",
    "source_system",
    "source_table",
    "source_report_id",
    "notice_id",
    "gas_date",
    "source_hub_id",
    "source_facility_id",
    "source_surrogate_key",
]


def _select_sttm_default_allocation_notices(
    int675: LazyFrame,
    facilities: LazyFrame,
    zones: LazyFrame,
) -> LazyFrame:
    rows = int675.select(
        *source_metadata(table_name=SOURCE_TABLES[0], report_id="INT675"),
        notice_id=pl.col("notice_identifier").cast(pl.String),
        gas_date=parse_datetime("gas_date").dt.date(),
        source_hub_id=pl.col("hub_identifier").cast(pl.String),
        source_hub_name=pl.col("hub_name").cast(pl.String),
        source_facility_id=pl.col("facility_identifier").cast(pl.String),
        facility_name=pl.col("facility_name").cast(pl.String),
        notice_message=pl.col("notice_message").cast(pl.String),
    ).with_columns(
        date_key=get_surrogate_key(["gas_date"]),
        surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES),
    )
    return with_facility_zone_keys(rows, facilities, zones).select(list(SCHEMA))


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver STTM default allocation notice fact.",
    ins={
        "int675": AssetIn(key=INT675_KEY),
        "facilities": AssetIn(key=FACILITIES_KEY),
        "zones": AssetIn(key=ZONES_KEY),
    },
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "parquet"},
    retry_policy=RetryPolicy(
        max_retries=3,
        delay=60,
        backoff=Backoff.EXPONENTIAL,
        jitter=Jitter.PLUS_MINUS,
    ),
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_fact_sttm_default_allocation_notice(
    int675: LazyFrame,
    facilities: LazyFrame,
    zones: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    """Materialize the silver STTM default allocation notice fact asset."""
    return _materialize_result(
        _select_sttm_default_allocation_notices(int675, facilities, zones)
    )


@asset_check(
    asset=silver_gas_fact_sttm_default_allocation_notice,
    name="check_required_fields",
    description="Check required STTM default allocation notice fields are not null.",
)
def silver_gas_fact_sttm_default_allocation_notice_required_fields(
    input_df: LazyFrame,
) -> AssetCheckResult:
    """Validate required fields for the silver STTM default allocation notice fact."""
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_fact_sttm_default_allocation_notice_duplicate_row_check = (
    duplicate_row_check_factory(
        assets_definition=silver_gas_fact_sttm_default_allocation_notice,
        check_name="check_for_duplicate_rows",
        primary_key="surrogate_key",
        description="Check that surrogate_key is unique.",
    )
)
silver_gas_fact_sttm_default_allocation_notice_schema_check = (
    schema_matches_check_factor(
        schema=SCHEMA,
        assets_definition=silver_gas_fact_sttm_default_allocation_notice,
        check_name="check_schema_matches",
        description="Check observed schema matches target schema.",
    )
)
silver_gas_fact_sttm_default_allocation_notice_schema_drift_check = (
    schema_drift_check_factory(
        schema=SCHEMA,
        assets_definition=silver_gas_fact_sttm_default_allocation_notice,
        check_name="check_schema_drift",
        description="Check for schema drift against the declared asset schema.",
    )
)


@definitions
def defs() -> Definitions:
    """Return Dagster definitions for the silver STTM default allocation notice."""
    return Definitions(
        assets=[silver_gas_fact_sttm_default_allocation_notice],
        asset_checks=[
            silver_gas_fact_sttm_default_allocation_notice_duplicate_row_check,
            silver_gas_fact_sttm_default_allocation_notice_schema_check,
            silver_gas_fact_sttm_default_allocation_notice_schema_drift_check,
            silver_gas_fact_sttm_default_allocation_notice_required_fields,
        ],
        sensors=[
            AutomationConditionSensorDefinition(
                name="silver_gas_fact_sttm_default_allocation_notice_sensor",
                target=[silver_gas_fact_sttm_default_allocation_notice.key],
                default_status=DEFAULT_SENSOR_STATUS,
                run_tags={"ecs/cpu": "512", "ecs/memory": "4096"},
            )
        ],
    )
