"""Dagster definitions for the silver gas location dimension asset."""

from typing import cast

import polars as pl
from dagster import (
    AssetChecksDefinition,
    AssetIn,
    AssetKey,
    AssetsDefinition,
    Definitions,
    MaterializeResult,
    SensorDefinition,
    TableColumnDep,
    TableColumnLineage,
    definitions,
)
from polars import LazyFrame

from aemo_etl.defs.gas_model._asset_shell import (
    GasModelAssetSpec,
    build_gas_model_asset_definitions,
)
from aemo_etl.utils import get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_dim_location"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one current row per source-qualified gas location"
SURROGATE_KEY_SOURCES = ["source_system", "source_location_id"]
SOURCE_TABLES = ["silver.gbb.silver_gasbb_locations_list"]
SOURCE_SYSTEM = "GBB"
GBB_LOCATIONS_KEY = AssetKey(["silver", "gbb", "silver_gasbb_locations_list"])

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="LocationId")
        ],
        "source_location_id": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="LocationId")
        ],
        "location_name": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="LocationName")
        ],
        "state": [TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="State")],
        "location_type": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="LocationType")
        ],
        "location_description": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="Description")
        ],
        "source_last_updated": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="LastUpdated")
        ],
        "source_last_updated_timestamp": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="LastUpdated")
        ],
        "source_surrogate_key": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="surrogate_key")
        ],
        "source_file": [
            TableColumnDep(asset_key=GBB_LOCATIONS_KEY, column_name="source_file")
        ],
        "ingested_timestamp": [
            TableColumnDep(
                asset_key=GBB_LOCATIONS_KEY, column_name="ingested_timestamp"
            )
        ],
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_location_id": pl.String,
    "location_name": pl.String,
    "state": pl.String,
    "location_type": pl.String,
    "location_description": pl.String,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver dimension primary key generated by surrogate_key_sources.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the gas model row.",
    "source_location_id": "Source-system location identifier.",
    "location_name": "Canonical gas location name.",
    "state": "Australian state for the gas location.",
    "location_type": "Source location type.",
    "location_description": "Source location description.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "source_system",
    "source_location_id",
    "location_name",
]


def _parse_source_last_updated(column: str) -> pl.Expr:
    source = pl.col(column)
    return pl.coalesce(
        source.str.strptime(pl.Datetime("us"), "%d %b %Y %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d", strict=False),
    )


def _select_current_locations(df: LazyFrame) -> LazyFrame:
    return (
        df.with_columns(
            source_system=pl.lit(SOURCE_SYSTEM),
            source_tables=pl.lit(SOURCE_TABLES).cast(pl.List(pl.String)),
            source_location_id=pl.col("LocationId").cast(pl.String),
            location_name=pl.col("LocationName").cast(pl.String),
            state=pl.col("State").cast(pl.String),
            location_type=pl.col("LocationType").cast(pl.String),
            location_description=pl.col("Description").cast(pl.String),
            source_last_updated=pl.col("LastUpdated").cast(pl.String),
            source_last_updated_timestamp=_parse_source_last_updated("LastUpdated"),
            source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        )
        .with_columns(
            surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES),
        )
        .sort(
            [
                "source_system",
                "source_location_id",
                "source_last_updated_timestamp",
                "ingested_timestamp",
            ],
            descending=[False, False, True, True],
            nulls_last=True,
        )
        .unique(subset=SURROGATE_KEY_SOURCES, keep="first", maintain_order=True)
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


def _materialize_silver_gas_dim_location(
    gbb_locations: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    """Materialize the silver gas location dimension asset."""
    return _materialize_result(_select_current_locations(gbb_locations))


_GAS_MODEL_SPEC = GasModelAssetSpec(
    name=TABLE_NAME,
    description="Silver current-snapshot gas location dimension.",
    ins={"gbb_locations": AssetIn(key=GBB_LOCATIONS_KEY)},
    materialize=_materialize_silver_gas_dim_location,
    schema=SCHEMA,
    column_descriptions=DESCRIPTIONS,
    grain=GRAIN,
    surrogate_key_sources=SURROGATE_KEY_SOURCES,
    source_tables=SOURCE_TABLES,
    required_columns=REQUIRED_COLUMNS,
    required_fields_description="Check required dimension fields are not null.",
)

type _LocationAssetChecks = tuple[
    AssetChecksDefinition,
    AssetChecksDefinition,
    AssetChecksDefinition,
    AssetChecksDefinition,
]


def _build_shell_parts() -> tuple[
    AssetsDefinition,
    _LocationAssetChecks,
    tuple[SensorDefinition, ...],
]:
    definitions_result = build_gas_model_asset_definitions(_GAS_MODEL_SPEC)
    assets = list(definitions_result.assets or [])
    asset_checks = tuple(definitions_result.asset_checks or ())
    sensors = tuple(definitions_result.sensors or ())

    assert len(assets) == 1, f"expected one asset definition, got {len(assets)}"
    assert len(asset_checks) == 4, (
        f"expected four asset checks, got {len(asset_checks)}"
    )
    asset_definition = assets[0]
    assert isinstance(asset_definition, AssetsDefinition), (
        f"expected AssetsDefinition, got {type(asset_definition)}"
    )
    assert all(
        isinstance(asset_check_definition, AssetChecksDefinition)
        for asset_check_definition in asset_checks
    ), "expected only AssetChecksDefinition values"

    return (
        asset_definition,
        cast(_LocationAssetChecks, asset_checks),
        sensors,
    )


(
    silver_gas_dim_location,
    _SILVER_GAS_DIM_LOCATION_ASSET_CHECKS,
    _SILVER_GAS_DIM_LOCATION_SENSORS,
) = _build_shell_parts()
(
    silver_gas_dim_location_duplicate_row_check,
    silver_gas_dim_location_schema_check,
    silver_gas_dim_location_schema_drift_check,
    silver_gas_dim_location_required_fields,
) = _SILVER_GAS_DIM_LOCATION_ASSET_CHECKS


@definitions
def defs() -> Definitions:
    """Return Dagster definitions for the silver gas location dimension asset."""
    return Definitions(
        assets=[silver_gas_dim_location],
        asset_checks=list(_SILVER_GAS_DIM_LOCATION_ASSET_CHECKS),
        sensors=list(_SILVER_GAS_DIM_LOCATION_SENSORS),
    )
