import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AssetKey,
    AutomationCondition,
    AutomationConditionSensorDefinition,
    Definitions,
    MaterializeResult,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET, DEFAULT_SENSOR_STATUS
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_fact_connection_point_flow"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per gas date, facility, connection point, flow direction, and source update"
SURROGATE_KEY_SOURCES = [
    "source_system",
    "gas_date",
    "source_facility_id",
    "source_connection_point_id",
    "flow_direction",
    "source_last_updated_timestamp",
]
SOURCE_TABLES = ["silver.gbb.silver_gasbb_pipeline_connection_flow_v2"]
SOURCE_SYSTEM = "GBB"

GBB_CONNECTION_FLOW_KEY = AssetKey(
    ["silver", "gbb", "silver_gasbb_pipeline_connection_flow_v2"]
)
DATES_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_date"])
FACILITIES_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_facility"])
LOCATIONS_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_location"])
CONNECTION_POINTS_KEY = AssetKey(
    ["silver", "gas_model", "silver_gas_dim_connection_point"]
)

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": [
            TableColumnDep(asset_key=GBB_CONNECTION_FLOW_KEY, column_name="GasDate"),
            TableColumnDep(asset_key=GBB_CONNECTION_FLOW_KEY, column_name="FacilityId"),
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="ConnectionPointId"
            ),
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="FlowDirection"
            ),
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="LastUpdated"
            ),
        ],
        "date_key": [
            TableColumnDep(asset_key=GBB_CONNECTION_FLOW_KEY, column_name="GasDate"),
            TableColumnDep(asset_key=DATES_KEY, column_name="surrogate_key"),
        ],
        "facility_key": [
            TableColumnDep(asset_key=GBB_CONNECTION_FLOW_KEY, column_name="FacilityId"),
            TableColumnDep(asset_key=FACILITIES_KEY, column_name="surrogate_key"),
        ],
        "location_key": [
            TableColumnDep(asset_key=GBB_CONNECTION_FLOW_KEY, column_name="LocationId"),
            TableColumnDep(asset_key=LOCATIONS_KEY, column_name="surrogate_key"),
        ],
        "connection_point_key": [
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="ConnectionPointId"
            ),
            TableColumnDep(
                asset_key=CONNECTION_POINTS_KEY, column_name="surrogate_key"
            ),
        ],
        "zone_key": [
            TableColumnDep(asset_key=CONNECTION_POINTS_KEY, column_name="zone_key")
        ],
        "actual_quantity_tj": [
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="ActualQuantity"
            )
        ],
        "source_surrogate_key": [
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="surrogate_key"
            )
        ],
        "source_file": [
            TableColumnDep(asset_key=GBB_CONNECTION_FLOW_KEY, column_name="source_file")
        ],
        "ingested_timestamp": [
            TableColumnDep(
                asset_key=GBB_CONNECTION_FLOW_KEY, column_name="ingested_timestamp"
            )
        ],
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "date_key": pl.String,
    "facility_key": pl.String,
    "location_key": pl.String,
    "connection_point_key": pl.String,
    "zone_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "gas_date": pl.Date,
    "source_facility_id": pl.String,
    "source_connection_point_id": pl.String,
    "flow_direction": pl.String,
    "actual_quantity_tj": pl.Float64,
    "quality": pl.String,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver fact primary key generated by surrogate_key_sources.",
    "date_key": "Parent silver_gas_dim_date surrogate_key.",
    "facility_key": "Parent silver_gas_dim_facility surrogate_key when resolvable.",
    "location_key": "Parent silver_gas_dim_location surrogate_key when resolvable.",
    "connection_point_key": "Parent silver_gas_dim_connection_point surrogate_key when resolvable.",
    "zone_key": "Parent silver_gas_dim_zone surrogate_key inherited from the connection point.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the gas model row.",
    "gas_date": "Gas day date.",
    "source_facility_id": "Source-system facility identifier.",
    "source_connection_point_id": "Source-system connection point identifier.",
    "flow_direction": "Gas flow direction.",
    "actual_quantity_tj": "Actual connection point flow quantity in TJ.",
    "quality": "Source quality flag.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "date_key",
    "source_system",
    "gas_date",
    "source_facility_id",
    "source_connection_point_id",
    "flow_direction",
]


def _parse_datetime(column: str) -> pl.Expr:
    source = pl.col(column).cast(pl.String)
    return pl.coalesce(
        source.str.strptime(pl.Datetime("us"), "%d %b %Y %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%d %B %Y %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%d %b %Y", strict=False),
        source.str.strptime(pl.Datetime("us"), "%d %B %Y", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y-%m-%d %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y-%m-%d", strict=False),
    )


def _select_connection_point_flow(
    gbb_connection_flow: LazyFrame,
    dates: LazyFrame,
    facilities: LazyFrame,
    locations: LazyFrame,
    connection_points: LazyFrame,
) -> LazyFrame:
    date_keys = dates.select(
        date_key=pl.col("surrogate_key"), gas_date=pl.col("gas_date")
    )
    facility_keys = facilities.filter(pl.col("source_system") == SOURCE_SYSTEM).select(
        facility_key=pl.col("surrogate_key"),
        source_facility_id=pl.col("source_facility_id"),
    )
    location_keys = locations.filter(pl.col("source_system") == SOURCE_SYSTEM).select(
        location_key=pl.col("surrogate_key"),
        source_location_id=pl.col("source_location_id"),
    )
    connection_point_keys = connection_points.filter(
        pl.col("source_system") == SOURCE_SYSTEM
    ).select(
        connection_point_key=pl.col("surrogate_key"),
        zone_key=pl.col("zone_key"),
        source_facility_id=pl.col("source_facility_id"),
        source_connection_point_id=pl.col("source_connection_point_id"),
        flow_direction=pl.col("flow_direction"),
    )

    return (
        gbb_connection_flow.with_columns(
            source_system=pl.lit(SOURCE_SYSTEM),
            source_tables=pl.lit(SOURCE_TABLES).cast(pl.List(pl.String)),
            gas_date=_parse_datetime("GasDate").dt.date(),
            source_facility_id=pl.col("FacilityId").cast(pl.String),
            source_connection_point_id=pl.col("ConnectionPointId").cast(pl.String),
            source_location_id=pl.col("LocationId").cast(pl.String),
            flow_direction=pl.col("FlowDirection").cast(pl.String),
            actual_quantity_tj=pl.col("ActualQuantity").cast(pl.Float64),
            quality=pl.col("Quality").cast(pl.String),
            source_last_updated=pl.col("LastUpdated").cast(pl.String),
            source_last_updated_timestamp=_parse_datetime("LastUpdated"),
            source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        )
        .with_columns(surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES))
        .join(date_keys, on="gas_date", how="left")
        .join(facility_keys, on="source_facility_id", how="left")
        .join(location_keys, on="source_location_id", how="left")
        .join(
            connection_point_keys,
            on=[
                "source_facility_id",
                "source_connection_point_id",
                "flow_direction",
            ],
            how="left",
        )
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver gas connection point flow fact.",
    ins={
        "gbb_connection_flow": AssetIn(key=GBB_CONNECTION_FLOW_KEY),
        "dates": AssetIn(key=DATES_KEY),
        "facilities": AssetIn(key=FACILITIES_KEY),
        "locations": AssetIn(key=LOCATIONS_KEY),
        "connection_points": AssetIn(key=CONNECTION_POINTS_KEY),
    },
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "parquet"},
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_fact_connection_point_flow(
    gbb_connection_flow: LazyFrame,
    dates: LazyFrame,
    facilities: LazyFrame,
    locations: LazyFrame,
    connection_points: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    return _materialize_result(
        _select_connection_point_flow(
            gbb_connection_flow,
            dates,
            facilities,
            locations,
            connection_points,
        )
    )


@asset_check(
    asset=silver_gas_fact_connection_point_flow,
    name="check_required_fields",
    description="Check required fact fields are not null.",
)
def silver_gas_fact_connection_point_flow_required_fields(
    input_df: LazyFrame,
) -> AssetCheckResult:
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_fact_connection_point_flow_duplicate_row_check = duplicate_row_check_factory(
    assets_definition=silver_gas_fact_connection_point_flow,
    check_name="check_for_duplicate_rows",
    primary_key="surrogate_key",
    description="Check that surrogate_key is unique.",
)

silver_gas_fact_connection_point_flow_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_connection_point_flow,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)

silver_gas_fact_connection_point_flow_schema_drift_check = schema_drift_check_factory(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_connection_point_flow,
    check_name="check_schema_drift",
    description="Check for schema drift against the declared asset schema.",
)


@definitions
def defs() -> Definitions:
    return Definitions(
        assets=[silver_gas_fact_connection_point_flow],
        asset_checks=[
            silver_gas_fact_connection_point_flow_duplicate_row_check,
            silver_gas_fact_connection_point_flow_schema_check,
            silver_gas_fact_connection_point_flow_schema_drift_check,
            silver_gas_fact_connection_point_flow_required_fields,
        ],
        sensors=[
            AutomationConditionSensorDefinition(
                name="silver_gas_fact_connection_point_flow_sensor",
                target=[silver_gas_fact_connection_point_flow.key],
                default_status=DEFAULT_SENSOR_STATUS,
            )
        ],
    )
