import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AssetKey,
    AutomationCondition,
    Definitions,
    MaterializeResult,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_fact_linepack"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per source-system linepack observation"
SURROGATE_KEY_SOURCES = [
    "source_system",
    "source_table",
    "gas_date",
    "source_facility_id",
    "observation_timestamp",
    "source_last_updated_timestamp",
    "source_surrogate_key",
]
SOURCE_TABLES = [
    "silver.gbb.silver_gasbb_linepack_capacity_adequacy",
    "silver.vicgas.silver_int128_v4_actual_linepack_1",
]

GBB_LINEPACK_KEY = AssetKey(
    ["silver", "gbb", "silver_gasbb_linepack_capacity_adequacy"]
)
VICGAS_LINEPACK_KEY = AssetKey(
    ["silver", "vicgas", "silver_int128_v4_actual_linepack_1"]
)
DATES_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_date"])
FACILITIES_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_facility"])
ZONES_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_zone"])

_SOURCE_LINEPACK_DEPS = [
    TableColumnDep(asset_key=GBB_LINEPACK_KEY, column_name="surrogate_key"),
    TableColumnDep(asset_key=VICGAS_LINEPACK_KEY, column_name="surrogate_key"),
]

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": _SOURCE_LINEPACK_DEPS,
        "date_key": [
            TableColumnDep(asset_key=GBB_LINEPACK_KEY, column_name="GasDate"),
            TableColumnDep(
                asset_key=VICGAS_LINEPACK_KEY, column_name="commencement_datetime"
            ),
            TableColumnDep(asset_key=DATES_KEY, column_name="surrogate_key"),
        ],
        "facility_key": [
            TableColumnDep(asset_key=GBB_LINEPACK_KEY, column_name="FacilityId"),
            TableColumnDep(asset_key=FACILITIES_KEY, column_name="surrogate_key"),
        ],
        "zone_key": [TableColumnDep(asset_key=ZONES_KEY, column_name="surrogate_key")],
        "actual_linepack_gj": [
            TableColumnDep(asset_key=VICGAS_LINEPACK_KEY, column_name="actual_linepack")
        ],
        "adequacy_flag": [
            TableColumnDep(asset_key=GBB_LINEPACK_KEY, column_name="Flag")
        ],
        "adequacy_description": [
            TableColumnDep(asset_key=GBB_LINEPACK_KEY, column_name="Description")
        ],
        "source_surrogate_key": _SOURCE_LINEPACK_DEPS,
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "date_key": pl.String,
    "facility_key": pl.String,
    "zone_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_table": pl.String,
    "gas_date": pl.Date,
    "observation_timestamp": pl.Datetime("us"),
    "source_facility_id": pl.String,
    "actual_linepack_gj": pl.Float64,
    "adequacy_flag": pl.String,
    "adequacy_description": pl.String,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver fact primary key generated by surrogate_key_sources.",
    "date_key": "Parent silver_gas_dim_date surrogate_key.",
    "facility_key": "Parent silver_gas_dim_facility surrogate_key when resolvable.",
    "zone_key": "Parent silver_gas_dim_zone surrogate_key when resolvable.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the gas model row.",
    "source_table": "Specific silver source table for this row.",
    "gas_date": "Gas day date.",
    "observation_timestamp": "Timestamp for the linepack observation where provided.",
    "source_facility_id": "Source-system facility identifier where provided.",
    "actual_linepack_gj": "VICGAS actual physical linepack in GJ.",
    "adequacy_flag": "GBB linepack capacity adequacy flag.",
    "adequacy_description": "GBB linepack capacity adequacy description.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = ["surrogate_key", "date_key", "source_system", "gas_date"]


def _parse_datetime(column: str) -> pl.Expr:
    source = pl.col(column).cast(pl.String)
    return pl.coalesce(
        source.str.strptime(pl.Datetime("us"), "%d %b %Y %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%d %B %Y %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%d %b %Y", strict=False),
        source.str.strptime(pl.Datetime("us"), "%d %B %Y", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y-%m-%d %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y-%m-%d", strict=False),
    )


def _gbb_linepack_rows(df: LazyFrame) -> LazyFrame:
    return df.select(
        source_system=pl.lit("GBB"),
        source_tables=pl.lit([SOURCE_TABLES[0]]).cast(pl.List(pl.String)),
        source_table=pl.lit(SOURCE_TABLES[0]),
        gas_date=_parse_datetime("GasDate").dt.date(),
        observation_timestamp=pl.lit(None).cast(pl.Datetime("us")),
        source_facility_id=pl.col("FacilityId").cast(pl.String),
        actual_linepack_gj=pl.lit(None).cast(pl.Float64),
        adequacy_flag=pl.col("Flag").cast(pl.String),
        adequacy_description=pl.col("Description").cast(pl.String),
        source_last_updated=pl.col("LastUpdated").cast(pl.String),
        source_last_updated_timestamp=_parse_datetime("LastUpdated"),
        source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        source_file=pl.col("source_file").cast(pl.String),
        ingested_timestamp=pl.col("ingested_timestamp"),
    )


def _vicgas_linepack_rows(df: LazyFrame) -> LazyFrame:
    return df.select(
        source_system=pl.lit("VICGAS"),
        source_tables=pl.lit([SOURCE_TABLES[1]]).cast(pl.List(pl.String)),
        source_table=pl.lit(SOURCE_TABLES[1]),
        gas_date=_parse_datetime("commencement_datetime").dt.date(),
        observation_timestamp=_parse_datetime("commencement_datetime"),
        source_facility_id=pl.lit(None).cast(pl.String),
        actual_linepack_gj=pl.col("actual_linepack").cast(pl.Float64),
        adequacy_flag=pl.lit(None).cast(pl.String),
        adequacy_description=pl.lit(None).cast(pl.String),
        source_last_updated=pl.col("current_date").cast(pl.String),
        source_last_updated_timestamp=_parse_datetime("current_date"),
        source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        source_file=pl.col("source_file").cast(pl.String),
        ingested_timestamp=pl.col("ingested_timestamp"),
    )


def _select_linepack(
    gbb_linepack: LazyFrame,
    vicgas_linepack: LazyFrame,
    dates: LazyFrame,
    facilities: LazyFrame,
) -> LazyFrame:
    date_keys = dates.select(
        date_key=pl.col("surrogate_key"), gas_date=pl.col("gas_date")
    )
    facility_keys = facilities.filter(pl.col("source_system") == "GBB").select(
        facility_key=pl.col("surrogate_key"),
        source_facility_id=pl.col("source_facility_id"),
    )
    combined = pl.concat(
        [_gbb_linepack_rows(gbb_linepack), _vicgas_linepack_rows(vicgas_linepack)],
        how="diagonal_relaxed",
    )

    return (
        combined.with_columns(
            zone_key=pl.lit(None).cast(pl.String),
            surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES),
        )
        .join(date_keys, on="gas_date", how="left")
        .join(facility_keys, on="source_facility_id", how="left")
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver gas linepack fact.",
    ins={
        "gbb_linepack": AssetIn(key=GBB_LINEPACK_KEY),
        "vicgas_linepack": AssetIn(key=VICGAS_LINEPACK_KEY),
        "dates": AssetIn(key=DATES_KEY),
        "facilities": AssetIn(key=FACILITIES_KEY),
    },
    io_manager_key="aemo_deltalake_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "deltalake"},
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_fact_linepack(
    gbb_linepack: LazyFrame,
    vicgas_linepack: LazyFrame,
    dates: LazyFrame,
    facilities: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    return _materialize_result(
        _select_linepack(gbb_linepack, vicgas_linepack, dates, facilities)
    )


@asset_check(
    asset=silver_gas_fact_linepack,
    name="check_required_fields",
    description="Check required fact fields are not null.",
)
def silver_gas_fact_linepack_required_fields(input_df: LazyFrame) -> AssetCheckResult:
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_fact_linepack_duplicate_row_check = duplicate_row_check_factory(
    assets_definition=silver_gas_fact_linepack,
    check_name="check_for_duplicate_rows",
    primary_key="surrogate_key",
    description="Check that surrogate_key is unique.",
)

silver_gas_fact_linepack_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_linepack,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)

silver_gas_fact_linepack_schema_drift_check = schema_drift_check_factory(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_linepack,
    check_name="check_schema_drift",
    description="Check for schema drift against the declared asset schema.",
)


@definitions
def defs() -> Definitions:
    return Definitions(
        assets=[silver_gas_fact_linepack],
        asset_checks=[
            silver_gas_fact_linepack_duplicate_row_check,
            silver_gas_fact_linepack_schema_check,
            silver_gas_fact_linepack_schema_drift_check,
            silver_gas_fact_linepack_required_fields,
        ],
    )
