"""Dagster definitions for the silver STTM allocation quantity fact asset."""

import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AutomationCondition,
    AutomationConditionSensorDefinition,
    Backoff,
    Definitions,
    Jitter,
    MaterializeResult,
    RetryPolicy,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET, DEFAULT_SENSOR_STATUS
from aemo_etl.defs.gas_model._sttm_common import (
    FACILITIES_KEY,
    ZONES_KEY,
    parse_datetime,
    source_asset_key,
    source_metadata,
    source_table,
    with_facility_zone_keys,
)
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_fact_sttm_allocation_quantity"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one row per STTM gas date, facility, flow direction, and allocation version"
SURROGATE_KEY_SOURCES = [
    "source_system",
    "source_table",
    "gas_date",
    "source_hub_id",
    "source_facility_id",
    "flow_direction",
    "allocation_version",
    "allocation_qty_quality_type",
    "source_surrogate_key",
]
SOURCE_TABLES = [
    source_table("int658_v1_latest_allocation_quantity_rpt_1"),
    source_table("int689_v1_expost_allocation_quantity_rpt_1"),
]
INT658_KEY = source_asset_key("int658_v1_latest_allocation_quantity_rpt_1")
INT689_KEY = source_asset_key("int689_v1_expost_allocation_quantity_rpt_1")

_SOURCE_KEY_DEPS = [
    TableColumnDep(asset_key=INT658_KEY, column_name="surrogate_key"),
    TableColumnDep(asset_key=INT689_KEY, column_name="surrogate_key"),
]
_SOURCE_HUB_ID_DEPS = [
    TableColumnDep(asset_key=INT658_KEY, column_name="hub_identifier"),
    TableColumnDep(asset_key=INT689_KEY, column_name="hub_identifier"),
]
_SOURCE_FACILITY_ID_DEPS = [
    TableColumnDep(asset_key=INT658_KEY, column_name="facility_identifier"),
    TableColumnDep(asset_key=INT689_KEY, column_name="facility_identifier"),
]

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": _SOURCE_KEY_DEPS,
        "date_key": [
            TableColumnDep(asset_key=INT658_KEY, column_name="gas_date"),
            TableColumnDep(asset_key=INT689_KEY, column_name="gas_date"),
        ],
        "facility_key": [
            *_SOURCE_HUB_ID_DEPS,
            *_SOURCE_FACILITY_ID_DEPS,
            TableColumnDep(asset_key=FACILITIES_KEY, column_name="surrogate_key"),
        ],
        "zone_key": [
            *_SOURCE_HUB_ID_DEPS,
            TableColumnDep(asset_key=ZONES_KEY, column_name="surrogate_key"),
        ],
        "source_hub_id": _SOURCE_HUB_ID_DEPS,
        "source_facility_id": _SOURCE_FACILITY_ID_DEPS,
        "allocation_qty_inc_mos_gj": [
            TableColumnDep(asset_key=INT658_KEY, column_name="allocation_qty_inc_mos"),
            TableColumnDep(asset_key=INT689_KEY, column_name="allocation_qty_inc_mos"),
        ],
        "allocation_qty_quality_type": [
            TableColumnDep(
                asset_key=INT689_KEY, column_name="allocation_qty_quality_type"
            )
        ],
        "source_surrogate_key": _SOURCE_KEY_DEPS,
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "date_key": pl.String,
    "facility_key": pl.String,
    "zone_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_table": pl.String,
    "source_report_id": pl.String,
    "gas_date": pl.Date,
    "allocation_version": pl.String,
    "source_hub_id": pl.String,
    "source_hub_name": pl.String,
    "source_facility_id": pl.String,
    "facility_name": pl.String,
    "flow_direction": pl.String,
    "allocation_qty_inc_mos_gj": pl.Float64,
    "allocation_qty_quality_type": pl.String,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver fact primary key generated by surrogate_key_sources.",
    "date_key": "Deterministic silver_gas_dim_date surrogate_key for gas_date.",
    "facility_key": "Parent silver_gas_dim_facility surrogate_key when resolvable.",
    "zone_key": "Parent silver_gas_dim_zone surrogate_key for STTM hub when resolvable.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the row.",
    "source_table": "Specific silver source table for this row.",
    "source_report_id": "STTM report identifier.",
    "gas_date": "Gas day date.",
    "allocation_version": "Source-specific allocation version represented by the row.",
    "source_hub_id": "Source-system hub identifier.",
    "source_hub_name": "Source-system hub name.",
    "source_facility_id": "Source-system facility identifier.",
    "facility_name": "Source-system facility name.",
    "flow_direction": "STTM source flow-direction flag.",
    "allocation_qty_inc_mos_gj": "Source allocation_qty_inc_mos value, inclusive of MOS gas.",
    "allocation_qty_quality_type": "Source ex-post allocation quantity data-quality flag.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "date_key",
    "source_system",
    "source_table",
    "source_report_id",
    "gas_date",
    "allocation_version",
    "source_hub_id",
    "source_facility_id",
    "flow_direction",
    "allocation_qty_inc_mos_gj",
    "source_surrogate_key",
]


def _allocation_rows(
    df: LazyFrame,
    *,
    table_name: str,
    report_id: str,
    allocation_version: str,
    has_quality_type: bool,
) -> LazyFrame:
    return df.select(
        *source_metadata(table_name=table_name, report_id=report_id),
        gas_date=parse_datetime("gas_date").dt.date(),
        allocation_version=pl.lit(allocation_version),
        source_hub_id=pl.col("hub_identifier").cast(pl.String),
        source_hub_name=pl.col("hub_name").cast(pl.String),
        source_facility_id=pl.col("facility_identifier").cast(pl.String),
        facility_name=pl.col("facility_name").cast(pl.String),
        flow_direction=pl.col("flow_direction").cast(pl.String),
        allocation_qty_inc_mos_gj=pl.col("allocation_qty_inc_mos").cast(pl.Float64),
        allocation_qty_quality_type=(
            pl.col("allocation_qty_quality_type").cast(pl.String)
            if has_quality_type
            else pl.lit(None).cast(pl.String)
        ),
    )


def _select_sttm_allocation_quantities(
    int658: LazyFrame,
    int689: LazyFrame,
    facilities: LazyFrame,
    zones: LazyFrame,
) -> LazyFrame:
    combined = pl.concat(
        [
            _allocation_rows(
                int658,
                table_name=SOURCE_TABLES[0],
                report_id="INT658",
                allocation_version="latest",
                has_quality_type=False,
            ),
            _allocation_rows(
                int689,
                table_name=SOURCE_TABLES[1],
                report_id="INT689",
                allocation_version="ex_post",
                has_quality_type=True,
            ),
        ],
        how="diagonal_relaxed",
    ).with_columns(
        date_key=get_surrogate_key(["gas_date"]),
        surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES),
    )
    return with_facility_zone_keys(combined, facilities, zones).select(list(SCHEMA))


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver STTM allocation quantity fact.",
    ins={
        "int658": AssetIn(key=INT658_KEY),
        "int689": AssetIn(key=INT689_KEY),
        "facilities": AssetIn(key=FACILITIES_KEY),
        "zones": AssetIn(key=ZONES_KEY),
    },
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "parquet"},
    retry_policy=RetryPolicy(
        max_retries=3,
        delay=60,
        backoff=Backoff.EXPONENTIAL,
        jitter=Jitter.PLUS_MINUS,
    ),
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_fact_sttm_allocation_quantity(
    int658: LazyFrame,
    int689: LazyFrame,
    facilities: LazyFrame,
    zones: LazyFrame,
) -> MaterializeResult[LazyFrame]:
    """Materialize the silver STTM allocation quantity fact asset."""
    return _materialize_result(
        _select_sttm_allocation_quantities(int658, int689, facilities, zones)
    )


@asset_check(
    asset=silver_gas_fact_sttm_allocation_quantity,
    name="check_required_fields",
    description="Check required STTM allocation quantity fields are not null.",
)
def silver_gas_fact_sttm_allocation_quantity_required_fields(
    input_df: LazyFrame,
) -> AssetCheckResult:
    """Validate required fields for the silver STTM allocation quantity fact."""
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_fact_sttm_allocation_quantity_duplicate_row_check = (
    duplicate_row_check_factory(
        assets_definition=silver_gas_fact_sttm_allocation_quantity,
        check_name="check_for_duplicate_rows",
        primary_key="surrogate_key",
        description="Check that surrogate_key is unique.",
    )
)
silver_gas_fact_sttm_allocation_quantity_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_fact_sttm_allocation_quantity,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)
silver_gas_fact_sttm_allocation_quantity_schema_drift_check = (
    schema_drift_check_factory(
        schema=SCHEMA,
        assets_definition=silver_gas_fact_sttm_allocation_quantity,
        check_name="check_schema_drift",
        description="Check for schema drift against the declared asset schema.",
    )
)


@definitions
def defs() -> Definitions:
    """Return Dagster definitions for the silver STTM allocation quantity fact."""
    return Definitions(
        assets=[silver_gas_fact_sttm_allocation_quantity],
        asset_checks=[
            silver_gas_fact_sttm_allocation_quantity_duplicate_row_check,
            silver_gas_fact_sttm_allocation_quantity_schema_check,
            silver_gas_fact_sttm_allocation_quantity_schema_drift_check,
            silver_gas_fact_sttm_allocation_quantity_required_fields,
        ],
        sensors=[
            AutomationConditionSensorDefinition(
                name="silver_gas_fact_sttm_allocation_quantity_sensor",
                target=[silver_gas_fact_sttm_allocation_quantity.key],
                default_status=DEFAULT_SENSOR_STATUS,
                run_tags={"ecs/cpu": "512", "ecs/memory": "4096"},
            )
        ],
    )
