import polars as pl
from dagster import (
    AssetCheckResult,
    AssetIn,
    AssetKey,
    AutomationCondition,
    Definitions,
    MaterializeResult,
    TableColumnDep,
    TableColumnLineage,
    asset,
    asset_check,
    definitions,
)
from polars import LazyFrame

from aemo_etl.configs import AEMO_BUCKET
from aemo_etl.factories.checks import (
    duplicate_row_check_factory,
    schema_drift_check_factory,
    schema_matches_check_factor,
)
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

DOMAIN = "gas_model"
TABLE_NAME = "silver_gas_dim_facility"
KEY_PREFIX = ["silver", DOMAIN]
GROUP_NAME = "gas_model"
GRAIN = "one current row per source-qualified gas facility"
SURROGATE_KEY_SOURCES = ["source_system", "source_facility_id"]
SOURCE_TABLES = ["silver.gbb.silver_gasbb_facilities"]
SOURCE_SYSTEM = "GBB"
GBB_FACILITIES_KEY = AssetKey(["silver", "gbb", "silver_gasbb_facilities"])
PARTICIPANTS_KEY = AssetKey(["silver", "gas_model", "silver_gas_dim_participant"])

COLUMN_LINEAGE = TableColumnLineage(
    deps_by_column={
        "surrogate_key": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="FacilityId")
        ],
        "participant_key": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="OperatorId"),
            TableColumnDep(asset_key=PARTICIPANTS_KEY, column_name="surrogate_key"),
        ],
        "source_facility_id": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="FacilityId")
        ],
        "facility_name": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="FacilityName")
        ],
        "facility_short_name": [
            TableColumnDep(
                asset_key=GBB_FACILITIES_KEY, column_name="FacilityShortName"
            )
        ],
        "facility_type": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="FacilityType")
        ],
        "facility_type_description": [
            TableColumnDep(
                asset_key=GBB_FACILITIES_KEY, column_name="FacilityTypeDescription"
            )
        ],
        "operating_state": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="OperatingState")
        ],
        "operating_state_date": [
            TableColumnDep(
                asset_key=GBB_FACILITIES_KEY, column_name="OperatingStateDate"
            )
        ],
        "operator_name": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="OperatorName")
        ],
        "source_operator_id": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="OperatorId")
        ],
        "operator_change_date": [
            TableColumnDep(
                asset_key=GBB_FACILITIES_KEY, column_name="OperatorChangeDate"
            )
        ],
        "source_last_updated": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="LastUpdated")
        ],
        "source_last_updated_timestamp": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="LastUpdated")
        ],
        "source_surrogate_key": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="surrogate_key")
        ],
        "source_file": [
            TableColumnDep(asset_key=GBB_FACILITIES_KEY, column_name="source_file")
        ],
        "ingested_timestamp": [
            TableColumnDep(
                asset_key=GBB_FACILITIES_KEY, column_name="ingested_timestamp"
            )
        ],
    }
)

SCHEMA = {
    "surrogate_key": pl.String,
    "participant_key": pl.String,
    "source_system": pl.String,
    "source_tables": pl.List(pl.String),
    "source_facility_id": pl.String,
    "facility_name": pl.String,
    "facility_short_name": pl.String,
    "facility_type": pl.String,
    "facility_type_description": pl.String,
    "operating_state": pl.String,
    "operating_state_date": pl.Date,
    "operator_name": pl.String,
    "source_operator_id": pl.String,
    "operator_change_date": pl.Date,
    "source_last_updated": pl.String,
    "source_last_updated_timestamp": pl.Datetime("us"),
    "source_surrogate_key": pl.String,
    "source_file": pl.String,
    "ingested_timestamp": pl.Datetime("us", time_zone="UTC"),
}

DESCRIPTIONS = {
    "surrogate_key": "Silver dimension primary key generated by surrogate_key_sources.",
    "participant_key": "Operator participant surrogate key when resolvable.",
    "source_system": "Source system identifier.",
    "source_tables": "Silver source tables used to construct the gas model row.",
    "source_facility_id": "Source-system facility identifier.",
    "facility_name": "Facility name.",
    "facility_short_name": "Facility short name.",
    "facility_type": "Facility type.",
    "facility_type_description": "Facility type description.",
    "operating_state": "Facility operating state.",
    "operating_state_date": "Parsed date the current operating state was set.",
    "operator_name": "Facility operator name.",
    "source_operator_id": "Source-system operator company identifier.",
    "operator_change_date": "Parsed date the operator changed.",
    "source_last_updated": "Raw source update value.",
    "source_last_updated_timestamp": "Parsed source update timestamp.",
    "source_surrogate_key": "Source row surrogate key for lineage.",
    "source_file": "Archived source file for the source row.",
    "ingested_timestamp": "Timestamp when the source row was ingested.",
}

REQUIRED_COLUMNS = [
    "surrogate_key",
    "source_system",
    "source_facility_id",
    "facility_name",
]


def _parse_datetime(column: str) -> pl.Expr:
    source = pl.col(column).cast(pl.String)
    return pl.coalesce(
        source.str.strptime(pl.Datetime("us"), "%d %b %Y %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d %H:%M:%S", strict=False),
        source.str.strptime(pl.Datetime("us"), "%Y/%m/%d", strict=False),
    )


def _parse_date(column: str) -> pl.Expr:
    return _parse_datetime(column).dt.date()


def _select_current_facilities(
    gbb_facilities: LazyFrame, participants: LazyFrame
) -> LazyFrame:
    participant_keys = participants.filter(
        pl.col("participant_identity_source") == "company_id"
    ).select(
        participant_key=pl.col("surrogate_key"),
        source_operator_id=pl.col("participant_identity_value"),
    )
    return (
        gbb_facilities.with_columns(
            source_system=pl.lit(SOURCE_SYSTEM),
            source_tables=pl.lit(SOURCE_TABLES).cast(pl.List(pl.String)),
            source_facility_id=pl.col("FacilityId").cast(pl.String),
            facility_name=pl.col("FacilityName").cast(pl.String),
            facility_short_name=pl.col("FacilityShortName").cast(pl.String),
            facility_type=pl.col("FacilityType").cast(pl.String),
            facility_type_description=pl.col("FacilityTypeDescription").cast(pl.String),
            operating_state=pl.col("OperatingState").cast(pl.String),
            operating_state_date=_parse_date("OperatingStateDate"),
            operator_name=pl.col("OperatorName").cast(pl.String),
            source_operator_id=pl.col("OperatorId").cast(pl.String),
            operator_change_date=_parse_date("OperatorChangeDate"),
            source_last_updated=pl.col("LastUpdated").cast(pl.String),
            source_last_updated_timestamp=_parse_datetime("LastUpdated"),
            source_surrogate_key=pl.col("surrogate_key").cast(pl.String),
        )
        .with_columns(surrogate_key=get_surrogate_key(SURROGATE_KEY_SOURCES))
        .sort(
            [
                "source_system",
                "source_facility_id",
                "source_last_updated_timestamp",
                "operating_state_date",
                "ingested_timestamp",
            ],
            descending=[False, False, True, True, True],
            nulls_last=True,
        )
        .unique(subset=SURROGATE_KEY_SOURCES, keep="first", maintain_order=True)
        .join(participant_keys, on="source_operator_id", how="left")
        .select(list(SCHEMA))
    )


def _materialize_result(value: LazyFrame) -> MaterializeResult[LazyFrame]:
    return MaterializeResult(
        value=value,
        metadata={"dagster/column_lineage": COLUMN_LINEAGE},
    )


@asset(
    key_prefix=KEY_PREFIX,
    group_name=GROUP_NAME,
    description="Silver current-snapshot gas facility dimension.",
    ins={
        "gbb_facilities": AssetIn(key=GBB_FACILITIES_KEY),
        "participants": AssetIn(key=PARTICIPANTS_KEY),
    },
    io_manager_key="aemo_parquet_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"silver.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "grain": GRAIN,
        "surrogate_key_sources": SURROGATE_KEY_SOURCES,
        "source_tables": SOURCE_TABLES,
    },
    kinds={"table", "parquet"},
    automation_condition=AutomationCondition.any_deps_updated()
    & ~AutomationCondition.in_progress()
    & ~AutomationCondition.any_deps_missing(),
)
def silver_gas_dim_facility(
    gbb_facilities: LazyFrame, participants: LazyFrame
) -> MaterializeResult[LazyFrame]:
    return _materialize_result(_select_current_facilities(gbb_facilities, participants))


@asset_check(
    asset=silver_gas_dim_facility,
    name="check_required_fields",
    description="Check required dimension fields are not null.",
)
def silver_gas_dim_facility_required_fields(input_df: LazyFrame) -> AssetCheckResult:
    null_counts = (
        input_df.select(pl.col(column).is_null().sum() for column in REQUIRED_COLUMNS)
        .collect()
        .to_dicts()[0]
    )
    return AssetCheckResult(
        passed=all(count == 0 for count in null_counts.values()),
        check_name="check_required_fields",
        metadata={"null_counts": null_counts},
    )


silver_gas_dim_facility_duplicate_row_check = duplicate_row_check_factory(
    assets_definition=silver_gas_dim_facility,
    check_name="check_for_duplicate_rows",
    primary_key="surrogate_key",
    description="Check that surrogate_key is unique.",
)

silver_gas_dim_facility_schema_check = schema_matches_check_factor(
    schema=SCHEMA,
    assets_definition=silver_gas_dim_facility,
    check_name="check_schema_matches",
    description="Check observed schema matches target schema.",
)

silver_gas_dim_facility_schema_drift_check = schema_drift_check_factory(
    schema=SCHEMA,
    assets_definition=silver_gas_dim_facility,
    check_name="check_schema_drift",
    description="Check for schema drift against the declared asset schema.",
)


@definitions
def defs() -> Definitions:
    return Definitions(
        assets=[silver_gas_dim_facility],
        asset_checks=[
            silver_gas_dim_facility_duplicate_row_check,
            silver_gas_dim_facility_schema_check,
            silver_gas_dim_facility_schema_drift_check,
            silver_gas_dim_facility_required_fields,
        ],
    )
