#!/usr/bin/env bash

branch_name=$(git branch --show-current)

CONTAINER_IDENTIFIER=${branch_name/\//-}

CONTAINER_NAME=emdl-"$CONTAINER_IDENTIFIER"

NETWORK=podman

export CONTAINER_NAME CONTAINER_IDENTIFIER NETWORK
