#!/usr/bin/env bash

. "./scripts/@common"

mkdir -p "$HOME"/.cache/localstack/volume

podman run \
	--userns=host \
	--network="$NETWORK" \
	--interactive \
	--tty \
	--detach \
	--replace \
	--detach-keys "ctrl-a,ctrl-e" \
	--publish 3000:3000 \
	--volume "$SSH_AUTH_SOCK":/ssh-agent \
	--volume "$XDG_RUNTIME_DIR"/podman/podman.sock:/run/podman/podman.sock \
	--volume "$HOME"/.config/opencode/opencode.json:/root/.config/opencode/opencode.json \
	--mount type=bind,source="$WORKTREE_DIR",destination=/worktree,relabel=shared \
	--env IN_CONTAINER=true \
	--env HOST_XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
	--env HOST_HOME="$HOME" \
	--env LOCALSTACK_AUTH_TOKEN="$LOCALSTACK_AUTH_TOKEN" \
	--env LOCALSTACK_ENDPOINT="http://$LOCALSTACK_NAME:4566" \
	--env ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
	--env SSH_AUTH_SOCK=/ssh-agent \
	--env DOCKER_HOST=unix:///run/podman/podman.sock \
	--env TMUX="$TMUX" \
	--name "$CONTAINER_NAME" \
	localhost/emdl-dev:latest \
	bash -l
