#!/usr/bin/env bash

. "./scripts/@common"

if "$IN_CONTAINER"; then
	command=(podman --remote)
else
	command=(podman)
fi

"${command[@]}" run \
	--rm \
	--interactive \
	--tty \
	--network="$NETWORK" \
	--env LOCALSTACK_AUTH_TOKEN="${LOCALSTACK_AUTH_TOKEN:?}" \
	--env DOCKER_SOCK=/run/podman/podman.sock \
	--env DOCKER_HOST=unix://run/podman/podman.sock \
	--env CUSTOM_SSL_CERT_PATH=/home/cmamon/.local/lib/localstack/custom/server.test.pem \
	--volume "${HOST_XDG_RUNTIME_DIR:-$XDG_RUNTIME_DIR}"/podman/podman.sock:/run/podman/podman.sock \
	--volume "${HOST_HOME:-$HOME}"/.cache/localstack/volume:/var/lib/localstack \
	--name "$LOCALSTACK_NAME" \
	localstack/localstack-pro
