#!/usr/bin/env python3
"""Drain GitHub issues through Codex implementation and triage loops."""

from __future__ import annotations

import argparse
import json
import re
import shlex
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


AI_TRIAGE_DISCLAIMER = "> *This was generated by AI during triage.*"

READY_LABEL = "ready-for-agent"
NEEDS_TRIAGE_LABEL = "needs-triage"
NEEDS_INFO_LABEL = "needs-info"
READY_FOR_HUMAN_LABEL = "ready-for-human"
WONTFIX_LABEL = "wontfix"

AGENT_RUNNING_LABEL = "agent-running"
AGENT_FAILED_LABEL = "agent-failed"
AGENT_PR_OPEN_LABEL = "agent-pr-open"

TRIAGE_STATE_LABELS = frozenset(
    {
        NEEDS_TRIAGE_LABEL,
        NEEDS_INFO_LABEL,
        READY_LABEL,
        READY_FOR_HUMAN_LABEL,
        WONTFIX_LABEL,
    }
)
IMPLEMENTATION_STOP_LABELS = frozenset(
    {
        NEEDS_TRIAGE_LABEL,
        NEEDS_INFO_LABEL,
        READY_FOR_HUMAN_LABEL,
        WONTFIX_LABEL,
        AGENT_RUNNING_LABEL,
        AGENT_FAILED_LABEL,
        AGENT_PR_OPEN_LABEL,
    }
)
TRIAGE_STOP_LABELS = frozenset(
    {
        READY_LABEL,
        READY_FOR_HUMAN_LABEL,
        WONTFIX_LABEL,
        AGENT_RUNNING_LABEL,
        AGENT_FAILED_LABEL,
        AGENT_PR_OPEN_LABEL,
    }
)

REQUIRED_ISSUE_SECTIONS = ("What to build", "Acceptance criteria", "Blocked by")
AEMO_ETL_PREFIX = "backend-services/dagster-user/aemo-etl/"
ENVIRONMENT_FAILURE_PATTERNS = (
    "podman: command not found",
    "docker: command not found",
    "cannot connect to the docker daemon",
    "could not connect to podman",
    "podman.sock",
    "permission denied while trying to connect",
)


@dataclass(frozen=True)
class LabelSpec:
    name: str
    color: str
    description: str


LABEL_SPECS = (
    LabelSpec("bug", "D73A4A", "Something is broken."),
    LabelSpec("enhancement", "A2EEEF", "New feature or improvement."),
    LabelSpec(NEEDS_TRIAGE_LABEL, "EDEDED", "Maintainer needs to evaluate."),
    LabelSpec(NEEDS_INFO_LABEL, "FBCA04", "Waiting on reporter information."),
    LabelSpec(READY_LABEL, "0E8A16", "Fully specified and ready for an AFK agent."),
    LabelSpec(READY_FOR_HUMAN_LABEL, "5319E7", "Needs human implementation."),
    LabelSpec(WONTFIX_LABEL, "FFFFFF", "Will not be actioned."),
    LabelSpec(AGENT_RUNNING_LABEL, "1D76DB", "Agent issue loop is running."),
    LabelSpec(AGENT_FAILED_LABEL, "B60205", "Agent issue loop failed."),
    LabelSpec(AGENT_PR_OPEN_LABEL, "0E8A16", "Agent issue loop opened a PR."),
)


class RalphError(RuntimeError):
    """Base error for user-facing loop failures."""


class CommandFailure(RalphError):
    """A subprocess command failed."""

    def __init__(
        self,
        command: list[str],
        cwd: Path,
        returncode: int,
        stdout: str,
        stderr: str,
        log_path: Path | None,
    ) -> None:
        super().__init__(f"Command failed ({returncode}): {format_command(command)}")
        self.command = command
        self.cwd = cwd
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr
        self.log_path = log_path


class IssueFailure(RalphError):
    """An issue-specific failure that should not stop the whole drain."""

    def __init__(self, message: str, log_path: Path | None = None) -> None:
        super().__init__(message)
        self.log_path = log_path


class EnvironmentFailure(IssueFailure):
    """A local environment failure that should stop the drain."""


@dataclass(frozen=True)
class CompletedCommand:
    stdout: str
    stderr: str


@dataclass(frozen=True)
class Issue:
    number: int
    title: str
    body: str
    labels: frozenset[str]
    created_at: datetime
    updated_at: datetime
    url: str
    comments: int
    author: str | None

    @classmethod
    def from_gh(cls, payload: dict[str, Any]) -> "Issue":
        return cls(
            number=int(payload["number"]),
            title=str(payload.get("title") or ""),
            body=str(payload.get("body") or ""),
            labels=frozenset(label["name"] for label in payload.get("labels", [])),
            created_at=parse_github_datetime(str(payload.get("createdAt") or "")),
            updated_at=parse_github_datetime(str(payload.get("updatedAt") or "")),
            url=str(payload.get("url") or ""),
            comments=parse_comment_count(payload.get("comments")),
            author=extract_login(payload.get("author")),
        )


@dataclass(frozen=True)
class QACommand:
    args: tuple[str, ...]
    cwd: Path
    name: str


@dataclass(frozen=True)
class QAResult:
    command: QACommand
    log_path: Path | None


@dataclass(frozen=True)
class LoopConfig:
    repo_root: Path
    repo: str
    base: str
    issue: int | None
    drain: bool
    max_issues: int
    dry_run: bool
    bootstrap_labels: bool
    issue_limit: int
    log_root: Path
    worktree_container: Path


def emit(message: str, *, err: bool = False) -> None:
    stream = sys.stderr if err else sys.stdout
    stream.write(f"{message}\n")
    stream.flush()


def format_command(args: list[str] | tuple[str, ...]) -> str:
    return " ".join(shlex.quote(arg) for arg in args)


def parse_github_datetime(value: str) -> datetime:
    if value == "":
        return datetime.min.replace(tzinfo=UTC)
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def extract_login(value: Any) -> str | None:
    if isinstance(value, dict) and "login" in value:
        return str(value["login"])
    return None


def parse_comment_count(value: Any) -> int:
    if isinstance(value, list):
        return len(value)
    if value is None:
        return 0
    return int(value)


def parse_repo_slug(remote_url: str) -> str:
    remote_url = remote_url.strip()
    patterns = (
        r"^git@github\.com:(?P<slug>[^/]+/[^/]+?)(?:\.git)?$",
        r"^https://github\.com/(?P<slug>[^/]+/[^/]+?)(?:\.git)?/?$",
        r"^ssh://git@github\.com/(?P<slug>[^/]+/[^/]+?)(?:\.git)?/?$",
    )
    for pattern in patterns:
        match = re.match(pattern, remote_url)
        if match is not None:
            return match.group("slug")
    raise ValueError(f"Cannot derive GitHub repo from remote URL: {remote_url}")


def slugify(value: str, *, max_length: int = 56) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if slug == "":
        slug = "issue"
    if len(slug) <= max_length:
        return slug
    return slug[:max_length].rstrip("-")


def section_body(markdown: str, heading: str) -> str | None:
    pattern = re.compile(
        rf"(?ims)^#{{1,6}}\s+{re.escape(heading)}\s*$\n"
        rf"(?P<body>.*?)(?=^#{{1,6}}\s+\S|\Z)"
    )
    match = pattern.search(markdown)
    if match is None:
        return None
    return match.group("body").strip()


def missing_required_sections(markdown: str) -> list[str]:
    missing: list[str] = []
    for heading in REQUIRED_ISSUE_SECTIONS:
        body = section_body(markdown, heading)
        if body is None or body.strip() == "":
            missing.append(heading)
    return missing


def parse_blockers(markdown: str) -> list[int]:
    blocked_by = section_body(markdown, "Blocked by")
    if blocked_by is None:
        return []
    blockers = sorted({int(value) for value in re.findall(r"(?:#|/issues/)(\d+)", blocked_by)})
    return blockers


def issue_has_any_label(issue: Issue, labels: frozenset[str]) -> bool:
    return len(issue.labels.intersection(labels)) > 0


def is_ready_candidate(issue: Issue) -> bool:
    if READY_LABEL not in issue.labels:
        return False
    return not issue_has_any_label(issue, IMPLEMENTATION_STOP_LABELS)


def is_basic_triage_candidate(issue: Issue) -> bool:
    if issue_has_any_label(issue, TRIAGE_STOP_LABELS):
        return False
    state_labels = issue.labels.intersection(TRIAGE_STATE_LABELS)
    return not state_labels or NEEDS_TRIAGE_LABEL in state_labels


def root_prek_needed(changed_file: str) -> bool:
    return (
        changed_file in {"AGENTS.md", "README.md", ".pre-commit-config.yaml"}
        or changed_file.startswith("docs/")
        or changed_file.startswith("infrastructure/")
        or (
            changed_file.startswith("backend-services/")
            and not changed_file.startswith(AEMO_ETL_PREFIX)
        )
    )


def select_qa_commands(changed_files: list[str], repo_root: Path) -> list[QACommand]:
    commands: list[QACommand] = []
    has_aemo_etl_change = any(path.startswith(AEMO_ETL_PREFIX) for path in changed_files)
    if has_aemo_etl_change:
        aemo_root = repo_root / AEMO_ETL_PREFIX
        commands.extend(
            [
                QACommand(("make", "unit-test"), aemo_root, "aemo-etl Unit test"),
                QACommand(("make", "component-test"), aemo_root, "aemo-etl Component test"),
                QACommand(("make", "integration-test"), aemo_root, "aemo-etl Integration test"),
                QACommand(("make", "run-prek"), aemo_root, "aemo-etl Commit check"),
            ]
        )

    if any(root_prek_needed(path) for path in changed_files):
        commands.append(QACommand(("prek", "run", "-a"), repo_root, "root Commit check"))

    if any(path.startswith(("scripts/", "tests/")) for path in changed_files):
        commands.append(
            QACommand(
                ("python3", "-m", "unittest", "discover", "-s", "tests"),
                repo_root,
                "Ralph unit tests",
            )
        )

    deduped: list[QACommand] = []
    seen: set[tuple[tuple[str, ...], Path]] = set()
    for command in commands:
        key = (command.args, command.cwd)
        if key not in seen:
            deduped.append(command)
            seen.add(key)
    return deduped


def parse_git_status_paths(status_output: str) -> list[str]:
    paths: list[str] = []
    for line in status_output.splitlines():
        if len(line) < 4:
            continue
        path = line[3:].strip()
        if " -> " in path:
            path = path.rsplit(" -> ", 1)[1]
        paths.append(path.strip('"'))
    return sorted(set(paths))


def looks_like_environment_failure(error: CommandFailure) -> bool:
    output = f"{error.stdout}\n{error.stderr}".lower()
    return any(pattern in output for pattern in ENVIRONMENT_FAILURE_PATTERNS)


def codex_exec_command(cwd: Path) -> list[str]:
    return [
        "codex",
        "exec",
        "--cd",
        str(cwd),
        "--sandbox",
        "workspace-write",
        "--full-auto",
        "--json",
        "-",
    ]


class CommandRunner:
    def __init__(self, *, dry_run: bool) -> None:
        self.dry_run = dry_run

    def run(
        self,
        args: list[str],
        *,
        cwd: Path,
        input_text: str | None = None,
        log_path: Path | None = None,
        execute_in_dry_run: bool = True,
    ) -> CompletedCommand:
        if self.dry_run and not execute_in_dry_run:
            emit(f"DRY RUN: {format_command(args)}")
            return CompletedCommand(stdout="", stderr="")

        if log_path is not None:
            log_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            result = subprocess.run(
                args,
                cwd=cwd,
                input=input_text,
                text=True,
                capture_output=True,
                check=True,
            )
        except subprocess.CalledProcessError as error:
            stdout = error.stdout or ""
            stderr = error.stderr or ""
            if log_path is not None:
                write_command_log(log_path, args, cwd, stdout, stderr, error.returncode)
            raise CommandFailure(args, cwd, error.returncode, stdout, stderr, log_path) from error

        if log_path is not None:
            write_command_log(log_path, args, cwd, result.stdout, result.stderr, result.returncode)
        return CompletedCommand(stdout=result.stdout, stderr=result.stderr)


def write_command_log(
    path: Path,
    args: list[str],
    cwd: Path,
    stdout: str,
    stderr: str,
    returncode: int,
) -> None:
    path.write_text(
        "\n".join(
            [
                f"$ {format_command(args)}",
                f"cwd: {cwd}",
                f"exit: {returncode}",
                "",
                "STDOUT:",
                stdout,
                "",
                "STDERR:",
                stderr,
                "",
            ]
        ),
        encoding="utf-8",
    )


class GitHubClient:
    def __init__(self, *, repo: str, repo_root: Path, runner: CommandRunner) -> None:
        self.repo = repo
        self.repo_root = repo_root
        self.runner = runner

    def auth_status(self) -> None:
        self.runner.run(["gh", "auth", "status"], cwd=self.repo_root)

    def list_labels(self) -> set[str]:
        payload = self._json(
            ["gh", "label", "list", "-R", self.repo, "--limit", "200", "--json", "name"]
        )
        return {str(item["name"]) for item in payload}

    def bootstrap_labels(self) -> None:
        for label in LABEL_SPECS:
            self.runner.run(
                [
                    "gh",
                    "label",
                    "create",
                    label.name,
                    "-R",
                    self.repo,
                    "--color",
                    label.color,
                    "--description",
                    label.description,
                    "--force",
                ],
                cwd=self.repo_root,
                execute_in_dry_run=False,
            )

    def list_open_issues(self, *, limit: int) -> list[Issue]:
        payload = self._json(
            [
                "gh",
                "issue",
                "list",
                "-R",
                self.repo,
                "--state",
                "open",
                "--limit",
                str(limit),
                "--json",
                "number,title,body,labels,createdAt,updatedAt,url,comments,author",
            ]
        )
        issues = [Issue.from_gh(item) for item in payload]
        return sorted(issues, key=lambda issue: (issue.created_at, issue.number))

    def view_issue(self, number: int) -> Issue:
        payload = self._json(
            [
                "gh",
                "issue",
                "view",
                str(number),
                "-R",
                self.repo,
                "--json",
                "number,title,body,labels,createdAt,updatedAt,url,comments,author",
            ]
        )
        return Issue.from_gh(payload)

    def issue_state(self, number: int) -> str:
        payload = self._json(
            [
                "gh",
                "issue",
                "view",
                str(number),
                "-R",
                self.repo,
                "--json",
                "state",
            ]
        )
        return str(payload["state"]).upper()

    def issue_comments(self, number: int) -> list[dict[str, Any]]:
        payload = self._json(
            [
                "gh",
                "issue",
                "view",
                str(number),
                "-R",
                self.repo,
                "--comments",
                "--json",
                "comments",
            ]
        )
        return list(payload.get("comments", []))

    def current_user(self) -> str:
        result = self.runner.run(["gh", "api", "user", "--jq", ".login"], cwd=self.repo_root)
        return result.stdout.strip()

    def edit_issue_labels(
        self,
        number: int,
        *,
        add: list[str] | None = None,
        remove: list[str] | None = None,
    ) -> None:
        add = add or []
        remove = remove or []
        if not add and not remove:
            return
        args = ["gh", "issue", "edit", str(number), "-R", self.repo]
        for label in add:
            args.extend(["--add-label", label])
        for label in remove:
            args.extend(["--remove-label", label])
        self.runner.run(args, cwd=self.repo_root, execute_in_dry_run=False)

    def comment_issue(self, number: int, body: str, *, run_dir: Path) -> None:
        comment_path = run_dir / f"issue-{number}-comment.md"
        if not self.runner.dry_run:
            comment_path.write_text(body, encoding="utf-8")
        self.runner.run(
            [
                "gh",
                "issue",
                "comment",
                str(number),
                "-R",
                self.repo,
                "--body-file",
                str(comment_path),
            ],
            cwd=self.repo_root,
            execute_in_dry_run=False,
        )

    def create_draft_pr(
        self,
        *,
        title: str,
        body: str,
        branch: str,
        base: str,
        run_dir: Path,
    ) -> str:
        body_path = run_dir / "pull-request-body.md"
        if not self.runner.dry_run:
            body_path.write_text(body, encoding="utf-8")
        result = self.runner.run(
            [
                "gh",
                "pr",
                "create",
                "-R",
                self.repo,
                "--base",
                base,
                "--head",
                branch,
                "--title",
                title,
                "--body-file",
                str(body_path),
                "--draft",
            ],
            cwd=self.repo_root,
            log_path=run_dir / "gh-pr-create.log",
            execute_in_dry_run=False,
        )
        return result.stdout.strip()

    def _json(self, args: list[str]) -> Any:
        result = self.runner.run(args, cwd=self.repo_root)
        return json.loads(result.stdout)


class GitClient:
    def __init__(self, *, repo_root: Path, runner: CommandRunner) -> None:
        self.repo_root = repo_root
        self.runner = runner

    def fetch_base(self, base: str, *, run_dir: Path) -> None:
        self.runner.run(
            ["git", "fetch", "origin", base],
            cwd=self.repo_root,
            log_path=run_dir / "git-fetch.log",
            execute_in_dry_run=False,
        )

    def add_worktree(self, *, branch: str, base: str, path: Path, run_dir: Path) -> None:
        if path.exists():
            raise IssueFailure(f"Worktree already exists: {path}")
        self.runner.run(
            ["git", "worktree", "add", "-b", branch, str(path), f"origin/{base}"],
            cwd=self.repo_root,
            log_path=run_dir / "git-worktree-add.log",
            execute_in_dry_run=False,
        )

    def changed_files(self, *, cwd: Path) -> list[str]:
        result = self.runner.run(["git", "status", "--porcelain"], cwd=cwd)
        return parse_git_status_paths(result.stdout)

    def has_uncommitted_changes(self, *, cwd: Path) -> bool:
        result = self.runner.run(["git", "status", "--porcelain"], cwd=cwd)
        return result.stdout.strip() != ""

    def commit_and_push(
        self,
        *,
        cwd: Path,
        branch: str,
        message: str,
        run_dir: Path,
    ) -> None:
        self.runner.run(
            ["git", "add", "-A"],
            cwd=cwd,
            log_path=run_dir / "git-add.log",
            execute_in_dry_run=False,
        )
        self.runner.run(
            ["git", "commit", "-m", message],
            cwd=cwd,
            log_path=run_dir / "git-commit.log",
            execute_in_dry_run=False,
        )
        self.runner.run(
            ["git", "push", "-u", "origin", branch],
            cwd=cwd,
            log_path=run_dir / "git-push.log",
            execute_in_dry_run=False,
        )

    def remove_worktree(self, path: Path, *, run_dir: Path) -> None:
        self.runner.run(
            ["git", "worktree", "remove", str(path)],
            cwd=self.repo_root,
            log_path=run_dir / "git-worktree-remove.log",
            execute_in_dry_run=False,
        )


class RalphLoop:
    def __init__(self, config: LoopConfig, runner: CommandRunner) -> None:
        self.config = config
        self.runner = runner
        self.github = GitHubClient(repo=config.repo, repo_root=config.repo_root, runner=runner)
        self.git = GitClient(repo_root=config.repo_root, runner=runner)
        self.triaged_this_run: set[int] = set()

    def run(self) -> None:
        self._validate_tools()

        if self.config.bootstrap_labels:
            self.github.auth_status()
            self.github.bootstrap_labels()
            message = (
                "DRY RUN: would bootstrap issue labels."
                if self.config.dry_run
                else "Bootstrapped issue labels."
            )
            emit(message)
            if self.config.dry_run or (not self.config.drain and self.config.issue is None):
                return

        self.github.auth_status()
        self._validate_labels()

        implemented = 0
        while True:
            if self.config.max_issues > 0 and implemented >= self.config.max_issues:
                emit(f"Reached --max-issues {self.config.max_issues}.")
                return

            ready_issue = self._next_ready_issue()
            if ready_issue is not None:
                if self.config.dry_run:
                    emit(f"DRY RUN: would implement #{ready_issue.number}: {ready_issue.title}")
                    return
                self._handle_implementation(ready_issue)
                implemented += 1
                if not self.config.drain:
                    return
                continue

            if not self.config.drain:
                emit("No ready issue found.")
                return

            triage_issue = self._next_triage_issue()
            if triage_issue is None:
                emit("No unblocked ready or triage-actionable issues remain.")
                return
            if self.config.dry_run:
                emit(f"DRY RUN: would triage #{triage_issue.number}: {triage_issue.title}")
                return
            self._run_triage(triage_issue)
            self.triaged_this_run.add(triage_issue.number)

    def _validate_tools(self) -> None:
        missing = [tool for tool in ("git", "gh", "codex") if shutil.which(tool) is None]
        if missing:
            raise RalphError(f"Missing required command(s): {', '.join(missing)}")

    def _validate_labels(self) -> None:
        actual = self.github.list_labels()
        expected = {label.name for label in LABEL_SPECS}
        missing = sorted(expected - actual)
        if missing:
            labels = ", ".join(missing)
            raise RalphError(f"Missing labels: {labels}. Run with --bootstrap-labels first.")

    def _next_ready_issue(self) -> Issue | None:
        issues = self._issue_pool()
        for issue in issues:
            if not is_ready_candidate(issue):
                continue
            if self._has_open_blockers(issue):
                continue
            return issue
        return None

    def _next_triage_issue(self) -> Issue | None:
        current_user: str | None = None
        for issue in self.github.list_open_issues(limit=self.config.issue_limit):
            if issue.number in self.triaged_this_run:
                continue
            if self._has_open_blockers(issue):
                continue
            if is_basic_triage_candidate(issue):
                return issue
            if NEEDS_INFO_LABEL in issue.labels:
                if current_user is None:
                    current_user = self.github.current_user()
                if self._needs_info_has_reporter_activity(issue, current_user=current_user):
                    return issue
        return None

    def _issue_pool(self) -> list[Issue]:
        if self.config.issue is not None:
            return [self.github.view_issue(self.config.issue)]
        return self.github.list_open_issues(limit=self.config.issue_limit)

    def _has_open_blockers(self, issue: Issue) -> bool:
        for blocker in parse_blockers(issue.body):
            if self.github.issue_state(blocker) != "CLOSED":
                return True
        return False

    def _needs_info_has_reporter_activity(self, issue: Issue, *, current_user: str) -> bool:
        if issue.author is None:
            return False

        comments = self.github.issue_comments(issue.number)
        latest_triage_note = datetime.min.replace(tzinfo=UTC)
        for comment in comments:
            author = extract_login(comment.get("author"))
            body = str(comment.get("body") or "")
            if author == current_user and body.startswith(AI_TRIAGE_DISCLAIMER):
                created_at = parse_github_datetime(str(comment.get("createdAt") or ""))
                latest_triage_note = max(latest_triage_note, created_at)

        for comment in comments:
            author = extract_login(comment.get("author"))
            if author != issue.author:
                continue
            created_at = parse_github_datetime(str(comment.get("createdAt") or ""))
            if created_at > latest_triage_note:
                return True
        return False

    def _handle_implementation(self, issue: Issue) -> None:
        run_dir = self._run_dir(issue)
        run_dir.mkdir(parents=True, exist_ok=True)

        claimed = False
        worktree_path: Path | None = None
        try:
            self._validate_issue_contract(issue)
            self.github.edit_issue_labels(
                issue.number,
                add=[AGENT_RUNNING_LABEL],
                remove=[READY_LABEL, AGENT_FAILED_LABEL],
            )
            claimed = True
            branch, worktree_path = self._branch_and_worktree(issue)
            self.git.fetch_base(self.config.base, run_dir=run_dir)
            self.git.add_worktree(
                branch=branch,
                base=self.config.base,
                path=worktree_path,
                run_dir=run_dir,
            )
            qa_results = self._implement_with_retry(issue, worktree_path, run_dir)
            changed_files = self.git.changed_files(cwd=worktree_path)
            if not changed_files:
                raise IssueFailure("Codex completed without producing file changes.")

            self.git.commit_and_push(
                cwd=worktree_path,
                branch=branch,
                message=f"Implement issue #{issue.number}: {issue.title}",
                run_dir=run_dir,
            )
            pr_url = self.github.create_draft_pr(
                title=f"Implement #{issue.number}: {issue.title}",
                body=build_pr_body(issue, changed_files, qa_results, run_dir),
                branch=branch,
                base=self.config.base,
                run_dir=run_dir,
            )
            self.github.edit_issue_labels(
                issue.number,
                add=[AGENT_PR_OPEN_LABEL],
                remove=[AGENT_RUNNING_LABEL],
            )
            self.github.comment_issue(
                issue.number,
                f"Draft PR opened: {pr_url}\n\nRun logs: `{run_dir}`",
                run_dir=run_dir,
            )
            if worktree_path is not None:
                self.git.remove_worktree(worktree_path, run_dir=run_dir)
            emit(f"Opened draft PR for #{issue.number}: {pr_url}")
        except EnvironmentFailure as error:
            if claimed:
                self._mark_issue_failed(issue, error, run_dir)
            raise
        except IssueFailure as error:
            if claimed:
                self._mark_issue_failed(issue, error, run_dir)
            emit(f"Issue #{issue.number} failed: {error}", err=True)
        except CommandFailure as error:
            issue_error = IssueFailure(str(error), log_path=error.log_path)
            if claimed:
                self._mark_issue_failed(issue, issue_error, run_dir)
            emit(f"Issue #{issue.number} failed: {error}", err=True)

    def _validate_issue_contract(self, issue: Issue) -> None:
        missing = missing_required_sections(issue.body)
        if missing:
            raise IssueFailure(f"Missing required issue section(s): {', '.join(missing)}")

    def _branch_and_worktree(self, issue: Issue) -> tuple[str, Path]:
        slug = slugify(issue.title)
        branch = f"agent/issue-{issue.number}-{slug}"
        worktree_path = self.config.worktree_container / f"agent-issue-{issue.number}-{slug}"
        return branch, worktree_path

    def _implement_with_retry(self, issue: Issue, worktree_path: Path, run_dir: Path) -> list[QAResult]:
        first_prompt = implementation_prompt(issue)
        try:
            self._run_codex(first_prompt, worktree_path, run_dir / "codex-implementation-1.jsonl")
            return self._run_qa(worktree_path, run_dir)
        except EnvironmentFailure:
            raise
        except (CommandFailure, IssueFailure) as first_error:
            retry_prompt = retry_implementation_prompt(issue, first_error)
            self._run_codex(retry_prompt, worktree_path, run_dir / "codex-implementation-2.jsonl")
            return self._run_qa(worktree_path, run_dir)

    def _run_codex(self, prompt: str, cwd: Path, log_path: Path) -> None:
        if not self.runner.dry_run:
            log_path.with_suffix(".prompt.md").write_text(prompt, encoding="utf-8")
        self.runner.run(
            codex_exec_command(cwd),
            cwd=cwd,
            input_text=prompt,
            log_path=log_path,
            execute_in_dry_run=False,
        )

    def _run_qa(self, worktree_path: Path, run_dir: Path) -> list[QAResult]:
        changed_files = self.git.changed_files(cwd=worktree_path)
        if not changed_files:
            raise IssueFailure("No changed files available for QA selection.")
        commands = select_qa_commands(changed_files, worktree_path)
        if not commands:
            raise IssueFailure(
                "No QA command matched changed files: " + ", ".join(changed_files)
            )

        results: list[QAResult] = []
        for index, command in enumerate(commands, start=1):
            log_path = run_dir / f"qa-{index}-{slugify(command.name)}.log"
            try:
                self.runner.run(
                    list(command.args),
                    cwd=command.cwd,
                    log_path=log_path,
                    execute_in_dry_run=False,
                )
            except CommandFailure as error:
                if looks_like_environment_failure(error):
                    raise EnvironmentFailure(
                        f"Environment failure while running {command.name}: "
                        f"{format_command(command.args)}",
                        log_path=error.log_path,
                    ) from error
                raise
            results.append(QAResult(command=command, log_path=log_path))
        return results

    def _mark_issue_failed(self, issue: Issue, error: IssueFailure, run_dir: Path) -> None:
        self.github.edit_issue_labels(
            issue.number,
            add=[AGENT_FAILED_LABEL],
            remove=[AGENT_RUNNING_LABEL],
        )
        log_line = f"\n\nLog: `{error.log_path}`" if error.log_path is not None else ""
        self.github.comment_issue(
            issue.number,
            f"Agent issue loop failed: {error}{log_line}\n\nRun logs: `{run_dir}`",
            run_dir=run_dir,
        )

    def _run_triage(self, issue: Issue) -> None:
        run_dir = self._run_dir(issue, prefix="triage")
        run_dir.mkdir(parents=True, exist_ok=True)
        prompt = triage_prompt(issue, self.config.repo)
        self._run_codex(prompt, self.config.repo_root, run_dir / "codex-triage.jsonl")
        emit(f"Triage pass completed for #{issue.number}.")

    def _run_dir(self, issue: Issue, *, prefix: str = "issue") -> Path:
        timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        return self.config.log_root / f"{prefix}-{issue.number}-{timestamp}"


def implementation_prompt(issue: Issue) -> str:
    return textwrap.dedent(
        f"""
        Implement GitHub issue #{issue.number}: {issue.title}

        Work in this repository worktree only. Follow AGENTS.md and the repo's
        canonical terms, especially Subproject, Test lane, Fast check, Commit
        check, and Push check.

        Do not commit, push, open a PR, or edit GitHub labels/comments. The
        Ralph script owns those steps after validation.

        You may run narrowed checks while debugging. The Ralph script will run
        final required QA after your turn.

        Issue URL: {issue.url}

        Issue body:

        {issue.body}
        """
    ).strip()


def retry_implementation_prompt(issue: Issue, error: Exception) -> str:
    detail = str(error)
    if isinstance(error, CommandFailure):
        detail = command_failure_summary(error)
    if isinstance(error, IssueFailure) and error.log_path is not None:
        detail = f"{error}\nLog: {error.log_path}"
    return textwrap.dedent(
        f"""
        Continue implementing GitHub issue #{issue.number}: {issue.title}

        The previous attempt failed. Fix the issue in the current worktree.
        Do not commit, push, open a PR, or edit GitHub labels/comments.

        Failure detail:

        {detail}
        """
    ).strip()


def triage_prompt(issue: Issue, repo: str) -> str:
    return textwrap.dedent(
        f"""
        Use the $triage skill to triage GitHub issue #{issue.number} in {repo}.

        You may use gh to label, comment, or close the issue. Do not edit repo
        files during this automated post-loop triage pass.

        Triage label mapping:
        - bug: bug
        - enhancement: enhancement
        - needs-triage: needs-triage
        - needs-info: needs-info
        - ready-for-agent: ready-for-agent
        - ready-for-human: ready-for-human
        - wontfix: wontfix

        Runtime labels owned by the Ralph loop:
        - agent-running
        - agent-failed
        - agent-pr-open

        Every issue comment you post must begin with:
        {AI_TRIAGE_DISCLAIMER}

        If an enhancement looks like wontfix and would require creating or
        updating .out-of-scope/, mark it ready-for-human instead and explain
        that v1 automated triage does not write repo files.

        Issue URL: {issue.url}

        Issue body:

        {issue.body}
        """
    ).strip()


def command_failure_summary(error: CommandFailure) -> str:
    pieces = [
        f"Command: {format_command(error.command)}",
        f"Exit code: {error.returncode}",
    ]
    if error.log_path is not None:
        pieces.append(f"Log: {error.log_path}")
    if error.stderr.strip():
        pieces.append("stderr:\n" + tail_text(error.stderr))
    if error.stdout.strip():
        pieces.append("stdout:\n" + tail_text(error.stdout))
    return "\n\n".join(pieces)


def tail_text(value: str, *, max_lines: int = 80) -> str:
    lines = value.splitlines()
    return "\n".join(lines[-max_lines:])


def build_pr_body(
    issue: Issue,
    changed_files: list[str],
    qa_results: list[QAResult],
    run_dir: Path,
) -> str:
    qa_lines = [
        f"- `{format_command(result.command.args)}` from `{result.command.cwd}`"
        for result in qa_results
    ]
    changed_lines = [f"- `{path}`" for path in changed_files]
    return "\n".join(
        [
            f"Closes #{issue.number}",
            "",
            "## Summary",
            "",
            f"Implements `{issue.title}` through the Ralph agent issue loop.",
            "",
            "## Changed files",
            "",
            *changed_lines,
            "",
            "## QA",
            "",
            *qa_lines,
            "",
            f"Run logs: `{run_dir}`",
            "",
            "This PR was opened as a draft by the Ralph loop for human review.",
            "",
        ]
    )


def discover_repo_root(runner: CommandRunner) -> Path:
    result = runner.run(["git", "rev-parse", "--show-toplevel"], cwd=Path.cwd())
    return Path(result.stdout.strip())


def discover_repo_slug(runner: CommandRunner, repo_root: Path) -> str:
    result = runner.run(["git", "config", "--get", "remote.origin.url"], cwd=repo_root)
    return parse_repo_slug(result.stdout)


def default_worktree_container(repo_root: Path) -> Path:
    if repo_root.parent.name.endswith("__worktrees"):
        return repo_root.parent
    return repo_root.parent / f"{repo_root.name}__worktrees"


def build_config(args: argparse.Namespace, runner: CommandRunner) -> LoopConfig:
    repo_root = discover_repo_root(runner).resolve()
    repo = args.repo or discover_repo_slug(runner, repo_root)
    log_root = (repo_root / ".ralph" / "runs").resolve()
    worktree_container = (
        Path(args.worktree_container).resolve()
        if args.worktree_container is not None
        else default_worktree_container(repo_root).resolve()
    )
    return LoopConfig(
        repo_root=repo_root,
        repo=repo,
        base=args.base,
        issue=args.issue,
        drain=args.drain,
        max_issues=args.max_issues,
        dry_run=args.dry_run,
        bootstrap_labels=args.bootstrap_labels,
        issue_limit=args.issue_limit,
        log_root=log_root,
        worktree_container=worktree_container,
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Drain ready GitHub issues through Codex implementation and triage."
    )
    parser.add_argument("--repo", help="GitHub repository in OWNER/REPO form.")
    parser.add_argument("--base", default="main", help="Base branch for generated PRs.")
    parser.add_argument("--issue", type=int, help="Implement one specific issue number.")
    parser.add_argument(
        "--drain",
        action="store_true",
        help="Continue through implementation and triage until the queue is blocked or empty.",
    )
    parser.add_argument(
        "--max-issues",
        type=int,
        default=3,
        help="Maximum implementation attempts in --drain mode. Use 0 for unlimited.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Show the next action only.")
    parser.add_argument(
        "--bootstrap-labels",
        action="store_true",
        help="Create or update the required triage and runtime labels.",
    )
    parser.add_argument(
        "--issue-limit",
        type=int,
        default=100,
        help="Maximum open issues to inspect per scan.",
    )
    parser.add_argument(
        "--worktree-container",
        help="Directory where per-issue worktrees should be created.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    parsed_args = parse_args(sys.argv[1:] if argv is None else argv)
    runner = CommandRunner(dry_run=parsed_args.dry_run)
    try:
        config = build_config(parsed_args, runner)
        RalphLoop(config, runner).run()
    except RalphError as error:
        emit(f"ralph: {error}", err=True)
        return 1
    except ValueError as error:
        emit(f"ralph: {error}", err=True)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
