encryptionsalt: v1:3H8MEt0seIk=:v1:wZZ0GsOGkcvXYXxf:arSaYEpMPaiUKzN/7ptJc9mvlvFfKA==
config:
  aws:region: ap-southeast-2
  aws-pulumi:cognito_client_id:
    secure: v1:ZraZSIf+h0e+zgPH:rHCWqn+surygwlNWR2sPr+jINNdAvqofCbIhLfNdgPuHgehDWf2ruN9r
  aws-pulumi:cognito_server_metadata_url:
    secure: v1:FFtNw+Jz3zxdDglM:+gjdb5iAdg7FP79CR5zqkm9slW9CouvbQQCcSfWcvRaqkBR5OLdtkJqhAZJPgjxIwEDFeAo8X9NQ82mKMiRoFMc5wp0/F8VZH2yTlXI+HicusavneCzUOtyDgZN1r5cywusQFmaV0GBi7FCaKwL5wBf5DzhPwv2sHAE=
  aws-pulumi:cognito_token_signing_key_url:
    secure: v1:puqTS1wTpCMG+ps3:L39Yls1EoEqriE8xbqJ3Jw7JXscXHlKl/zBap25ZLI5eHyFN7vMEXreoWjfA4UcDXWtdabRwM8yA23QotVUPk+a8755l5zjqYE25STYBEpbAuSlcjFNMWjWeWYgAQsuUZUo2NdZ6x2I9B1zPv+nv
  aws-pulumi:cognito_client_secret:
    secure: v1:I/f+km0DuuLWGcmB:0gjniiKbvk2poSoAxckvx+wcbEi2cSF3keS5GXE8MMBkFCt6+5Jh3hpyNUKGh9/lXJCo1XGF80efQYhnmBqmLRJPHds=
  aws-pulumi:website_root_url: ausenergymarketdata.com
  aws-pulumi:developer_email: ""
  aws-pulumi:dagster_failure_alert_topic_arn: arn:aws:sns:ap-southeast-2:100187958338:dagster-failed-run-alerts
