from dagster import AssetSpec
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_2p_sensitivities",
    glob_pattern="gasbb2psensitivies*",
    schema={
        "PeriodID": String,
        "State": String,
        "Increase": Float64,
        "Decrease": Float64,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "PeriodID": "relevant periods",
        "State": "state",
        "Increase": "increase value",
        "Decrease": "decrease value",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["PeriodID", "State"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "This report displays information about Field Reserves and Resources. "
        "Both GASBB_2P_SENSETIVITIES_ALL and GASBB_2P_SENSETIVITIES_LAST_QUARTER are "
        "updated monthly."
    ),
)
