from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_locations_list",
    glob_pattern="gasbblocationslist*",
    schema={
        "LocationName": String,
        "LocationId": Int64,
        "State": String,
        "LocationType": String,
        "Description": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "LocationName": "Name of the Location.",
        "LocationId": "Unique Location identifier.",
        "State": "Location state.",
        "LocationType": "Type of location.",
        "Description": "Free text description of the Location.",
        "LastUpdated": "Date the list of locations was last updated.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["LocationId", "LastUpdated"],
    group_name="gbb__gasbb",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Lists all production and demand locations within the Bulletin Board system. "
        "Updated daily."
    ),
)
