from dagster import AssetSpec
from polars import Boolean, Datetime, Int64, String

from aemo_etl.defs.gbb.hooks import EnsureColumnsHook
from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_nodes_connection_points",
    glob_pattern="gasbbnodesandconnectionpoints*",
    schema={
        "FacilityName": String,
        "FacilityId": Int64,
        "FacilityType": String,
        "ConnectionPointId": Int64,
        "ConnectionPointName": String,
        "FlowDirection": String,
        "Exempt": Boolean,
        "ExemptionDescription": String,
        "NodeId": Int64,
        "StateId": Int64,
        "StateName": String,
        "LocationName": String,
        "LocationId": Int64,
        "EffectiveDate": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "FacilityName": "Name of the facility.",
        "FacilityId": "A unique AEMO defined facility identifier.",
        "FacilityType": "Facility type associated with the Facility Id.",
        "ConnectionPointId": "A unique AEMO defined connection point identifier.",
        "ConnectionPointName": "Name of connection point.",
        "FlowDirection": "Gas flow direction: Receipt, Delivery, Processed, DeliveryLngStor.",
        "Exempt": "Flag indicating whether the connection point has a data exemption.",
        "ExemptionDescription": "Description of exemption.",
        "NodeId": "A unique AEMO defined node identifier.",
        "StateId": "A unique AEMO defined state identifier.",
        "StateName": "Name of the state.",
        "LocationName": "Name of location.",
        "LocationId": "A unique AEMO defined location identifier.",
        "EffectiveDate": "Date record is effective from",
        "LastUpdated": "Date the record was last modified.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    bronze_postprocess_object_hooks=[
        EnsureColumnsHook([("EffectiveDate", String), ("OperatingState", String)])
    ],
    surrogate_key_sources=[
        "FacilityId",
        "ConnectionPointId",
        "EffectiveDate",
        "LastUpdated",
    ],
    group_name="gbb__gasbb",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Detailed information on all facilities and their associated nodes and Connection Points. "
        "Updated daily."
    ),
)
