from dagster import AssetSpec
from polars import Datetime, Float64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_lng_transactions",
    glob_pattern="gasbblngtransactions*",
    schema={
        "TransactionMonth": String,
        "VolWeightPrice": Float64,
        "Volume": Float64,
        "SupplyStartDate": String,
        "SupplyEndDate": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "TransactionMonth": "Transaction month.",
        "VolWeightPrice": "The volume weighted price for the reporting period.",
        "Volume": "The total volume of the transactions for the reporting period.",
        "SupplyStartDate": "The earliest start date of all transactions in the reporting period.",
        "SupplyEndDate": "The latest end date of all transactions in the reporting period.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["TransactionMonth", "SupplyStartDate", "SupplyEndDate"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="LNG transaction aggregated data. GASBB_LNG_TRANSACTIONS is updated monthly.",
)
