from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.defs.gbb.hooks import EnsureColumnsHook
from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_facilities",
    glob_pattern="gasbbfacilities*",
    schema={
        "FacilityName": String,
        "FacilityShortName": String,
        "FacilityId": Int64,
        "FacilityType": String,
        "FacilityTypeDescription": String,
        "OperatingState": String,
        "OperatingStateDate": String,
        "OperatorName": String,
        "OperatorId": Int64,
        "OperatorChangeDate": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "FacilityName": "Name of the facility.",
        "FacilityShortName": "Abbreviated version of the facility name.",
        "FacilityId": "A unique AEMO defined facility identifier.",
        "FacilityType": "Facility type associated with the facility id.",
        "FacilityTypeDescription": "Free text description of the facility type.",
        "OperatingState": "The operating state (Active or Inactive) of the facility.",
        "OperatingStateDate": "Date the current operating state was set.",
        "OperatorName": "Name of the operator for the facility.",
        "OperatorId": "The facility operator's ID.",
        "OperatorChangeDate": "Date the current operator for the facility was set.",
        "LastUpdated": "Date and time the record was last modified.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    bronze_postprocess_object_hooks=[EnsureColumnsHook([("LastUpdated", String)])],
    surrogate_key_sources=["FacilityId", "LastUpdated"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "List of all currently registered BB facilities and organisation responsible for operation. "
        "Updated daily."
    ),
)
