from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_shippers_list",
    glob_pattern="gasbbshippers*",
    schema={
        "EffectiveDate": String,
        "FacilityId": Int64,
        "FacilityName": String,
        "FacilityType": String,
        "CompanyId": Int64,
        "OperatorName": String,
        "ShipperName": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "EffectiveDate": "Gas date that corresponding record takes effect.",
        "FacilityId": "A unique AEMO defined Facility identifier.",
        "FacilityName": "The name of the BB facility.",
        "FacilityType": "The type of facility.",
        "CompanyId": "Unique identifier for the company who operates the facility.",
        "OperatorName": "The name of the company who operates the facility.",
        "ShipperName": "The name of the shipper who holds the capacity.",
        "LastUpdated": "The date data was last submitted.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "EffectiveDate",
        "FacilityId",
        "ShipperName",
        "LastUpdated",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="Shippers with contracted primary Storage, Compression or Pipeline capacity. Updated daily.",
)
