from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_facility_developments",
    glob_pattern="gasbbfacilitydevelopments*",
    schema={
        "DevFacilityId": Int64,
        "ProposedName": String,
        "EffectiveDate": String,
        "FacilityType": String,
        "MinNameplate": Float64,
        "MaxNameplate": Float64,
        "Location": String,
        "PlannedCommissionFrom": String,
        "PlannedCommissionTo": String,
        "DevelopmentStage": String,
        "RelatedFacilityId": String,
        "RelatedFacilityName": String,
        "Comments": String,
        "ReportingEntity": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "DevFacilityId": "A unique AEMO defined Development Facility Identifier.",
        "ProposedName": "The name of the Facility development.",
        "EffectiveDate": "The effective date of the submission.",
        "FacilityType": "The facility development type.",
        "MinNameplate": "The lower estimate of nameplate rating capacity.",
        "MaxNameplate": "The upper estimate of nameplate rating capacity.",
        "Location": "The location of the development facility.",
        "PlannedCommissionFrom": "The planned start date of commissioning.",
        "PlannedCommissionTo": "The planned end date of commissioning.",
        "DevelopmentStage": "Current stage: PROPOSED, COMMITTED, CANCELLED, ENDED.",
        "RelatedFacilityId": "Any facility IDs related to the development facility.",
        "RelatedFacilityName": "The name of any related facility IDs.",
        "Comments": "Any additional comments included in the submission.",
        "ReportingEntity": "The entity reporting for the facility development.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["DevFacilityId", "EffectiveDate"],
    group_name="gas_raw",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb_duplicate"]),
    ],
    description=(
        "List of all Facility Developments. "
        "GASBB_FACILITYDEVELOPMENTS is updated within 30 minutes of receiving new data."
    ),
)
