from dagster import AssetSpec
from polars import Datetime, Float64, String

from aemo_etl.defs.gbb.hooks import GshGasTradesParseHook
from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

# TODO: Apply GshGasTradesParseHook once ported.
#
# The source CSV has a non-standard format:
#   - First 4 columns are metadata, not data
#   - Has a header row that needs stripping
#   - Has footer rows that need removing
#
# The legacy hook handles this at the bytes level before CSV parsing:
#   gsh_gas_trades_process_object(logger, contents) -> LazyFrame
#
# When ready, wrap it as a Hook[bytes] and pass to
# bronze_postprocess_object_hooks=[GshGasTradesParseHook()].
#
# class GshGasTradesParseHook(Hook[bytes]):
#     def process(self, s3_bucket: str, s3_key: str, object_: bytes) -> bytes:
#         csv_string = "\n".join(
#             [
#                 ",".join(line.split(",")[4:])
#                 for line in object_.decode("utf-8")
#                 .replace("\r\n", "\n")
#                 .split("\n")[1:-2]
#             ]
#         ).encode()
#         return csv_string

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_gsh_gas_trades",
    glob_pattern="gasbbgshgastrades*",
    schema={
        "TRADE_DATE": String,
        "TYPE": String,
        "PRODUCT": String,
        "LOCATION": String,
        "TRADE_PRICE": Float64,
        "DAILY_QTY_GJ": Float64,
        "START_DATE": String,
        "END_DATE": String,
        "MANUAL_TRADE": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "TRADE_DATE": "Date of the trade",
        "TYPE": "Trade Type",
        "PRODUCT": "Trade Product",
        "LOCATION": "Location",
        "TRADE_PRICE": "Price",
        "DAILY_QTY_GJ": "Quantity",
        "START_DATE": "Start Date",
        "END_DATE": "End Date",
        "MANUAL_TRADE": "Manual Trade?",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    bronze_postprocess_object_hooks=[GshGasTradesParseHook()],
    surrogate_key_sources=[
        "TRADE_DATE",
        "TYPE",
        "PRODUCT",
        "LOCATION",
        "START_DATE",
        "END_DATE",
        "MANUAL_TRADE",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Complete list of historical GSH gas trades. "
        "Used to analyse market trends over time."
    ),
)
