from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_pipeline_connection_flow_v2",
    glob_pattern="gasbbpipelineconnectionflow*",
    schema={
        "GasDate": String,
        "FacilityName": String,
        "FacilityId": Int64,
        "ConnectionPointName": String,
        "ConnectionPointId": Int64,
        "ActualQuantity": Float64,
        "FlowDirection": String,
        "State": String,
        "LocationName": String,
        "LocationId": Int64,
        "Quality": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "GasDate": "Date of gas day.",
        "FacilityId": "A unique AEMO defined Facility identifier.",
        "FacilityName": "Name of the facility.",
        "ConnectionPointId": "A unique AEMO defined connection point identifier.",
        "ConnectionPointName": "Names of the connection point.",
        "FlowDirection": "RECEIPT or DELIVERY.",
        "ActualQuantity": "Actual flow quantity in TJ.",
        "State": "Location.",
        "LocationName": "Name of the Location.",
        "LocationId": "Unique Location identifier.",
        "Quality": "OK, NIL, OOR, or Not Available.",
        "LastUpdated": "Date and time the record was last modified.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "GasDate",
        "FacilityId",
        "ConnectionPointId",
        "FlowDirection",
        "LastUpdated",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="Daily production and usage at each Connection Point (v2, with LastUpdated key).",
)
