from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_contacts",
    glob_pattern="gasbbcontacts*",
    schema={
        "PersonId": Int64,
        "PersonName": String,
        "CompanyName": String,
        "CompanyId": Int64,
        "Position": String,
        "Email": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "PersonId": "Person unique identifier.",
        "PersonName": "Name of the person.",
        "CompanyName": "Company name associated with the person.",
        "CompanyId": "Company ID associated with the person.",
        "Position": "Job title of person.",
        "Email": "Email address of person.",
        "LastUpdated": "Date and time the record was last modified.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["PersonId", "LastUpdated"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="Registered contact details for each participant. Updated daily.",
)
