from dagster import AssetSpec
from polars import Datetime, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_nt_lng_flow",
    glob_pattern="gasbbntlngflow*",
    schema={
        "Gas Date": String,
        "Total Receipts": String,
        "Total Deliveries": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "Gas Date": "Gas Date",
        "Total Receipts": "Total Receipts",
        "Total Deliveries": "Total Deliveries",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["Gas Date", "Total Receipts", "Total Deliveries"],
    group_name="gbb__gasbb",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="Report outlining NT LNG total flows.",
)
