from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_late_nomination_forecast",
    glob_pattern="gasbblatenominationandforecast*",
    schema={
        "GasDate": String,
        "FacilityName": String,
        "FacilityId": Int64,
        "ConnectionPointId": Int64,
        "EarliestSubmissionDate": String,
        "LateTimeSpan": Float64,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "GasDate": "Date of gas day.",
        "FacilityName": "Name of the facility.",
        "FacilityId": "A unique AEMO defined Facility identifier.",
        "ConnectionPointId": "A unique AEMO defined connection point identifier.",
        "EarliestSubmissionDate": "Date and time of the earliest submission for that gas date.",
        "LateTimeSpan": "Hours and minutes between submission cut-off and earliest submission date.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "GasDate",
        "FacilityId",
        "ConnectionPointId",
        "EarliestSubmissionDate",
    ],
    group_name="gbb__gasbb",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Record of late submissions for BB reporting entities. "
        "Updated daily, covers the last 31 days."
    ),
)
