from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_connection_point_nameplate",
    glob_pattern="gasbbconnectionpointnameplate*",
    schema={
        "ConnectionPointName": String,
        "ConnectionPointId": Int64,
        "FacilityName": String,
        "FacilityId": Int64,
        "FacilityType": String,
        "OwnerName": String,
        "OwnerId": Int64,
        "OperatorName": String,
        "OperatorId": Int64,
        "CapacityQuantity": Float64,
        "EffectiveDate": String,
        "Description": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "ConnectionPointName": "Connection Point name associated to a BB Pipeline or compression facility.",
        "ConnectionPointId": "A unique AEMO defined connection point identifier.",
        "FacilityName": "The facility reported.",
        "FacilityId": "Unique facility identifier.",
        "FacilityType": "The type of facility.",
        "OwnerName": "The reporting facility owner.",
        "OwnerId": "The reporting facility owner ID.",
        "OperatorName": "Name of the operator for the facility.",
        "OperatorId": "The facility operator's ID.",
        "CapacityQuantity": "Standing capacity quantity in TJ.",
        "EffectiveDate": "Gas day date that corresponding record takes effect.",
        "Description": "Reasons or comments related to the capacity quantity.",
        "LastUpdated": "The date data was last submitted by a participant.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "ConnectionPointId",
        "FacilityId",
        "EffectiveDate",
        "LastUpdated",
    ],
    group_name="gbb__gasbb",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Nameplate rating for each connection point connected to a BB pipeline or compression facility. "
        "Produced daily."
    ),
)
