from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_actual_flow_storage",
    glob_pattern="gasbbactualflowstorage*",
    schema={
        "GasDate": String,
        "FacilityName": String,
        "State": String,
        "LocationId": Int64,
        "LocationName": String,
        "Demand": Float64,
        "Supply": Float64,
        "TransferIn": Float64,
        "TransferOut": Float64,
        "HeldInStorage": Float64,
        "FacilityId": Int64,
        "FacilityType": String,
        "CushionGasStorage": Float64,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "GasDate": "Date of gas day. Timestamps are ignored.",
        "FacilityName": "Name of the facility.",
        "State": "Name of the state.",
        "LocationId": "Unique location identifier.",
        "LocationName": "Name of the location.",
        "Demand": "Usage type expressed in TJ.",
        "Supply": "Usage type expressed in TJ.",
        "TransferIn": "Usage type. Only applicable to BB pipelines.",
        "TransferOut": "Usage type. Only applicable to BB pipelines.",
        "HeldInStorage": "Quantity held in storage.",
        "FacilityId": "A unique AEMO defined Facility identifier.",
        "FacilityType": "The type of facility.",
        "CushionGasStorage": "Quantity of gas retained to maintain required pressure.",
        "LastUpdated": "The date data was last submitted by a participant.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["GasDate", "FacilityId", "LocationId", "LastUpdated"],
    group_name="gas_raw",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb_duplicate"]),
    ],
    description=(
        "Daily Production, Flow and Storage data aggregated by Facility Id. "
        "Updated daily with historic records back to Sep 2018."
    ),
)
