from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.definitions.df_from_s3_keys import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_linepack_capacity_adequacy",
    glob_pattern="gasbblinepackcapacityadequacy*",
    schema={
        "GasDate": String,
        "FacilityId": Int64,
        "FacilityName": String,
        "FacilityType": String,
        "Flag": String,
        "Description": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "GasDate": "Date of gas day.",
        "FacilityId": "A unique AEMO defined Facility identifier.",
        "FacilityName": "The name of the BB facility.",
        "FacilityType": "The type of facility.",
        "Flag": "Traffic light colour (Green, Amber, Red) indicating LCA status.",
        "Description": "Comments related to the change in LCA flag.",
        "LastUpdated": "The date when the record was last updated.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["GasDate", "FacilityId", "LastUpdated"],
    group_name="gbb__gasbb",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb_duplicate"]),
    ],
    description=(
        "Linepack Capacity Adequacy for each Pipeline for D to D+2. "
        "Produced daily with historical and future data."
    ),
)
