import json
from collections import defaultdict
from collections.abc import Mapping
from importlib.metadata import version
from typing import cast

import polars as pl
from dagster import (
    AssetExecutionContext,
    AssetIn,
    AutomationCondition,
    Definitions,
    TableSchema,
    asset,
    definitions,
)
from polars import LazyFrame, String

from aemo_etl.configs import AEMO_BUCKET
from aemo_etl.utils import get_metadata_schema, get_surrogate_key

pkg_version = version("aemo_etl")


DESCRIPTIONS = {
    "asset_key_path": "key path of asset",
    "metadata": "JSON-serialised metadata of asset",
    "description": "asset description",
    "dependencies": "key path of asset dependencies",
    "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
}

SCHEMA = {
    "asset_key_path": list[str],
    "metadata": str,
    "description": str,
    "dependencies": list[list[str]],
    "surrogate_key": String,
}


DOMAIN = "metadata"

TABLE_NAME = "bronze_table_metadata"

KEY_PREFIX = ["bronze", DOMAIN]


def _safe_json(metadata: Mapping[str, object]) -> str | None:
    """Serialise a metadata dict to JSON.

    TableSchema values are expanded to {column_name: {type, description}} dicts
    so they can be split into column_schema / column_description in the silver layer.
    Any other non-serialisable value falls back to its string representation.
    """
    if not metadata:
        return None
    safe: dict[str, object] = {}
    for k, v in metadata.items():
        if isinstance(v, TableSchema):
            safe[k] = {
                col.name: {"type": str(col.type), "description": col.description or ""}
                for col in v.columns
            }
        else:
            try:
                json.dumps(v)
                safe[k] = v
            except Exception:
                safe[k] = str(v)
    return json.dumps(safe)


@asset(
    key_prefix=KEY_PREFIX,
    group_name="gas_raw",
    description="Table metadata asset",
    io_manager_key="aemo_deltalake_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"aemo.{DOMAIN}.{TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(KEY_PREFIX)}/{TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(SCHEMA, DESCRIPTIONS),
        "surrogate_key_sources": ["asset_key_path"],
        "cron_schedule": "0 0 * * *",
        "cron_description": "At 12:00 AM",
    },
    kinds={"table", "deltalake"},
    automation_condition=(
        AutomationCondition.code_version_changed()
        | AutomationCondition.missing()
        | AutomationCondition.on_cron("@daily")
    )
    & ~AutomationCondition.in_progress(),
    # code_version=random_hash,
    code_version=pkg_version,
)
def bronze_table_metadata(context: AssetExecutionContext) -> LazyFrame:
    asset_keys = context.repository_def.assets_defs_by_key

    data_dict: defaultdict[str, list[str | object]] = defaultdict(list)

    for asset_key in asset_keys:
        asset_defs = context.repository_def.assets_defs_by_key.get(asset_key)

        metadata: Mapping[str, object] = {}
        description = ""
        asset_deps = []

        if hasattr(asset_defs, "metadata_by_key"):
            metadata = cast(
                Mapping[str, object], asset_defs.metadata_by_key.get(asset_key)
            )

        if hasattr(asset_defs, "descriptions_by_key"):
            description = asset_defs.descriptions_by_key.get(asset_key, "")

        if hasattr(asset_defs, "asset_deps"):
            asset_deps = [
                [item for item in key.path] for key in asset_defs.asset_deps.keys()
            ]

        data_dict["asset_key_path"].append([item for item in asset_key.path])
        data_dict["metadata"].append(_safe_json(metadata))
        data_dict["description"].append(description)
        data_dict["dependencies"].append(asset_deps)

    output = LazyFrame(data_dict, strict=False).with_columns(
        surrogate_key=get_surrogate_key([pl.col("asset_key_path").list.join("__")])
    )

    return output


SILVER_TABLE_NAME = "silver_table_metadata"

SILVER_KEY_PREFIX = ["silver", DOMAIN]

SILVER_DESCRIPTIONS = {
    "asset_key_path": "key path of asset",
    "description": "asset description",
    "dependencies": "key path of asset dependencies",
    "dagster_table_name": "dagster table name from asset metadata",
    "dagster_uri": "dagster URI from asset metadata",
    "column_schema": "JSON dict of {column_name: type} from asset column schema",
    "column_description": "JSON dict of {column_name: description} from asset column schema",
    "surrogate_key_sources": "surrogate key sources from asset metadata",
    "cron_schedule": "cron schedule from asset metadata (when present)",
    "cron_description": "human-readable cron description (when present)",
    "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
}

SILVER_SCHEMA = {
    "asset_key_path": list[str],
    "description": str,
    "dependencies": list[list[str]],
    "dagster_table_name": str,
    "dagster_uri": str,
    "column_schema": str,
    "column_description": str,
    "surrogate_key_sources": str,
    "cron_schedule": str,
    "cron_description": str,
    "surrogate_key": String,
}

# Simple string-valued metadata keys extracted verbatim (or JSON-serialised if list/dict)
METADATA_KEYS = {
    "dagster/table_name": "dagster_table_name",
    "dagster/uri": "dagster_uri",
    "surrogate_key_sources": "surrogate_key_sources",
    "cron_schedule": "cron_schedule",
    "cron_description": "cron_description",
}


def _silver_extract(raw: str | None, key: str) -> str | None:
    """Extract a scalar value from a JSON metadata string by key."""
    if raw is None:
        return None
    value = json.loads(raw).get(key)
    if value is None:
        return None
    return value if isinstance(value, str) else json.dumps(value)


def _silver_extract_column_schema_field(raw: str | None, field: str) -> str | None:
    """Extract {col_name: field_value} from the dagster/column_schema dict."""
    if raw is None:
        return None
    schema_dict = json.loads(raw).get("dagster/column_schema")
    if not schema_dict:
        return None
    return json.dumps({col: info[field] for col, info in schema_dict.items()})


@asset(
    key_prefix=SILVER_KEY_PREFIX,
    name=SILVER_TABLE_NAME,
    group_name="gas_model",
    description="Silver table metadata asset — flattened metadata dict from bronze",
    ins={"df": AssetIn(bronze_table_metadata.key)},
    io_manager_key="aemo_deltalake_overwrite_io_manager",
    metadata={
        "dagster/table_name": f"aemo.{DOMAIN}.{SILVER_TABLE_NAME}",
        "dagster/uri": f"s3://{AEMO_BUCKET}/{'/'.join(SILVER_KEY_PREFIX)}/{SILVER_TABLE_NAME}",
        "dagster/column_schema": get_metadata_schema(
            SILVER_SCHEMA, SILVER_DESCRIPTIONS
        ),
        "surrogate_key_sources": ["asset_key_path"],
    },
    kinds={"table", "deltalake"},
    automation_condition=(
        AutomationCondition.any_deps_updated() | AutomationCondition.missing()
    )
    & ~AutomationCondition.in_progress(),
)
def silver_table_metadata(df: LazyFrame) -> LazyFrame:
    collected = df.collect()

    collected = collected.with_columns(
        [
            pl.col("metadata")
            .map_elements(
                lambda m, k=src_key: _silver_extract(m, k),
                return_dtype=pl.String,
            )
            .alias(col_name)
            for src_key, col_name in METADATA_KEYS.items()
        ]
        + [
            pl.col("metadata")
            .map_elements(
                lambda m: _silver_extract_column_schema_field(m, "type"),
                return_dtype=pl.String,
            )
            .alias("column_schema"),
            pl.col("metadata")
            .map_elements(
                lambda m: _silver_extract_column_schema_field(m, "description"),
                return_dtype=pl.String,
            )
            .alias("column_description"),
        ]
    )

    return collected.drop("metadata").lazy()


@definitions
def defs() -> Definitions:
    return Definitions(assets=[bronze_table_metadata, silver_table_metadata])
