from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.defs.raw.gbb.hooks import LowercaseColumnsHook
from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

# TODO: Apply NameplateRatingLowercaseHook once ported.
#
# The source files have inconsistent column name casing. The legacy hook normalises
# all column names to lowercase before schema matching:
#   nameplate_rating_preprocess(logger, df) -> LazyFrame
#
# When ready, wrap it as a Hook[LazyFrame] and pass to
# bronze_postprocess_lazyframe_hooks=[NameplateRatingLowercaseHook()].
#
# class NameplateRatingLowercaseHook(Hook[LazyFrame]):
#     def process(self, s3_bucket: str, s3_key: str, object_: LazyFrame) -> LazyFrame:
#         columns = object_.collect_schema().keys()
#         return object_.rename({c: c.lower() for c in columns})

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_nameplate_rating",
    glob_pattern="gasbbnameplaterating*",
    schema={
        "facilityname": String,
        "facilityid": Int64,
        "facilitytype": String,
        "capacitytype": String,
        "capacityquantity": Float64,
        "flowdirection": String,
        "capacitydescription": String,
        "receiptlocation": Int64,
        "receiptlocationname": String,
        "deliverylocation": Int64,
        "deliverylocationname": String,
        "effectivedate": String,
        "description": String,
        "lastupdated": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "facilityname": "Facility name associated with the Facility Id.",
        "facilityid": "A unique AEMO defined Facility identifier.",
        "facilitytype": "Facility type associated with the Facility Id.",
        "capacitytype": "Storage or MDQ.",
        "capacityquantity": "Standing capacity quantity in TJ.",
        "flowdirection": "Receipt, Delivery, Processed, DeliveryLngStor, or NONE.",
        "capacitydescription": "Free text describing the capacity number.",
        "receiptlocation": "Connection Point Id for the receipt location.",
        "receiptlocationname": "The name of the receipt location.",
        "deliverylocation": "Connection Point Id for the delivery location.",
        "deliverylocationname": "The name of the delivery location.",
        "effectivedate": "Gas day date the record takes effect.",
        "description": "Comments related to the quantity or change.",
        "lastupdated": "Date and time record was last updated.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    bronze_postprocess_object_hooks=[LowercaseColumnsHook()],
    surrogate_key_sources=[
        "facilityid",
        "capacitytype",
        "flowdirection",
        "effectivedate",
        "lastupdated",
        "receiptlocation",
        "deliverylocation",
    ],
    group_name="gas_raw",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
    ],
    description=(
        "Standing nameplate capacity of all BB facilities. "
        "Full list updated annually; current updated within 30 minutes of new data."
    ),
)
