from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_nomination_and_forecast",
    glob_pattern="gasbbnominationandforecast*",
    schema={
        "Gasdate": String,
        "FacilityName": String,
        "FacilityType": String,
        "State": String,
        "LocationName": String,
        "Demand": Float64,
        "Supply": Float64,
        "TransferIn": Float64,
        "TransferOut": Float64,
        "FacilityId": Int64,
        "LocationId": Int64,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "Gasdate": "Date of gas day.",
        "FacilityName": "The name of the BB facility.",
        "FacilityType": "Facility type associated with the Facility Id.",
        "State": "Name of the state.",
        "LocationName": "Name of the location.",
        "Demand": "Usage type expressed in TJ.",
        "Supply": "Usage type expressed in TJ.",
        "TransferIn": "Usage type expressed in TJ. Only applicable to BB pipelines.",
        "TransferOut": "Usage type expressed in TJ. Only applicable to BB pipelines.",
        "FacilityId": "A unique AEMO defined Facility identifier.",
        "LocationId": "Unique location identifier.",
        "LastUpdated": "Date file was last updated.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["Gasdate", "FacilityId", "LocationId", "LastUpdated"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Nomination and Forecast data submitted to the market, aggregated by BB facility. "
        "Updated daily."
    ),
)
