from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.defs.raw.gbb.hooks import ForecastUtilisationUnpivotHook
from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

# TODO: Apply ForecastUtilisationUnpivotHook once ported.
#
# The source files are wide-format with dynamic date columns:
#   State | FacilityId | Monday 1 Jan | Tuesday 2 Jan | ...
#
# These need to be unpivoted to long format:
#   State | FacilityId | ForecastDate | ForecastValue | ForecastDay | ForecastPeriod
#
# The hook logic lives in legacy_configurations/gasbb/hooks.py:
#   forecast_utilisation_preprocess(logger, df) -> LazyFrame
#
# When ready, wrap it as a Hook[LazyFrame] and pass to
# bronze_postprocess_lazyframe_hooks=[ForecastUtilisationUnpivotHook()].
#
# class ForecastUtilisationUnpivotHook(Hook[LazyFrame]):
#     def process(self, s3_bucket: str, s3_key: str, object_: LazyFrame) -> LazyFrame:
#         return forecast_utilisation_preprocess(logger=None, df=object_)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_forecast_utilisation",
    glob_pattern="gbb_forecastutilisation*",
    schema={
        "State": String,
        "FacilityId": Int64,
        "FacilityName": String,
        "FacilityType": String,
        "ReceiptLocationId": Int64,
        "ReceiptLocationName": String,
        "DeliveryLocationId": Int64,
        "DeliveryLocationName": String,
        "Description": String,
        "ForecastMethod": String,
        "ForecastedFrom": String,
        "ForecastDate": String,
        "ForecastDay": String,
        "Units": String,
        "ForecastValue": String,
        "Nameplate": Float64,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "State": "Name of the state.",
        "FacilityId": "A unique AEMO defined facility identifier.",
        "FacilityName": "The name of the BB facility.",
        "FacilityType": "Facility type associated with the facility id.",
        "ReceiptLocationId": "Connection Point Id for the receipt location.",
        "ReceiptLocationName": "Connection Point name for the receipt location.",
        "DeliveryLocationId": "Connection Point Id for the delivery location.",
        "DeliveryLocationName": "Connection Point name for the delivery location.",
        "Description": "Describes the calculation in each row.",
        "ForecastMethod": "Describes the calculation for each BB pipeline.",
        "ForecastedFrom": "Date forecasts were created from",
        "ForecastDate": "Date forecasted for a given period",
        "ForecastDay": "Day+N description for forecast period",
        "Units": "The unit of measure for the calculated values.",
        "ForecastValue": "Value forecasted",
        "Nameplate": "Standing nameplate capacity quantity in TJ.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    bronze_postprocess_object_hooks=[ForecastUtilisationUnpivotHook()],
    surrogate_key_sources=[
        "State",
        "FacilityId",
        "FacilityName",
        "FacilityType",
        "ReceiptLocationId",
        "ReceiptLocationName",
        "DeliveryLocationId",
        "DeliveryLocationName",
        "Description",
        "ForecastMethod",
        "Units",
        "ForecastDay",
        "ForecastDate",
    ],
    group_name="gas_raw",
    deps=[
        AssetSpec(
            ["bronze", "gbb", "bronze_nemweb_public_files_gbb_forecast_utilization"]
        )
    ],
    description=(
        "7-day forecast utilisation outlook for East Coast supply-demand balance. "
        "GASBB_FORECAST_UTILISATION_NEXT7 is updated daily."
    ),
)
