from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_participants_list",
    glob_pattern="gasbbparticipants*",
    schema={
        "CompanyName": String,
        "CompanyId": Int64,
        "OrganisationTypeName": String,
        "ABN": String,
        "CompanyPhone": String,
        "Locale": String,
        "LastUpdated": String,
        "AddressType": String,
        "Address": String,
        "State": String,
        "Postcode": String,
        "CompanyFax": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "CompanyName": "Company name associated with the person.",
        "CompanyId": "Company ID associated with the person.",
        "OrganisationTypeName": "The type of organisation.",
        "ABN": "Australian Business Number for the participant.",
        "CompanyPhone": "Company phone details.",
        "Locale": "Location for the participant.",
        "LastUpdated": "Last changed details.",
        "AddressType": "Type of address.",
        "Address": "Mailing address for the company.",
        "State": "State where the company is located.",
        "Postcode": "Postcode details.",
        "CompanyFax": "Company fax details.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["CompanyId"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="List of registered participants in the Gas Bulletin Board system. Updated daily.",
)
