from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_short_term_capacity_outlook",
    glob_pattern="gasbbshorttermcapacityoutlook*",
    schema={
        "GasDate": String,
        "FacilityId": Int64,
        "FacilityName": String,
        "CapacityType": String,
        "CapacityTypeDescription": String,
        "OutlookQuantity": Float64,
        "FlowDirection": String,
        "CapacityDescription": String,
        "ReceiptLocation": Int64,
        "DeliveryLocation": Int64,
        "ReceiptLocationName": String,
        "DeliveryLocationName": String,
        "Description": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "GasDate": "Date of gas day.",
        "FacilityId": "A unique AEMO defined Facility Identifier.",
        "FacilityName": "The name of the BB facility.",
        "CapacityType": "STORAGE or MDQ.",
        "CapacityTypeDescription": "Description of the capacity type.",
        "OutlookQuantity": "Capacity outlook quantity to 3 decimal places.",
        "FlowDirection": "RECEIPT, DELIVERY, PROCESSED, or DELIVERYLNGSTOR.",
        "CapacityDescription": "Free text describing the capacity number.",
        "ReceiptLocation": "Connection Point ID for receipt location.",
        "DeliveryLocation": "Connection Point ID for delivery location.",
        "ReceiptLocationName": "Description of the Receipt Location.",
        "DeliveryLocationName": "Description of the Delivery Location.",
        "Description": "Comments about quantity or changes.",
        "LastUpdated": "Timestamp of last modification.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "GasDate",
        "FacilityId",
        "FlowDirection",
        "ReceiptLocation",
        "DeliveryLocation",
        "LastUpdated",
    ],
    group_name="gas_raw",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
    ],
    description=(
        "Expected daily capacity of a BB facility for the next seven days. "
        "Historical outlooks updated daily; future data updated within 30 minutes."
    ),
)
