from dagster import AssetSpec
from polars import Datetime, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_short_term_swap_transactions",
    glob_pattern="gasbbshorttermswaptransactions*",
    schema={
        "PeriodID": String,
        "State": String,
        "Quantity (TJ)": String,
        "VolumeWeightedPrice ($)": String,
        "TransactionType": String,
        "SupplyPeriodStart": String,
        "SupplyPeriodEnd": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "PeriodID": "Swap period",
        "State": "state for the swap",
        "Quantity (TJ)": "quantity in TJ",
        "VolumeWeightedPrice ($)": "volume weighted price",
        "TransactionType": "swap transaction type",
        "SupplyPeriodStart": "supply period start of swap",
        "SupplyPeriodEnd": "supply period end of swap",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "PeriodID",
        "State",
        "TransactionType",
        "SupplyPeriodStart",
        "SupplyPeriodEnd",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description=(
        "Short term gas swap transactions for each state/territory. "
        "VIC and QLD updated weekly; others updated monthly."
    ),
)
