from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

# Note: The legacy configuration included a custom anti-join post-process hook
# (medium_term_capacity_anti_join_postprocess) that referenced dead legacy modules.
# This is intentionally omitted: the silver layer's surrogate_key-based anti-join
# already handles deduplication of overlapping historical data.

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_medium_term_capacity_outlook",
    glob_pattern="gasbbmediumtermcapacityoutlook*",
    schema={
        "FacilityId": Int64,
        "FacilityName": String,
        "FromGasDate": String,
        "ToGasDate": String,
        "CapacityType": String,
        "OutlookQuantity": Float64,
        "FlowDirection": String,
        "CapacityDescription": String,
        "ReceiptLocation": Int64,
        "DeliveryLocation": Int64,
        "ReceiptLocationName": String,
        "DeliveryLocationName": String,
        "Description": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "FacilityId": "Unique plant identifier.",
        "FacilityName": "Name of the plant.",
        "FromGasDate": "Start gas day date.",
        "ToGasDate": "End gas day date.",
        "CapacityType": "STORAGE or MDQ.",
        "OutlookQuantity": "Capacity outlook quantity in TJ.",
        "FlowDirection": "Gas flow direction: RECEIPT, DELIVERY, PROCESSED, DELIVERYLNGSTOR.",
        "CapacityDescription": "Free text describing the capacity number.",
        "ReceiptLocation": "Connection Point Id for receipt location.",
        "DeliveryLocation": "Connection Point Id for delivery location.",
        "ReceiptLocationName": "The name of the receipt location.",
        "DeliveryLocationName": "The name of the delivery location.",
        "Description": "Comments about the quantity or change.",
        "LastUpdated": "Date and time record was last modified.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "FromGasDate",
        "ToGasDate",
        "FacilityId",
        "CapacityType",
        "FlowDirection",
        "ReceiptLocation",
        "DeliveryLocation",
        "LastUpdated",
    ],
    group_name="gas_raw",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb_duplicate"]),
    ],
    description=(
        "Capacity Outlook for the medium term. "
        "Full list updated daily; future outlooks updated within 30 minutes of new data."
    ),
)
