from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_field_interest_v2",
    glob_pattern="gasbbgasfieldinterest*",
    schema={
        "FieldName": String,
        "FieldInterestId": Int64,
        "CompanyId": Int64,
        "CompanyName": String,
        "GroupMembers": String,
        "PercentageShare": String,
        "EffectiveDate": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "FieldName": "The name of the Field in which the Field Interest is located.",
        "FieldInterestId": "A unique AEMO defined Field Interest Identifier.",
        "CompanyId": "The company ID of the responsible participant.",
        "CompanyName": "The company name of the responsible participant.",
        "GroupMembers": "The name of the group member.",
        "PercentageShare": "The BB field interest as a percentage of each member.",
        "EffectiveDate": "The date on which the record takes effect.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["FieldInterestId", "CompanyId", "EffectiveDate"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="Field Interest information (v2). Updated daily.",
)
