from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_uncontracted_capacity",
    glob_pattern="gasbbuncontractedcapacity*",
    schema={
        "FacilityId": Int64,
        "FacilityName": String,
        "FacilityType": String,
        "OutlookMonth": Int64,
        "OutlookYear": Int64,
        "CapacityType": String,
        "OutlookQuantity": Float64,
        "FlowDirection": String,
        "CapacityDescription": String,
        "ReceiptLocation": Int64,
        "ReceiptLocationName": String,
        "DeliveryLocation": Int64,
        "DeliveryLocationName": String,
        "Description": String,
        "LastUpdated": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "FacilityId": "Unique plant identifier.",
        "FacilityName": "Name of the plant.",
        "FacilityType": "Facility type associated with the Facility Id.",
        "OutlookMonth": "The month that the uncontracted capacity is available.",
        "OutlookYear": "The year that the uncontracted capacity is available.",
        "CapacityType": "Storage or MDQ.",
        "OutlookQuantity": "Daily average quantity across the month in TJ.",
        "FlowDirection": "RECEIPT or DELIVERY.",
        "CapacityDescription": "Free text describing the capacity number.",
        "ReceiptLocation": "Connection Point Id for receipt location.",
        "ReceiptLocationName": "The name of the receipt location.",
        "DeliveryLocation": "Connection Point Id for delivery location.",
        "DeliveryLocationName": "The name of the delivery location.",
        "Description": "Comments about the quantity or change.",
        "LastUpdated": "Date and time record was last modified.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "FacilityId",
        "OutlookMonth",
        "OutlookYear",
        "CapacityType",
        "FlowDirection",
        "ReceiptLocation",
        "DeliveryLocation",
        "FacilityType",
        "LastUpdated",
    ],
    group_name="gas_raw",
    deps=[
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"]),
        AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb_duplicate"]),
    ],
    description=(
        "Uncontracted primary firm capacity outlook for the next 36 months. "
        "Full list updated monthly."
    ),
)
