from dagster import AssetSpec
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_lng_shipments",
    glob_pattern="gasbblngshipments*",
    schema={
        "TransactionId": String,
        "FacilityId": Int64,
        "FacilityName": String,
        "VolumePJ": Float64,
        "ShipmentDate": String,
        "VersionDateTime": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "TransactionId": "Unique shipment identifier.",
        "FacilityId": "Unique facility identifier.",
        "FacilityName": "Name of the facility.",
        "VolumePJ": "Volume of the shipment in PJ.",
        "ShipmentDate": "Departure or unloading commencement date.",
        "VersionDateTime": "Time a successful submission is accepted by AEMO systems.",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["TransactionId", "FacilityId", "VersionDateTime"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="List of all LNG shipments. GASBB_LNG_EXPO_IMPO_SHIPMENTS is updated monthly.",
)
