from dagster import AssetSpec
from polars import Datetime, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_linepack_zones",
    glob_pattern="gasbblinepackzones*",
    schema={
        "Operator": String,
        "LinepackZone": String,
        "LinepackZoneDescription": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "Operator": "Operator of linepack zone",
        "LinepackZone": "Linepack Zone",
        "LinepackZoneDescription": "Description of Linepack Zone",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=["Operator", "LinepackZone"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="List of operator to linepack zones with descriptions.",
)
