from dagster import AssetSpec
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="gbb",
    name_suffix="gasbb_demand_zones_and_pipeline_connectionpoint_mapping",
    glob_pattern="gasbbdemandzonespipelineconnectionpointmapping*",
    schema={
        "FacilityName": String,
        "FacilityType": String,
        "FacilityId": Int64,
        "NodeId": Int64,
        "ConnectionPointId": Int64,
        "FlowDirection": String,
        "ConnectionPointName": String,
        "State": String,
        "DemandZone": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "FacilityName": "Name of the facility.",
        "FacilityType": "The facility development type.",
        "FacilityId": "The gas storage facility ID.",
        "NodeId": "A unique AEMO defined node identifier.",
        "ConnectionPointId": "A unique AEMO defined connection point identifier.",
        "FlowDirection": "Gas flow direction: RECEIPT, DELIVERY, PROCESSED, DELIVERYLNGSTOR.",
        "ConnectionPointName": "Names of the connection point.",
        "State": "The state where the transaction occurred.",
        "DemandZone": "",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    surrogate_key_sources=[
        "FacilityId",
        "NodeId",
        "ConnectionPointId",
        "FlowDirection",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "gbb", "bronze_nemweb_public_files_gbb"])],
    description="Mapping between pipelines, connection points and demand zones.",
)
