from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int037c_v4_indicative_price_1",
    glob_pattern="int037c_v4_indicative_price_1*",
    schema={
        "demand_type_name": String,
        "price_value_gst_ex": Float64,
        "transmission_group_id": Int64,
        "schedule_type_id": String,
        "transmission_id": Int64,
        "gas_date": String,
        "approval_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "demand_type_name": "Normal Uses Demand forecast used by operational schedule",
        "price_value_gst_ex": "Forecast market price ($) for BoD Scheduling horizon of the gas day in question",
        "transmission_group_id": "Link to the related day(s) ahead operational schedule",
        "schedule_type_id": "OS (Operating Schedule Id)",
        "transmission_id": "Schedule number these prices are related to",
        "gas_date": "e.g. 30 Jun 2007",
        "approval_datetime": "Date and time the schedule was approved 29 Jun 2007 01:23:45",
        "current_date": "Date and time the report is produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to indicate what the prices are for the day and what they are
        predicted to be for the next two days. Market participants may wish to use this
        information to estimate pricing for the following two days. This report is
        produced after the approval of each schedule. The report has the actual price
        information of each operating schedule, as well as forecast process for the day
        ahead schedules published. This means that on any given gas day the report is
        published: - 5 times for Day+0 after each of the 5 market schedules which
        reflects actual price that applies for each scheduling horizon. - 3 times for
        Day+1 which includes the estimated BoD price. - Once for Day+2 which includes
        the estimated BoD price. Participants can use this report to review the outcomes
        of the current day and to reflect on the options to adjust their positions for
        the coming days.
    """).strip("\n"),
    surrogate_key_sources=["demand_type_name", "transmission_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
