from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int041_v4_market_and_reference_prices_1",
    glob_pattern="int041_v4_market_and_reference_prices_1*",
    schema={
        "gas_date": String,
        "price_bod_gst_ex": Float64,
        "price_10am_gst_ex": Float64,
        "price_2pm_gst_ex": Float64,
        "price_6pm_gst_ex": Float64,
        "price_10pm_gst_ex": Float64,
        "imb_wtd_ave_price_gst_ex": Float64,
        "imb_inj_wtd_ave_price_gst_ex": Float64,
        "imb_wdr_wtd_ave_price_gst_ex": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day for the reference prices e.g. 30 Jun 2007",
        "price_bod_gst_ex": "Beginning of day (BoD) ex ante price.",
        "price_10am_gst_ex": "10:00 AM schedule ex ante price",
        "price_2pm_gst_ex": "2:00 PM schedule ex ante price",
        "price_6pm_gst_ex": "6:00 PM schedule ex ante price",
        "price_10pm_gst_ex": "10:00 PM schedule ex ante price",
        "imb_wtd_ave_price_gst_ex": "Imbalance weighted average daily price",
        "imb_inj_wtd_ave_price_gst_ex": "Injection imbalance weighted average daily price",
        "imb_wdr_wtd_ave_price_gst_ex": "Withdrawal imbalance weighted average daily price",
        "current_date": "Date and Time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to provide a clear picture of the actual market ex ante prices
        and calculated reference prices across a gas day used for settling the Declared
        Wholesale Gas Market. Therefore the market prices reported will use any
        administered price in place of the market price in this report. Effectively
        average daily prices are also inclusive of any administered prices. To view the
        market price determined by AEMO's market schedule please see INT037b, INT235 or
        INT310. Participants may wish to use this report to track an average daily price
        of gas over time. It may also be possible to use these prices as strike prices
        in off market hedge contracts that may develop over time. Note the average
        prices are not used for settling the market, only the prices set for each
        scheduling horizon are used in the settlement of a gas day. This report is
        produced after each last approved pricing schedule for the day and shows the
        data over a 14-day rolling period. Each report will contain a price for each of
        the 5 pricing schedules for the day and also include 3 forms of average daily
        pricing: - imbalance weighted average daily price - injection imbalance weighted
        average daily price - withdrawal imbalance weighted average daily price
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
