from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int091_v4_eddact_1",
    glob_pattern="int091_v4_eddact_1*",
    schema={
        "edd_update": String,
        "edd_date": String,
        "edd_value": Float64,
        "edd_type": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "edd_update": "Date and time value derived e.g. 27 Sep 2007 14:31:00",
        "edd_date": "Actual EDD date (event date) (e.g. 30 Jun 2007)",
        "edd_value": "EDD value",
        "edd_type": "=1 Billing EDD, used in BMP for generating consumed energy values and remains based on the 9-9 time period, even though the gas day is 6-6",
        "current_date": "Time Report Produced (e.g. 30 Jun 2007 06:00:00) Time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the Effective Degree Day (EDD) as calculated for a gas day
        in AEMO's settlements processing. This settlements EDD value is used in the
        generation of energy values used by AEMO to settle the wholesale market. Gas
        distributors and retailers use the information in this report to derive an
        average EDD figure for use in their own routines to estimate end-use customers'
        consumption where no actual read is available for a basic meter. The Victorian
        Retail Market Procedures prescribes AEMO requirement to publish the EDD (see
        section 2.8.2), how AEMO calculates the EDD (see attachment 6 section 3) and
        the use of this EDD value when generating an estimated meter reading (see
        attachment 4). The reported EDD is an actual EDD (i.e. Based on actual weather
        observations rather than weather forecasts) and is calculated for a 9-9 time
        period rather than a 6-6 gas day. This report is generated daily. Each report
        provides a historical record of actual EDD for a rolling 2 calendar month
        period ending on the day before the report date. Each row in the report provides
        the billing EDD for the specified edd_date. Since actual EDD is calculated on
        actual weather observations, the latest possible EDD available is for the
        previous full day. This means that actual EDD is always published (at least) 1
        day in arrears.
    """).strip("\n"),
    surrogate_key_sources=["edd_update", "edd_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
