from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int089_v4_linepack_balance_1",
    glob_pattern="int089_v4_linepack_balance_1*",
    schema={
        "gas_date": String,
        "total_imb_pmt": Float64,
        "total_dev_pmt": Float64,
        "linepack_acct_pmt_gst_ex": Float64,
        "linepack_acct_bal_gst_ex": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported e.g. 30 Jun 2007 06:00:00",
        "total_imb_pmt": "Sum of imbalance payments for the gas day (across all scheduling intervals) credit or debit amount ($)",
        "total_dev_pmt": "Sum of deviation payments for the gas day (across all scheduling intervals credit or debit amount ($)",
        "linepack_acct_pmt_gst_ex": "Credit or debit amount ($) to AEMO's linepack account = total_imbal_pmts + total_dev_pmts",
        "linepack_acct_bal_gst_ex": "Sum (linepack_acct_pmts for month) progressive total, accumulating from beginning of month to the end of the month",
        "current_date": "Date and Time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This month-to-date report is to provide an ongoing perspective of the total
        markets liability to linepack account payments or receipts. The amount reported
        is accumulated during the month and then paid out (in credit or debit) based on
        the participant consumption during the month. This amount effectively cashes out
        inter day movements in system linepack and smears the impact of unallocated gas
        in the market (due to things like measurement error). This account balance is
        based on provisional meter data and is subject to change at settlement time. A
        report is produced daily after 3 business days of the actual gas date. The
        report is used as part of the pre-processing step for settlements whereby
        participants may wish to use this report as an indication against liability of
        their linepack account. Each report contains a row for each gas day which shows
        the: - total imbalance payment - total deviation payment - linepack account
        payment - linepack account balance - date and time when the report was produced.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
