from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int117a_v4_est_ancillary_payments_1",
    glob_pattern="int117a_v4_est_ancillary_payments_1*",
    schema={
        "gas_date": String,
        "schedule_no": Int64,
        "est_ancillary_amt_gst_ex": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Format: dd mmm yyyy hh:mm (e.g. 15 Feb 2007 06:00)",
        "schedule_no": "Schedule number associated with the scheduling horizon (i.e. 1 = 6:00 AM to 6:00 AM, 2 = 10:00 AM to 6:00 AM)",
        "est_ancillary_amt_gst_ex": "Total Estimated Ancillary Payment (can be positive or negative) for a schedule",
        "current_date": "Time Report Produced (e.g. 30 Jun 2007 01:23:45)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is a public version of INT116a. It provides the estimated ancillary
        payments for the total gas market but does not take into account Actual Gas
        Injected Negative Offset (AGINO) and Actual Gas Withdrawal Negative Offset
        (AGWNO) quantities. That is it is produced at the operational schedule time and
        is not adjusted for actual metered values, and is therefore likely to differ
        from the final settlement total. Participants may use this report to compare
        their estimated ancillary payments (from INT116a) in the context of the whole
        gas market. This is a public report containing ancillary payments from the
        beginning of the previous month and is produced after each schedule. This report
        does not take into account AP Clawback. The ancillary payment amount can be
        positive or negative depending on the total estimated ancillary payment for the
        schedule. The number of rows in this report is dependent on the time of the
        month when this report is produced.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "schedule_no"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
