from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int139_v4_declared_daily_state_heating_value_1",
    glob_pattern="int139_v4_declared_daily_state_heating_value_1*",
    schema={
        "gas_date": String,
        "declared_heating_value": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported (e.g. 30 Jun 2007)",
        "declared_heating_value": "Declared daily state heating value\n Sum(h,z [HV(z,h) *(CF(z,h)) ])/Sum(h,z (CF(h,z))\n h= hour index\n z=zone index\n CF Corrected flow\n HV Heating Value",
        "current_date": "Date and time report produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the declared daily state heating value (HV) which is used
        by gas retailers and distribution businesses in their billing processes, to
        convert the difference in (actual or estimated) index readings from basic meters
        to energy consumption figures. The use of this state wide declared heating value
        is prescribed in the Victorian Distribution system code issued by the Essential
        Services Commission of Victoria. Section 2.6.1 (b) of the Victorian Retail
        Market Procedures describes AEMO's obligation to publish the daily state heating
        value and the obligation that the Distributor must use this value to calculate
        the average heating value for a reading period. The reported values are the
        volume-weighted average HVs of all Victoria's heating value zones. Note the
        values in this report are not normally subject to revision. Each report displays
        the daily state HV for the previous 90 days (not including the current gas
        day). Note: This report is decommissioned from December 2024.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
