from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int128_v4_actual_linepack_1",
    glob_pattern="int128_v4_actual_linepack_1*",
    schema={
        "commencement_datetime": String,
        "actual_linepack": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "commencement_datetime": "Commencement date and time (e.g. 25 Apr 2007 1:00:00)",
        "actual_linepack": "Energy value representing the physical linepack",
        "current_date": "Date and time report produced (e.g. 30 Jun 2007 01:23:56)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides information on changes in physical linepack over a 3-day
        period, and can be used by Participants as an input into their forecasting and
        trading activities. Note the information in this report is derived from
        real-time gas pressure data and does not relate to the scheduled linepack
        values, as the scheduled linepack is a relative value. It is also important to
        recognise that this report contains details about the system's physical linepack
        and is not the settlement linepack, which is a financial balancing concept not
        related in any way to the physical linepack in the system on each day.
        Participants may use this report to make assumptions about the physical
        capabilities of the system when correlated with weather, type of day and other
        variables that impact on demand. Each report provides hourly linepack quantities
        for the current and previous 2 gas days. Reports are produced as operational
        schedules are approved, with information about the linepack movements for the
        current gas day becoming progressively more complete in the course of the day.
    """).strip("\n"),
    surrogate_key_sources=["commencement_datetime"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
