from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int112c_v4_ssc_1",
    glob_pattern="int112c_v4_ssc_1*",
    schema={
        "supply_source": String,
        "gas_date": String,
        "ssc_id": Int64,
        "ti": Int64,
        "hourly_constraint": Int64,
        "mod_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "supply_source": "Name of the constrained supply source",
        "gas_date": "Dates that mark the boundary of the application of the constraint (e.g. 27 Jun 2011)",
        "ssc_id": "Id of the Constraint",
        "ti": "Time interval 1-24 (hour of the gas day)",
        "hourly_constraint": "1 value for each hour of the gas day, Set to 1 if hourly constraint is applied. 0 if hourly constraint has not been applied",
        "mod_datetime": "Creation/modification time stamp (e.g. 07 Jun 2011 08:01:23)",
        "current_date": "Date and time the report was produced (e.g. 30 Jun 2011 1:23:56)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains information regarding any supply and demand point
        constraints (SDPCs) that are current in the scheduling processes used in the
        DTS. These constraints are part of the configuration of the network that can be
        manually set by the AEMO Schedulers and form one of the inputs to the schedule
        generation process. This report contains supply point constraints, which
        selectively constrain injection bids at system injection points where the
        facility operator has registered multiple supply sources. Traders can use this
        information to understand the network-based restrictions that will constrain
        their ability to offer or withdraw gas in the market on a given day. A report is
        produced each time an operational schedule (OS) is approved by AEMO. Therefore
        it is expected that each day there will be at least 9 of these reports issued.
        Each report contains details of the SSCs that have applied to schedules
        previously run: - on the previous gas day - for the current gas day - for the
        next 2 gas days. Each SSC has a unique identifier and applies to a single
        injection MIRN. Each row in the report contains details of one SSC for one hour
        of the gas day. This report will contain 24 rows for each SSC for each gas day
        reported.
    """).strip("\n"),
    surrogate_key_sources=["supply_source", "gas_date", "ti"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
