from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int112b_v4_nftc_1",
    glob_pattern="int112b_v4_nftc_1*",
    schema={
        "nftc_name": String,
        "commencement_date": String,
        "termination_date": String,
        "daily_max_net_inj_qty_gj": Int64,
        "daily_max_net_wdl_qty_gj": Int64,
        "ti": Int64,
        "hourly_max_net_inj_qty_gj": Int64,
        "hourly_max_net_wdl_qty_gj": Int64,
        "mod_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "nftc_name": "Name of the Net Flow Transportation Constraint",
        "commencement_date": "e.g. 27 Jun 2011. Dates that mark the boundary of the application of the constraint",
        "termination_date": "e.g. 27 Jun 2011. Dates that mark the boundary of the application of the constraint",
        "daily_max_net_inj_qty_gj": "The aggregate maximum daily injection limit in gigajoules applied by this constraint",
        "daily_max_net_wdl_qty_gj": "The aggregate maximum daily withdrawal limit in gigajoules applied by this constraint",
        "ti": "Time interval 1-24 (hour of the gas day)",
        "hourly_max_net_inj_qty_gj": "1 value for each hour of the gas day",
        "hourly_max_net_wdl_qty_gj": "1 value for each hour of the gas day",
        "mod_datetime": "NFTC creation/modification time stamp e.g. 07 Jun 2011 08:01:23",
        "current_date": "Date and time the report was produced",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains information on group directional flow point constraints
        (DFPCs) pertaining to the DTS. Grouped directional flow points are those points
        in the DTS where multiple injections and withdrawals can occur. This report
        contains flow constraints for a group of meters typically at the same location.
        NFTCs are part of the configuration of the network that can be manually changed
        by the AEMO Schedulers, and form one of the inputs to the schedule generation
        process. Traders can use this information to understand the network-based
        restrictions that will constrain their ability to offer gas to the market on a
        given day in the reporting window. (See Also INT112)
    """).strip("\n"),
    surrogate_key_sources=["nftc_name", "commencement_date", "ti"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
