from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int112_v4_dfpc_1",
    glob_pattern="int112_v4_dfpc_1*",
    schema={
        "dfpc_id": Int64,
        "injection_mirn": String,
        "withdrawal_mirn": String,
        "commencement_date": String,
        "termination_date": String,
        "daily_max_net_inj_qty_gj": Int64,
        "daily_max_net_wdl_qty_gj": Int64,
        "ti": Int64,
        "hourly_max_net_inj_qty_gj": Int64,
        "hourly_max_net_wdl_qty_gj": Int64,
        "mod_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "dfpc_id": "Id of the Constraint",
        "injection_mirn": "Injection mirn",
        "withdrawal_mirn": "Withdrawal mirn paired to injection mirn",
        "commencement_date": "Dates that mark the boundary of the application of the constraint (e.g. 27 Jun 2006)",
        "termination_date": "Dates that mark the boundary of the application of the constraint (e.g. 27 Jun 2006)",
        "daily_max_net_inj_qty_gj": "Daily maximum net injection quantity in GJ",
        "daily_max_net_wdl_qty_gj": "Daily maximum net withdrawal quantity in GJ",
        "ti": "Time interval 1-24 (hour of the gas day)",
        "hourly_max_net_inj_qty_gj": "1 value for each hour of the gas day",
        "hourly_max_net_wdl_qty_gj": "1 value for each hour of the gas day",
        "mod_datetime": "DFPC creation/modification time stamp (e.g. 07 Jun 2006 08:01:23)",
        "current_date": "Date and time the report was produced (e.g. 30 Jun 2005 1:23:56)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains information on the directional flow point constraints
        (DFPCs) pertaining to the DTS. Directional flow points are those points in the
        DTS where both injections and withdrawals can occur, and the key item of
        interest is the NET movement of gas. DFPCs are part of the configuration of the
        network that can be manually changed by the AEMO Schedulers, and form one of
        the inputs to the schedule generation process. Traders can use this information
        to understand the network-based restrictions that will constrain their ability
        to offer gas to the market on a given day in the reporting window. A report is
        produced each time an operational schedule (OS) is approved by AEMO. Therefore,
        it is expected that each day there will be at least 9 of these reports issued:
        - 5 being for the standard current gas day schedules - 3 being for the standard
        1-day ahead schedules - 1 being for the standard 2 days ahead schedule. Each
        DFPC has a unique identifier and applies to a single pair of MIRNs (an
        injection MIRN and a withdrawal MIRN). Each row in the report contains details
        of one DFPC for one hour of the gas day. This report will contain 24 rows for
        each DFPC for each gas day reported.
    """).strip("\n"),
    surrogate_key_sources=["dfpc_id", "ti"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
