from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int139a_v4_daily_zonal_heating_1",
    glob_pattern="int139a_v4_daily_zonal_heating_1*",
    schema={
        "gas_date": String,
        "hv_zone": Int64,
        "hv_zone_desc": String,
        "heating_value": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Starting hour of gas day being reported, example: 30 Jun 2007",
        "hv_zone": "Heating value zone number as assigned by the AEMO. Values for Victoria can be in the range of 400-699",
        "hv_zone_desc": "Heating value zone name",
        "heating_value": "Daily volume flow weighted average heating value (GJ/1000 m(3)) to two decimal places",
        "current_date": "Date and time report is produced. Example: 30 Jun 2007 06:00:00",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        A report providing the heating value for each heating value zone used to
        determine the energy content of gas consumed within Victoria. This is consistent
        with the Energy Calculation Procedures. The daily zonal heating value
        calculation is expected to be triggered at approximately 9:30AM each day. The
        reported values are the volume-weighted average HVs of each of Victoria's
        heating value zones. The values in this report may be subject to revision by
        AEMO. This report contains heating values zones for DTS connected DDS and
        non-DTS connected DDS (non-DTS Bairnsdale, non-DTS South Gippsland, and
        non-DTS Grampians regions). Each report displays the daily volume weighted
        average HV for each heating value zone in Victoria over the previous 90 gas
        days (not including the current gas day). The HV is always published one day in
        arrears.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "hv_zone"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
