from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int125_v8_details_of_organisations_1",
    glob_pattern="int125_v8_details_of_organisations_1*",
    schema={
        "company_id": Int64,
        "company_name": String,
        "registered_name": String,
        "acn": String,
        "abn": String,
        "organization_class_name": String,
        "organization_type_name": String,
        "organization_status_name": String,
        "line_1": String,
        "line_2": String,
        "line_3": String,
        "province_id": String,
        "city": String,
        "postal_code": String,
        "phone": String,
        "fax": String,
        "market_code": String,
        "company_code": String,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "company_id": "Identifying organisation's id",
        "company_name": "Participant organisation name",
        "registered_name": "Participant organisation registered name",
        "acn": "ACN details of each Market participant",
        "abn": "ABN details of each Market participant",
        "organization_class_name": "Either Non-Participant or Participant or Market-Participant",
        "organization_type_name": "Bank, Producer, Distributor, Retailer",
        "organization_status_name": "Either New Status or Applicant Status",
        "line_1": "Address details",
        "line_2": "Address details",
        "line_3": "Address details",
        "province_id": "State",
        "city": "City",
        "postal_code": "Postal code",
        "phone": "Phone number",
        "fax": "Fax number",
        "market_code": "The code representing the gas market that the Market participant operates in",
        "company_code": "The company code used by Market participants to send B2B transactions and receive MIBB/GASBB reports",
        "current_date": "Date and Time Report Produced (e.g. 30 June 2005 1:23:56)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is a public listing of all the registered Market participants. A
        report is produced daily at 09:00 hrs AEST. Each report contains the: company
        id and name; organisation class, type and status; province id; address and
        contact numbers; the initial registration of a company in gas market systems
        which determines the organisation type for that company. For market code STTM:
        Organisation type name of Producer should be interpreted as STTM Injection
        Facility, STTM Net Metered Facility, or STTM Aggregation Facility; Declared
        Transmission System Service Provider as STTM Pipeline Operator; Allocation
        Agent should be interpreted as a Shipper who is registered as a sub allocation
        agent in the STTM. The market_code field represents the gas market that the
        Market participant operates in: NATGASBB, NSWACTGAS, QLDGAS, SAGAS, STTM,
        VICGAS, VICGASW.
    """).strip("\n"),
    surrogate_key_sources=["company_id", "market_code"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
