from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int150_v4_public_metering_data_1",
    glob_pattern="int150_v4_public_metering_data_1*",
    schema={
        "gas_date": String,
        "flag": String,
        "id": String,
        "ti": Int64,
        "energy_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported e.g. as 30 Jun 1998",
        "flag": "WTHDL - int92 withdrawals, INJ - integer 98 injections",
        "id": "Meter registration number or withdrawal zone name",
        "ti": "Trading interval (1-24), where 1= 6:00 AM to 7:00 AM, 2= 7:00 AM to 8:00 AM, until the 24th interval",
        "energy_gj": "Energy value (GJ) (not adjusted for UAFG)",
        "current_date": "Time report produced",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This public report contains metering data grouped by withdrawal zone and
        injection point for the previous 2 months. This report provides an industry
        overview of what is happening across the system (for example, quantity of
        energy flow and injected). This report can be used by Participants to estimate
        their settlement exposure to the market. Participants should however be aware
        that the data is provisional and can change at settlement. Participants should
        also be aware that this meter data is what is used by AEMO when prudential
        processing is done to assess each Market participants exposure to the market and
        the likelihood of a margin call being required. It should be noted that this
        data is likely to have a proportion generated from substitutions and estimates
        and should only be used as a guide to the demand on that day. A report is
        produced three business days after the gas date.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "flag", "id", "ti"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
