from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int199_v4_cumulative_price_1",
    glob_pattern="int199_v4_cumulative_price_1*",
    schema={
        "transmission_id": Int64,
        "gas_date": String,
        "schedule_interval": Int64,
        "cumulative_price": Float64,
        "cpt_exceeded_flag": String,
        "schedule_type_id": String,
        "transmission_doc_id": Int64,
        "approval_datetime": String,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "transmission_id": "Schedule Id - Unique identifier associated with each schedule",
        "gas_date": "Gas day of schedule. format dd mmm yyy e.g. 30 Jun 2008",
        "schedule_interval": "Schedule interval (1=6:00 AM, 2=10:00 AM, 3=2:00 PM, 4=6:00 PM, 5=10:00 PM)",
        "cumulative_price": "Rolling cumulative price from MCP's from previous Y-1 LAOS and next FAOS",
        "cpt_exceeded_flag": "'Y' when CP >= CPT, otherwise 'N'",
        "schedule_type_id": "OS (Operating Schedule Id)",
        "transmission_doc_id": "Run Id",
        "approval_datetime": "Date and time the schedule was approved 29 Jun 2007 01:23:45",
        "current_date": "Current report run date time. Format dd Mmm yyyy hh:mi:ss e.g. 15 May 2008 12:22:12",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        Interface 199 (INT199) is an Event-Triggered report published on the Market
        Information Bulletin Board (MIBB). This report must provide by scheduling
        interval by gas day the cumulative price (CP) and a flag to indicate when CP is
        greater than or equal to the threshold (CPT). The report is produced on approval
        of a current gas day operating/pricing schedules with start time equal to the
        commencement of each scheduling interval. Ad hoc operating reschedules during a
        scheduling interval are included in the determination of MCP's for previous
        scheduling intervals, but do not themselves trigger the report. Whilst bid
        information is public and this can be estimated by the public, actual scheduling
        information by bid is still regarded as confidential by Market participants.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "schedule_interval"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
