from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int152_v4_sched_min_qty_linepack_1",
    glob_pattern="int152_v4_sched_min_qty_linepack_1*",
    schema={
        "gas_date": String,
        "type": String,
        "linepack_id": Int64,
        "linepack_zone_id": Int64,
        "commencement_datetime": String,
        "ti": Int64,
        "termination_datetime": String,
        "unit_id": String,
        "linepack_zone_name": String,
        "transmission_document_id": Int64,
        "quantity": Int64,
        "current_date": String,
        "approval_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day (e.g. 30 Jun 2007)",
        "type": "LPMIN for INT046, LPSCHED for INT115",
        "linepack_id": "Linepack identifier",
        "linepack_zone_id": "Linepack zone identifier (Null for LPSCHED)",
        "commencement_datetime": "Format: dd mon yyy hh:mm:ss",
        "ti": "Applicable to LPSCHED only, null for LPMIN. 0-24. 0 means linepack at start of schedule. Ie 5:59am 1-24 represents the time interval of the day.",
        "termination_datetime": "Format: dd mon yyyy hh:mm:ss",
        "unit_id": "GJ",
        "linepack_zone_name": "Name of linepack zone",
        "transmission_document_id": "Null for LPMIN",
        "quantity": "Quantity value",
        "current_date": "Date and time the report was produced: Format dd mon yyyy hh:mm:ss",
        "approval_date": "Date of approval (e.g. 30 Jun 2007)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides transparency into the system operation of the gas market,
        as required under clause 320 of the NGR. This report combines two different
        types of content: the end-of-day linepack minimum target (in GJ) set by AEMO
        as part of system operations; and the hourly linepack quantities scheduled for
        the gas day. Users should refer to INT108 (Schedule Run Log) to determine the
        characteristics of each schedule. As a report is generated each time an
        operational schedule is approved there will be at least 9 issues of INT152 each
        day. Each report shows the scheduled and minimum linepack quantities (in GJ) for
        the previous 7 gas days, current gas day, and next 2 gas days. For LPMIN rows,
        there is one row for the system linepack minimum for each gas day. For LPSCHED
        rows, there are 25 rows for each schedule where the start time is 06:00 AM, or
        26 rows otherwise.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "type", "linepack_id", "commencement_datetime"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
