from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int126_v4_dfs_data_1",
    glob_pattern="int126_v4_dfs_data_1*",
    schema={
        "dfs_version": Int64,
        "gas_date": String,
        "last_update_datetime": String,
        "previous_day_min": Float64,
        "max": Float64,
        "overnight_min": Float64,
        "average_wind_speed": Float64,
        "sunshine": Int64,
        "effective_temperature": Float64,
        "dfs_edd": Float64,
        "total_demand_forecast": Int64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "dfs_version": "Demand forecast version",
        "gas_date": "Gas Day date the temperature data applies to (e.g. 30 Jun 2007)",
        "last_update_datetime": "Time data obtained and loaded into AEMO's database (e.g. 05:00:00)",
        "previous_day_min": "Previous day over night minimum temperature (NULL from 15 April 2024)",
        "max": "Maximum temperature for day (NULL from 15 April 2024)",
        "overnight_min": "Overnight minimum temperature (NULL from 15 April 2024)",
        "average_wind_speed": "Average wind speed (knots) (NULL from 15 April 2024)",
        "sunshine": "Hours of sunshine (NULL from 15 April 2024)",
        "effective_temperature": "Effective temperature calculated by AEMO's Demand Forecasting System (DFS)",
        "dfs_edd": "Effective Degree Day (EDD) calculated by AEMO's Demand Forecasting System (DFS)",
        "total_demand_forecast": "AEMO's total daily demand forecast for the gas day calculated by AEMO's Demand Forecasting System (DFS)",
        "current_date": "Date and time report produced (e.g. 30 June 2005 1:23:56)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides AEMO's calculated effective temperature, effective degree
        day (EDD) and total system demand forecast (representing system demand and site
        specific demand) for the DWGM from AEMO's Demand Forecasting System (DFS). This
        data can be used to validate forecasting methodologies against AEMO's DFS. It
        is also used to validate AEMO's demand forecast where there has been a demand
        override in the scheduling process. Not every demand generated by the AEMO DFS
        is used in the scheduling process. Participants should reference INT108 Schedule
        Run Log to determine the Demand Forecasts used for each schedule. This report
        contains data for the current gas day, 1-day ahead, 2 days ahead, and the
        previous 7 days (up to 10 days total). From 15 April 2024, AEMO has a new
        weather forecast data provider and the following fields will be NULL:
        previous_day_min, max, overnight_min, average_wind_speed, sunshine.
    """).strip("\n"),
    surrogate_key_sources=["dfs_version", "gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
