from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int138_v4_settlement_version_1",
    glob_pattern="int138_v4_settlement_version_1*",
    schema={
        "statement_version_id": Int64,
        "settlement_cat_type": String,
        "version_from_date": String,
        "version_to_date": String,
        "interest_rate": Float64,
        "issued_date": String,
        "version_desc": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "statement_version_id": "Statement version identifier",
        "settlement_cat_type": "Type (e.g. FNL for Final, PLM for Preliminary)",
        "version_from_date": "Effective start date (e.g. 30 Jun 2007)",
        "version_to_date": "Effective end date (e.g. 30 Jun 2007)",
        "interest_rate": "Interest rate applied to the settlement",
        "issued_date": "Date issued (e.g. 30 Jun 2007)",
        "version_desc": "Description of the version",
        "current_date": "Date and time report produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to display recently issued settlement versions. Participants may
        wish to use this report as a reference to link other reports together based on
        settlement version. A report is produced publicly when settlement statement is
        issued. Each report contains the: statement version identifier, settlement
        category type, effective state date, effective end date, interest rate, date of
        issue, description of the version, date and time when the report was produced.
    """).strip("\n"),
    surrogate_key_sources=["statement_version_id", "version_from_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
