from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int117b_v4_ancillary_payments_1",
    glob_pattern="int117b_v4_ancillary_payments_1*",
    schema={
        "ap_run_id": Int64,
        "gas_date": String,
        "schedule_no": Int64,
        "ancillary_amt_gst_ex": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "ap_run_id": "Number identifying ancillary run",
        "gas_date": "Format: dd mmm yyyy hh:mm (e.g. 15 Feb 2007 06:00)",
        "schedule_no": "Schedule number",
        "ancillary_amt_gst_ex": "Total Ancillary Payment (can be positive or negative) for a schedule",
        "current_date": "Time Report Produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is a public version of INT116b. It shows the actual ancillary
        payments for the gas market by taking into account the Actual Gas Injected
        Negative Offset (AGINO) and Actual Gas Withdrawal Negative Offset (AGWNO)
        quantities, as well as the proportion of injections used to support an uplift
        hedge. Participants may wish to use this report to gauge their actual ancillary
        payments (from INT116b) in the context of the whole gas market. Participants
        should note that although the AGINO and AGWNO are included in the calculations
        for this report, the meter data used for this purpose is provisional data that
        may change at settlement. This a public report containing ancillary payments
        from the beginning of the previous month and is produced no later than the third
        business day after the gas day (D+3). The ancillary payment amount can be
        positive or negative.
    """).strip("\n"),
    surrogate_key_sources=["ap_run_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
