from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int258_v4_mce_nodes_1",
    glob_pattern="int258_v4_mce_nodes_1*",
    schema={
        "pipeline_id": Int64,
        "point_group_identifier_id": Int64,
        "point_group_identifier_name": String,
        "nodal_altitude": Int64,
        "last_mod_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "pipeline_id": "Pipeline identifier e.g. 1",
        "point_group_identifier_id": "Point group identifier e.g. 4",
        "point_group_identifier_name": "Point group identifier name e.g. Rosebud",
        "nodal_altitude": "Nodal altitude e.g. 37",
        "last_mod_date": "Time last modified e.g. 20 Jun 2001 16:42:35",
        "current_date": "Date and Time the report is produced e.g. 21 Jun 2001 16:42:35",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains the current MCE Nodes. This public report is produced each
        time a change occurs. It identifies nodes that the MCE uses. The nodal prices
        from MCE forms the network prices. Each report contains the: pipeline
        identifier, point group identifier and name, nodal altitude, last modified date,
        and date and time when the report was produced.
    """).strip("\n"),
    surrogate_key_sources=["pipeline_id", "point_group_identifier_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
