from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int287_v4_gas_consumption_1",
    glob_pattern="int287_v4_gas_consumption_1*",
    schema={
        "gas_date": String,
        "total_gas_used": String,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported (e.g. 30 Jun 2007)",
        "total_gas_used": "total gas used in gj",
        "current_date": "Date and Time Report Produced (e.g. 30 Jun 2007 01:23:45)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This public report shows the daily gas consumed at an operational level and
        therefore will have minor discrepencies due to metering substitutions or
        updates post the gas day
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
