from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int260_v4_compressor_char_1",
    glob_pattern="int260_v4_compressor_char_1*",
    schema={
        "compressor_id": Int64,
        "compressor_name": String,
        "pipe_segment_id": Int64,
        "min_pressure_delta": Float64,
        "most_efficient_pressure_delta": Float64,
        "max_pressure_delta": Float64,
        "max_compressor_power": Float64,
        "min_compressor_power": Float64,
        "compressor_efficiency": Float64,
        "compressor_efficiency_at_min": Float64,
        "efficiency_coefficient": Float64,
        "super_compressability_factor": Float64,
        "compressor_station_id": Int64,
        "station_name": String,
        "last_mod_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "compressor_id": "Compressor id e.g. 3",
        "compressor_name": "Compressor name e.g. Brooklyn Compressor No 4",
        "pipe_segment_id": "Pipe segment id e.g. 17",
        "min_pressure_delta": "Minimum pressure differential along segment e.g. 250.0",
        "most_efficient_pressure_delta": "Maximum efficiency at optimal pressure differential e.g. 960.0",
        "max_pressure_delta": "Max pressure differentials along a segment e.g. 1110.0",
        "max_compressor_power": "Max power available from each compressor e.g. 850.0",
        "min_compressor_power": "Min power available from each compressor e.g. 450.0",
        "compressor_efficiency": "Max efficiency of the compressor at its optimal pressure differential e.g. 68500000000000005",
        "compressor_efficiency_at_min": "Min efficiency at the least optimal pressure differential e.g. 330000000000000002",
        "efficiency_coefficient": "Coefficient for adjusting the efficiency of the compressor e.g. 1.5",
        "super_compressability_factor": "Super compressability of gas at compressor inlet e.g. 92000000000000004",
        "compressor_station_id": "Compressor station id e.g. 2",
        "station_name": "Station name e.g. Brooklyn Compressor Stage III",
        "last_mod_date": "Time last modified e.g. 10 Jun 2001 16:50:46",
        "current_date": "Time the report is produced e.g. 21 Jun 2001 16:50:46",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report contains the current compressor characteristics, and this data is
        used as input to the MCE. This public report is produced each time when a
        change occurs. Each report shows the minimum and maximum pressure change. Each
        report contains the: compressor id and name, pipe segment id, pressure and
        compressor information, station name, last modified date. Note: From 16
        December 2024, this report is decommissioned and AEMO does not produce data
        for it.
    """).strip("\n"),
    surrogate_key_sources=["compressor_id", "compressor_station_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
