from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int235_v4_sched_system_total_1",
    glob_pattern="int235_v4_sched_system_total_1*",
    schema={
        "transmission_id": Int64,
        "gas_date": String,
        "flag": String,
        "day_in_advance": String,
        "data_type": String,
        "detail": String,
        "transmission_doc_id": Int64,
        "id": String,
        "value": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "transmission_id": "Schedule Id, (0 for Administered price) - Unique identifier associated with each schedule",
        "gas_date": "Gas day of schedule (e.g. 30 Jun 2007)",
        "flag": "Schedule_Type – OS, MS, (Administered Pricing)",
        "day_in_advance": "D-2, D-1, D-0",
        "data_type": "Data type (e.g. CTLD WDLS, UNCTLD WDLS, LINEPACK, INJECTIONS, COMP FUEL USAGE, MKT PRICE HORIZON 1-5 GST EX)",
        "detail": "DAILY, EOD, MCE BOD, 10% EXCEEDANCE, NORMAL, 90% EXCEEDANCE, ADMINISTERED, ACTUAL PRICE",
        "transmission_doc_id": "Run Id, (0 for Administered price)",
        "id": "MIRN (e.g. 30000001PC), Withdrawal Zone (e.g. Ballarat), ALL COMPRESSORS, SYSTEM",
        "value": "Quantity or Price",
        "current_date": "Date/Time report produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides transparency into the operation of the wholesale gas market
        as required in clause 320 of the NGR. It is intended to provide users with a
        public summary 'snapshot' of the market and of all schedules and prices. INT235
        brings together many varied pieces of information. Users should refer to INT108
        (Schedule Run Log) to determine the specific characteristics of each schedule
        associated with a specific transmission id or transmission document id. Where
        prices have been administered, no schedule id will exist in these cases —
        therefore 0 is used as transmission id. An INT235 report is triggered each time
        a schedule is approved. It contains details for both operational and market
        schedules. The reporting window includes the current gas date, 2 days prior, and
        2 days after. For each day in its reporting window, wherever possible INT235
        will provide details of the last approved 2-day ahead, 1-day ahead, first
        approved current gas day, and last approved current gas day operational and
        pricing schedules.
    """).strip("\n"),
    surrogate_key_sources=[
        "transmission_id",
        "gas_date",
        "day_in_advance",
        "data_type",
        "detail",
        "id",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
