from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int322a_v4_uplift_breakdown_sett_1",
    glob_pattern="int322a_v4_uplift_breakdown_sett_1*",
    schema={
        "statement_version_id": Int64,
        "gas_date": String,
        "sched_no": Int64,
        "total_uplift_amt": Float64,
        "tuq_qty": Float64,
        "dts_uplift_amt": Float64,
        "final_qds_gj": Float64,
        "event_cap_rate": Float64,
        "event_liability_amt": Float64,
        "event_liability_qty": Float64,
        "annual_cap_limit": Float64,
        "annual_liability_amt": Float64,
        "annual_liability_qty": Float64,
        "net_dts_uplift_amt": Float64,
        "modified_surprise_uplift_amt": Float64,
        "modified_surprise_uplift_qty": Float64,
        "common_uplift_amt": Float64,
        "common_uplift_qty": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "statement_version_id": "Settlement statement version identifier",
        "gas_date": "Gas date in format dd mmm yyyy",
        "sched_no": "Schedule number",
        "total_uplift_amt": "Total uplift amount",
        "tuq_qty": "TUQ quantity",
        "dts_uplift_amt": "DTS uplift amount",
        "final_qds_gj": "Final QDS in GJ",
        "event_cap_rate": "Event cap rate",
        "event_liability_amt": "Event liability amount",
        "event_liability_qty": "Event liability quantity",
        "annual_cap_limit": "Annual cap limit",
        "annual_liability_amt": "Annual liability amount",
        "annual_liability_qty": "Annual liability quantity",
        "net_dts_uplift_amt": "Net DTS uplift amount",
        "modified_surprise_uplift_amt": "Modified surprise uplift amount",
        "modified_surprise_uplift_qty": "Modified surprise uplift quantity",
        "common_uplift_amt": "Common uplift amount",
        "common_uplift_qty": "Common uplift quantity",
        "current_date": "Date and Time Report Produced, e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This is a public Report, to show the breakdown of settlements issued Uplift
        payments for gas days from 1 January 2023 onwards.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "sched_no"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
