from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int348_v4_cctransfer_1",
    glob_pattern="int348_v4_cctransfer_1*",
    schema={
        "transfer_id": Int64,
        "zone_id": Int64,
        "zone_name": String,
        "start_date": String,
        "end_date": String,
        "transferred_qty_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "transfer_id": "Identifier number of the CC transfer",
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "start_date": "Starting CC product period start date. Dd mmm yyyy",
        "end_date": "Ending CC product period end date. Dd mmm yyyy",
        "transferred_qty_gj": """
            CC amount in GJ transferred in the denoted transfer id
        """,
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the approved CC transfer amounts conducted on the previous
        day.

        This report will be published on the following gas day (D+1) if a transfer of
        capacity certificates has been approved on the previous gas day. The report will
        be published at midnight. If no transfer of capacity certificates has been
        approved, the report will not be published. The report provides information
        about the amount of CC transferred for a CC zone and CC product period.
    """).strip("\n"),
    surrogate_key_sources=["transfer_id", "zone_id", "start_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
