from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int312_v4_settlements_activity_1",
    glob_pattern="int312_v4_settlements_activity_1*",
    schema={
        "gas_date": String,
        "uafg_28_days_pct": Float64,
        "total_scheduled_inj_gj": Float64,
        "total_scheduled_wdl_gj": Float64,
        "total_actual_inj_gj": Float64,
        "total_actual_wdl_gj": Float64,
        "total_uplift_amt": Float64,
        "su_uplift_amt": Float64,
        "cu_uplift_amt": Float64,
        "vu_uplift_amt": Float64,
        "tu_uplift_amt": Float64,
        "ru_uplift_amt": Float64,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "dd mmm yyyy",
        "uafg_28_days_pct": "Uafg-28-day-rolling in pct",
        "total_scheduled_inj_gj": "Total scheduled injection in GJ",
        "total_scheduled_wdl_gj": """
            Sum of total scheduled controllable withdrawals, demand forecasts and
            AEMO's over-ride in GJ
        """,
        "total_actual_inj_gj": "Total actual injection in GJ",
        "total_actual_wdl_gj": "Total actual withdrawals in GJ",
        "total_uplift_amt": "Total uplift in $",
        "su_uplift_amt": "Total surprise uplift in $",
        "cu_uplift_amt": "Total congestion uplift in $",
        "vu_uplift_amt": """
            Total common uplift resulting from unallocated AEMO's demand forecast
            over-ride in $
        """,
        "tu_uplift_amt": """
            Total common uplift from exceedance of DTSP's liability limit in $
        """,
        "ru_uplift_amt": "Total residual commin uplift in $",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to provide the market with information about settlement activity
        for the previous 12 months. Participants may wish to use this report to monitor
        market activity in the industry.

        A report is produced daily to the public with a rolling 12-month period.
        "uafg" in the second column of the report refers to unaccounted for gas shown
        in percentage. This could be due to a number of reasons, such as measurement
        errors or leakages. This report will show the "uatg" for a rolling 28-day
        period.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
