from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int316_v4_operational_gas_1",
    glob_pattern="int316_v4_operational_gas_1*",
    schema={
        "gas_date": String,
        "hv_zone": Int64,
        "hv_zone_desc": String,
        "energy_gj": Float64,
        "volume_kscm": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Date the record was current, e.g. 30 Jun 2007",
        "hv_zone": "Heating value zone id number",
        "hv_zone_desc": "Heating value zone name",
        "energy_gj": "Sum of Hourly energy (GJ) for gas date",
        "volume_kscm": "Sum of Hourly volume (kscm) for gas date",
        "current_date": "Date and Time Report Produced, e.g. 30 Jun 2005 1:23:56",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is a comma separated values (csv) file that contains details of
        operational gas (volumes in kscm and energy in GJ) by heating value zone.

        This report should be used in conjunction with the linepack report to determine
        Market participant portion of operational gas. Participants are advised to check
        the date range of the latest final settlement run to determine if the
        corresponding data in this report is: - provisional (no settlement version for
        the gas date) - preliminary (only preliminary settlement has been run for the
        gas date) - final (final settlement run for the gas date) - revision (revision
        settlement has been run for the gas date)

        This report is generated weekly on a Saturday.

        Each report contains data for the period between and including the following:
        The first gas date of the month that is 13 months prior to the current date
        and the gas date prior to the current gas date.
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "hv_zone"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
