from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int339_v4_ccauction_bid_stack_1",
    glob_pattern="int339_v4_ccauction_bid_stack_1*",
    schema={
        "auction_id": Int64,
        "auction_date": String,
        "bid_id": Int64,
        "zone_id": Int64,
        "zone_name": String,
        "start_period": String,
        "end_period": String,
        "step": Int64,
        "bid_price": Float64,
        "bid_quantity_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "auction_id": "Identifier number of the CC auction",
        "auction_date": "Auction run date. dd mmm yyyy",
        "bid_id": "Bid identifier",
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "start_period": """
            Starting CC product period representing date range period for the
            capacity
        """,
        "end_period": """
            Ending CC product period representing date range period for the capacity
        """,
        "step": "Bid step number",
        "bid_price": "CC auction bid step price",
        "bid_quantity_gj": "CC auction bid step quantity",
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the entire bid stack information without participant data
        identifying data for the current (latest) CC auction as denoted by the auction
        ID number.

        This report provides the final capacity certificate bid stack data for the
        current (latest) auction published.
    """).strip("\n"),
    surrogate_key_sources=["bid_id", "zone_id", "step"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
