from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int345_v4_ccauction_zone_1",
    glob_pattern="int345_v4_ccauction_zone_1*",
    schema={
        "zone_id": Int64,
        "zone_name": String,
        "zone_type": String,
        "from_date": String,
        "to_date": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "zone_type": "Type of CC zone. Entry/Exit",
        "from_date": "Effective from date of the zone",
        "to_date": "Effective end date of the zone",
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides a listing of the CC zones.

        This report will be regenerated when CC zone data is updated.
    """).strip("\n"),
    surrogate_key_sources=["zone_id"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
