from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int310_v4_price_and_withdrawals_1",
    glob_pattern="int310_v4_price_and_withdrawals_1*",
    schema={
        "gas_date": String,
        "schedule_interval": Int64,
        "transmission_id": Int64,
        "sched_inj_gj": Float64,
        "sched_wdl_gj": Float64,
        "price_value": Float64,
        "administered_price": Float64,
        "actual_wdl_gj": Float64,
        "actual_inj_gj": Float64,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "dd mmm yyyy",
        "schedule_interval": "(1,2,3,4 or 5)",
        "transmission_id": "Schedule ID",
        "sched_inj_gj": "Last approved scheduled injections",
        "sched_wdl_gj": """
            Last approved scheduled withdrawals including controllable withdrawals
        """,
        "price_value": "Price value",
        "administered_price": "Administered Price",
        "actual_wdl_gj": "Actual metered withdrawals",
        "actual_inj_gj": "Actual metered injections",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to show the overall statistics for gas days for the last 12
        months. Participants may wish to use this report as a market analysis tool for
        forecasting purposes, and general information for management within their
        respective organisations.

        A report is produced daily covering the previous rolling 12-month period. The
        report provides information about scheduled gas injections and withdrawals and
        actual system performance for the previous 12 months.

        Each report contains the: - gas date - schedule interval (indicating 1 to 5
        when the deviation occurred, where 1 refers to 6:00 AM to 10:00 AM, 2 will
        relate to 10:00 AM to 2:00 PM, and so forth) - transmission identifier for the
        schedule - scheduled injections in gigajoules - scheduled withdrawals in
        gigajoules - price for the scheduling horizons - Administered Price (the value
        in the admin price field is null when no admin prices applies and when there has
        been an admin price, it will be displayed and the price_value will show the last
        approved schedule price) - Actual metered withdrawals in gigajoules - Actual
        metered injections in gigajoules
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "schedule_interval"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
