from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int343_v4_ccauction_auction_qty_1",
    glob_pattern="int343_v4_ccauction_auction_qty_1*",
    schema={
        "auction_id": Int64,
        "zone_id": Int64,
        "zone_name": String,
        "zone_type": String,
        "capacity_period": String,
        "auction_date": String,
        "available_capacity_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "auction_id": "Identifier number of the CC auction",
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "zone_type": "Type of CC zone. Entry/Exit",
        "capacity_period": "Date ranged period the CC product applies to",
        "auction_date": "Auction run date. dd mmm yyyy",
        "available_capacity_gj": """
            Available capacity to bid on for opened auction in GJ
        """,
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the CC capacities available for auction by zone and period
        after the announcement that the CC auction is open.

        A report is produced when CC auction is triggered. This report will show the
        auctionable quantity for each product for a particular auction ID in csv format.
        Sort order is by Zone and Capacity Period in ascending order.
    """).strip("\n"),
    surrogate_key_sources=["zone_id", "capacity_period"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
