from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int353_v4_ccauction_qty_won_1",
    glob_pattern="int353_v4_ccauction_qty_won_1*",
    schema={
        "auction_id": Int64,
        "auction_date": String,
        "zone_id": Int64,
        "zone_name": String,
        "zone_type": String,
        "start_date": String,
        "end_date": String,
        "cc_period": String,
        "clearing_price": Float64,
        "quantities_won_gj": Float64,
        "unallocated_qty": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "auction_id": "Identifier number of the CC auction",
        "auction_date": "Auction run date. dd mmm yyyy",
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "zone_type": "Type of CC zone. Entry/Exit",
        "start_date": "Starting CC product period start date. Dd mmm yyyy",
        "end_date": "Ending CC product period end date. Dd mmm yyyy",
        "cc_period": """
            CC product period name representing date range period for the capacity
        """,
        "clearing_price": "Price in which bid cleared",
        "quantities_won_gj": "Quantity won in GJ",
        "unallocated_qty": "Quantity not won in GJ",
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the CC capacities won at auction for the published CC
        auction by zone and period.

        A report is produced on approval of the CC auction results for a CC auction
        <ID>. This report will show the CC auction results in csv format. Aggregation
        of all quantities won by all Market participants. Sort order is by Zone ID,
        calendar months for the years within auction period range.
    """).strip("\n"),
    surrogate_key_sources=["zone_id", "cc_period"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
