from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int351_v4_ccregistry_summary_1",
    glob_pattern="int351_v4_ccregistry_summary_1*",
    schema={
        "zone_id": Int64,
        "zone_name": String,
        "zone_type": String,
        "start_date": String,
        "end_date": String,
        "total_holding_gj": Float64,
        "source": String,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "zone_id": "Identifier number of CC zone",
        "zone_name": "Name of CC zone",
        "zone_type": "Type of CC zone. Entry/Exit",
        "start_date": "Starting CC product period start date. Dd mmm yyyy",
        "end_date": "Ending CC product period end date. Dd mmm yyyy",
        "total_holding_gj": "Total holding in GJ",
        "source": "Acquired source of the holding. Eg: AUCTION, DTSSP14",
        "current_date": "Report generation date. dd mmm yyyy hh:mm:ss",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides a registry of the capacity certificates allocated to each
        auction product.

        This report will provide the total capacity certificates that is allocated at
        each CC zone and period. The report aggregates the CC quantities won and paid
        for by all Market participants in a CC Auction for a CC zone and period. The
        report also provides quantities allocated by the DTS SP. This report is
        published daily at midnight.
    """).strip("\n"),
    surrogate_key_sources=["zone_id", "start_date", "end_date", "source"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
