from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int311_v5_customer_transfers_1",
    glob_pattern="int311_v5_customer_transfers_1*",
    schema={
        "gas_date": String,
        "transfers_lodged": Int64,
        "transfers_completed": Int64,
        "transfers_cancelled": Int64,
        "int_transfers_lodged": Int64,
        "int_transfers_completed": Int64,
        "int_transfers_cancelled": Int64,
        "greenfields_received": Int64,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "dd mmm yyyy",
        "transfers_lodged": "Count of mirn with Created_timestamp = gas_date",
        "transfers_completed": """
            Count of mirn, change_status = 'COM' with last_updated_timestamp =
            gas_date
        """,
        "transfers_cancelled": """
            Count of mirn, change_status = 'CAN' with last_updated_timestamp =
            gas_date
        """,
        "int_transfers_lodged": """
            Count of meter_type in ('PC', 'PD') with created_timestamp
        """,
        "int_transfers_completed": "Count of meter_type = 'PC' with last_update",
        "int_transfers_cancelled": "Count of meter_type = 'PD' with last_update",
        "greenfields_received": "Count of mirn with in a mirn_assignment_date",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This public report is to show a general overview of the total retail customer
        transfers in the market for the previous 12 months. The report provides some
        indication of the liquidity in retail churn over the past 12 months and is
        general information for management within each respective organisation.

        The report consists of a rolling 12-month period and reports transfers that
        have been lodged, completed or cancelled. This report provides an indication of
        market competition and transfer liquidity through the customer transfers.
    """).strip("\n"),
    surrogate_key_sources=["gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
