from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int439_v4_published_daily_heating_value_non_pts_1",
    glob_pattern="int439_v4_published_daily_heating_value_non_pts_1*",
    schema={
        "network_name": String,
        "gas_day": String,
        "heating_value": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_name": "Network name",
        "gas_day": "Gas day being reported e.g. 30 Jun 2007",
        "heating_value": "Heating Value",
        "current_date": "Time Report Produced e.g. 29 Jun 2007 01:23:45",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the publish heating values.

        This public report is produced daily. Only reports the non-DTS (Declared
        transmission) networks.

        Note: This report is decommissioned from December 2024.
    """).strip("\n"),
    surrogate_key_sources=["network_name", "gas_day"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
