from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int471_v4_latest_nsl_non_pts_rpt_1",
    glob_pattern="int471_v4_latest_nsl_non_pts_rpt_1*",
    schema={
        "nsl_update": String,
        "network_name": String,
        "gas_date": String,
        "distributor_name": String,
        "nsl_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "nsl_update": "Date and Time profile created",
        "network_name": "Primary Key for MIBB report",
        "gas_date": "Primary Key for MIBB report (e.g. 30 Jun 2007)",
        "distributor_name": "Primary Key for MIBB report",
        "nsl_gj": "Daily nsl energy for a DB",
        "current_date": "Date and Time report created",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the daily net system load (NSL) for each distribution area
        for a non-DTS (declared transmission system) network for the past 3 years. This
        report may be used as a reference for settlement information.

        Section 2.8.4 of the Victorian Retail Market Procedures AEMO's obligation to
        publish the NSL and Attachment 6 of the Victorian Retail Market Procedures set
        out how AEMO calculates the NSL.

        This public report is produced upon generation of NSL. It is similar to INT171
        but for the non-DTS network and has an additional column for network name.

        Each report contains the: - date and time when the NSL was created/updated -
        network name - gas date - distributor name - daily NSL energy for a
        distribution business - date and time when the report was created
    """).strip("\n"),
    surrogate_key_sources=[
        "nsl_update",
        "network_name",
        "gas_date",
        "distributor_name",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
