from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int571_v4_latest_nsl_1",
    glob_pattern="int571_v4_latest_nsl_1*",
    schema={
        "nsl_update": String,
        "network_name": String,
        "gas_date": String,
        "distributor_name": String,
        "nsl_gj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "nsl_update": "Date and Time profile created",
        "network_name": "Network name",
        "gas_date": "Gas date being reported",
        "distributor_name": "Distribution region",
        "nsl_gj": "Daily nsl energy for a DB",
        "current_date": "Date and Time report created (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is to list the Net System Load (NSL) for each distribution area for
        a rolling 3 year period. This report may be used to validate consumed energy
        produced in INT569.

        Attachment 4 of the Queensland Retail Market Procedures describes the NSL in
        further detail.

        This public report is updated daily and reflects data which is one business day
        after the gas date (Day + 1). The NSL is defined as the total injection into a
        distribution business network minus the daily metered load (ie all the interval
        metered sites). It therefore represents the total consumption profile of all the
        non-daily read meters (basic meters).

        This report is similar to VIC MIBB report INT471.

        Each report contains the: - date and time when the NSL profile was updated -
        network name - gas date - distributor name - daily NSL energy in gigajoules for
        a distribution business - date and time the report was produced
    """).strip("\n"),
    surrogate_key_sources=["network_name", "gas_date", "distributor_name"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
