from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int597_v4_injection_scaling_factors_1",
    glob_pattern="int597_v4_injection_scaling_factors_1*",
    schema={
        "network_name": String,
        "version_id": Int64,
        "gas_date": String,
        "distributor_name": String,
        "withdrawal_zone": String,
        "scaling_factor": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("ms", time_zone="UTC"),
        "ingested_date": Datetime("ms", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_name": "Network name",
        "version_id": "Null for provisional statement type",
        "gas_date": "Gas date being reported. Format dd mmm yyyy e.g. 01 Jul 2007",
        "distributor_name": "Distribution Business name",
        "withdrawal_zone": "Withdrawal zone",
        "scaling_factor": "Injection scaling factor",
        "current_date": "Date and Time report produced 15 Aug 2007 10:06:54",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report is produced for the settlement period and shows the scaling factor
        adjustments for aggregated injections in Distribution region and withdrawal
        zone.

        This public report shows the daily scaling factors used in adjusting the
        retailer injections to match the actual withdrawals in a distribution region and
        withdrawal zone. There is no equivalent VIC MIBB report.

        Each report contents the: - network name - statement version identifier - gas
        date - distributor name - withdrawal zone - scaling factor - current date
    """).strip("\n"),
    surrogate_key_sources=[
        "network_name",
        "version_id",
        "gas_date",
        "distributor_name",
        "withdrawal_zone",
    ],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
