from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int539_v4_daily_zonal_hv_1",
    glob_pattern="int539_v4_daily_zonal_hv_1*",
    schema={
        "gas_date": String,
        "hv_zone": Int64,
        "hv_zone_desc": String,
        "heating_value_mj": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "gas_date": "Gas day being reported e.g. 30 Jun 2007",
        "hv_zone": "Heating value zone as assigned by the distributor",
        "hv_zone_desc": "Name of the heating value zone",
        "heating_value_mj": "The Heating value is in MJ per standard cubic meters",
        "current_date": "Date and Time Report Produced (e.g. 30 Jun 2007 06:00:00)",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides the daily heating value for each heating value zone.
        Section 2.6.1 of the Queensland Retail Market Procedures sect the obligation
        that the Distributor is to provide the HV.

        This Heating Value report contains data for rolling 120 days. There is no
        equivalent VIC MIBB report.

        This report is generated daily. Each report displays the daily HV for each
        heating value zone in Queensland over the previous 120 gas days.

        Each row in the report provides heating values: - for a particular heating
        value zone - for a particular gas day
    """).strip("\n"),
    surrogate_key_sources=["gas_date", "hv_zone"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
