from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int898_v1_newstreetlisting_1",
    glob_pattern="int898_v1_newstreetlisting_1*",
    schema={
        "distributor": String,
        "street_name": String,
        "street_id": String,
        "street_suffix": String,
        "suburb_or_place_or_locality": String,
        "state_or_territory": String,
        "site_address_postcode": String,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "distributor": """
            Hub profile ID of the distributor providing the data (e.g. AGLGNNWO)
        """,
        "street_name": "Name of the street",
        "street_id": "Street identifier (if available)",
        "street_suffix": "Street suffix (if available)",
        "suburb_or_place_or_locality": "Suburb, place or locality name",
        "state_or_territory": "State or territory (if available)",
        "site_address_postcode": "Postcode (if available)",
        "current_date": "Report creation date and timestamp",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        This report provides a listing of all street/suburb combinations where the
        distributor is the current distributor.

        AEMO processes files sent by distributors and publishes the new street listing
        data via this public MIBB report. This process is applicable to NSW/ACT
        networks.

        The 'New Street Listing Report' is a CSV report listing all street/suburb
        combinations where the distributor is the current distributor.
    """).strip("\n"),
    surrogate_key_sources=["distributor", "street_name", "suburb_or_place_or_locality"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
    job_tags={"ecs/cpu": "512", "ecs/memory": "4096"},
)
