from dagster import AssetSpec
from humanfriendly.text import dedent
from polars import Datetime, Float64, Int64, String

from aemo_etl.factories.df_from_s3_keys.definitions import (
    df_from_s3_keys_definitions_factory,
)

defs = df_from_s3_keys_definitions_factory(
    domain="vicgas",
    name_suffix="int871_v1_erftdailynslrpt_1",
    glob_pattern="int871_v1_erftdailynslrpt_1*",
    schema={
        "network_id": String,
        "gas_date": String,
        "gas_date_historical": String,
        "nsl_mj": Int64,
        "total_meter_count_basic": Int64,
        "normalisation_factor": Float64,
        "current_date": String,
        "ingested_timestamp": Datetime("us", time_zone="UTC"),
        "ingested_date": Datetime("us", time_zone="UTC"),
        "surrogate_key": String,
        "source_file": String,
    },
    schema_descriptions={
        "network_id": "Network identifier",
        "gas_date": "Gas date being reported",
        "gas_date_historical": "Historical gas date",
        "nsl_mj": "Net section load in MJ",
        "total_meter_count_basic": "Total count of basic meters",
        "normalisation_factor": "Normalisation factor",
        "current_date": "Date and time report produced",
        "ingested_timestamp": "timestamp which the data was ingested",
        "ingested_date": "date which the data was ingested, this is time zeroed utc",
        "surrogate_key": "surrogate primary key generated by surrogate_key_sources",
        "source_file": "source file",
    },
    description=dedent("""
        The ERFTDailyNSLRpt report provides net section load and supporting data for
        each Network section, in CSV format from AEMO to Retailers. The report is
        placed in the MIBB public folder as a .csv file.

        This report is specific to NSW-ACT networks and provides information about the
        net section load, total meter count for basic meters, and normalisation factors
        for each network section.
    """).strip("\n"),
    surrogate_key_sources=["network_id", "gas_date"],
    group_name="gas_raw",
    deps=[AssetSpec(["bronze", "vicgas", "bronze_nemweb_public_files_vicgas"])],
)
